### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by deluan** [deluan/navidrome#10]
Implement a simple UI, using React-Admin with the following features:
- [x] Manage users
- [x] Simple Library Browsing
- [x] Music Player
- [x] Manage Playlists
- [x] Configuration
- [ ] ~~Rescan (with scan status indicator)~~ - covered by #130
- [ ] ~~Simple Statistics (Dashboard)~~  - maybe later

**Comment by jvoisin** [comment]
It would be nice to have a vignette-based view for artists and albums, instead of a list.

**Comment by deluan** [comment]
Something like this? :)

![Screen Shot 2020-03-05 at 10 54 00](https://user-images.githubusercontent.com/331353/76764562-6e6cb100-676b-11ea-82bb-d4382b584380.png)

This is sitting in a branch in my local environment. I'll go back to this once I finish transcoding, hopefully this week.

For artists, I may wait for the Last.FM integration, though.

**Comment by ElleshaHackett** [comment]
Just wanted to make an issue for that but saw it mentioned here already. A statistics page would be great. A few ideas for that:
- Album Count
- Artist Count
- Songs Count
- Avg. Albums per artist
- Avg. Songs per artist
- Avg. Songs per album
- Album release year bar graph with album count per year
- Count per filetype
- Count per bitrate
- Additionally if you want something very fancy I suggest to get the following metadata if possible (language of lyrics/song). If not, I suggest to analyze through NLP the predicted language of the song lyrics (if available) or the song title. That way you can show a graph of songs per language :D. https://github.com/wooorm/franc is quite good, easy to use, fast and accurate.

**Comment by jvoisin** [comment]
I'm not sure I'm comfortable adding a *ton* of dependencies just for the sake of having a per-language graph of my music. This looks like feature creep to me :/

**Comment by BobWs** [comment]
+1 for Playlist management!
Thanks for developing this keep up the great work!

**Comment by deluan** [comment]
Closing this as the UI is mostly ready for general use. If you feel there's any functionality missing, please open a separated issue for it.
