### ISSUE TITLE
Web-player idle timeout settings

### ISSUE THREAD

**Issue by bubblesnout** [deluan/navidrome#101]
While the web player in Navidrome is very simple it fits my needs perfectly. The only issue I have with it is if I have to pause for a while when I come back and press play I'm automatically logged out which is just a bit annoying.

Understandably this is a security feature, but would love it if there was a way to disable or increase this timeout to prevent this from happening.

**Comment by deluan** [comment]
This timeout is currently 30 mins after the last interaction with the UI or the last player song. If you pause for more than 30 minutes, your session will be terminated.

I'll make this timeout configurable, but still have to figure out what is the best approach. This is related to the #60 issue.

**Comment by deluan** [comment]
Now there is a new config value, "SessionTimeout". Can be set as an env var like:
`ND_SESSIONTIMEOUT="24h"`

It accepts the GoLang Duration format: https://golang.org/pkg/time/#ParseDuration

**Comment by bubblesnout** [comment]
Thanks so much for sorting this out so quickly! I've pulled the latest source and entered the ND_SESSIONTIMEOUT env var and will give it a test.

**Comment by bubblesnout** [comment]
(works like a dream, thank you!)

**Comment by githubA3B5** [comment]
> Now there is a new config value, "SessionTimeout". Can be set as an env var like:
> `ND_SESSIONTIMEOUT="24h"`
> 
> It accepts the GoLang Duration format: https://golang.org/pkg/time/#ParseDuration
> 
> This will be in the next version, release will be probably tonight or tomorrow

Please write this env into the README.md
