### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by PANOSPAP1982** [deluan/navidrome#111]
MY FRIEND HELLO!!!TELL ME PLEASE SOMETHING!FOR MAKE ONE WEB FOR SEARCHING MUSIC SONGS AND ALBUMS FROM ITUNES I NEED TO PAY SOMETHING_AND IF YES,PLEASE COULD YOU SEND ME THE LINK?

**Comment by deluan** [comment]
You can make use Navidrome to make your iTunes music (only DRM-free songs) available on the Web. Just install it and configure the ND_MUSICFOLDER to point to the iTunes media folder location. You can find where is it in iTunes preferences:

<img width="645" alt="Screen Shot 2020-03-23 at 09 11 21" src="https://user-images.githubusercontent.com/331353/77320086-4d194100-6ce6-11ea-8b58-829081896361.png">

**Comment by PANOSPAP1982** [comment]
OOOO NO MAN....I MEAN TO MAKE A WEB VERSIONS AND HAVE RESULTS MUSIC ONLY...SONG AND ALBUMS FROM API ITUNES!!!I NEED TO PAY ?

**Comment by deluan** [comment]
Once you configure Navidrome as above, it will allow you to search and listen to your music (only) through a web browser.

That's the best you can get with any non-apple software, as iTunes does not have a public API. If you want iTunes on the web, and is willing to pay, I think the best option in your case is sign-up for Apple Music and use something like https://musi.sh/

**Comment by PANOSPAP1982** [comment]
DELUAN NO MAN....I NEED ONW WEB WHERE APPEAR UNLIMITED RESULTS!!!I FOUND 15-20 WEBS BUT ALL APPEAR 200-300 RESULTS ONLY!!!PLEASE COULD YOU TELL ME IF I NEED PAY SOMETHING TO HAVE RESULTS FROM ITUNES?I MEAN MAKE ONE WEB FOR SEARCH MUSIC SONGS AND ALBUMS

**Comment by deluan** [comment]
Not sure if I understand what are you asking for. Is it related to this project at all? Have you tried Navidrome? Do you want one page with all songs from your iTunes? 

Anyway, if you want a custom solution and is willing to pay, I think it is better to try a freelance developer. Try https://www.fiverr.com/

**Comment by PANOSPAP1982** [comment]
YOU ARE VERY NICE PERSON!!!!DELUAN MY FRIEND LOOK!!!AS YOU KNOW ITUNES HAVE MILLIONS SONGS AND ALBUMS!!!BUT ALL THE PAGES WHERE I FOUND SHOWS JUST 200-300 RESULTS!!!BUT I AM SURE IF SOMEONE IS DEVELOPMENT HE CAN INCREASE UNLIMITED RESULTS!!!I LOVE SPANISH MUSIC SO MUCH...AND I WANT TO FIND ALL THE SONGS...NOT JUST 200-300 BUT THOUSANDS!!!ONE FRIEND MINE MAKE ONE WEB ON LOCAL HOST BUT SAYS THAT NOT SHOWS RESULTS!!!AND TRY FIND TO FIX IT...BUT HE DONT KNOW IF IS NECESSARY TO PAY FOR TAKE RESULTS FROM ITUNES!!!THATS WHY I ASK YOU MY FRIEND

**Comment by deluan** [comment]
Yes, I'm a developer, but unfortunately I'm not available for freelance work at the moment. As I said, I think you should try something like https://www.fiverr.com/

I'll close this issue for now, as it is not related to Navidrome. If you install it and have any questions/suggestions on how to improve it, feel free to open another issue.

**Comment by PANOSPAP1982** [comment]
THANKS SO MUCH MAN FOR YOUR HELP!!!!
