### ISSUE TITLE
Submariner does not play songs

### ISSUE THREAD

**Issue by deluan** [deluan/navidrome#116]
Browsing, playlists, covers, everything seems to be working, but it does not play songs.

**Comment by deluan** [comment]
Looks like Submariner can plays MP3/ACC just fine, but is not able to play transcoded songs, _not even from Airsonic_. 

I sent an email to its developer, but as the project seems dormant and I didn't receive any replies, I'll close this, as it is not a Navidrome bug

**Comment by villovil** [comment]
I am having the same issue. This app seems to be the most promising to be able to playback music on my MAC without using a browser but sadly I have run into this issue.
Same issue with both Airsonic and Navidrome :-(
