### ISSUE TITLE
[WebUI] display year range for albums with tracks from different years

### ISSUE THREAD

**Issue by certuna** [deluan/navidrome#118]
Many compilation albums (both multi-artist and single-artist) have songs from different years on them. So you tag them with their individual years, and that year will be used in searches, filters, smart playlists etc. That's the theory.

Navidrome does store individual years per track in its DB, but in the album view only shows the highest number. This can be fixed by not having a single Year attribute for an album, but two fields (query of the max and min of the track years) and for the UI a simple embedded if-query to display either the range ("1976-1989") or a single year.

**Comment by deluan** [comment]
Great idea, and very simple to implement. I'll work on this this weekend

**Comment by deluan** [comment]
@certuna We now have a "Year" filter in the album view. How should we apply the filter in this situation? What do you think of displaying any album that has the selected year inside the range?

**Comment by deluan** [comment]
Changes applied to master.

I'll release a new version tonight. Will close this for now, but feel free to reopen if you feel it requires more changes
