### ISSUE TITLE
Make the 'Sort' tags searchable

### ISSUE THREAD

**Issue by arg274** [deluan/navidrome#121]
Musicbrainz uses the sort fields (specifically the 'Sort Artist' and the 'Sort Album Artist' fields) to store romanised versions of the content in the 'Artist' and the 'Album Artist' fields respectively for records that use non-Latin scripts. Making these fields searchable would immensely help in navigating media that do not have romanised data in any of the main tags.

Putting the UI search aside, piping them to work with the Subsonic API might require merging the sort fields with their non-sorted counterparts as the Subsonic API does not have separate fields for the sort tags. A possible implementation can be found in a modified fork of Airsonic, named [Jpsonic](https://github.com/tesshucom/jpsonic) which specifically caters to this issue.

The Musicbrainz styling guideline, however uses the field in a `last_name, first_name` format for individual artists. The field is used as-is compared to its non-sort counterpart if it's an alias or a band name. Articles are handled differently as well (The Strokes would become Strokes, The). The complete styling guideline can be found [here](https://musicbrainz.org/doc/Style). Regardless of these factors, the comma is always the delimiter; and so it might be a possible idea to tokenise and flip the tokens based on the position of the comma, check if the resultant is the same as the non-sort counterpart, and append to the sanitised string only if it's different, which would almost certainly be the case for non-Latin tags.

Listing the fields that should be searchable:
- Sort Album Artist
- Sort Artist
- Sort Album
- Sort Title

**Comment by certuna** [comment]
I think there's two ways to tackle search really:
- 1 search box that searches/filters across all the text fields in the db (artist, album, songs, genre etc), and displays the return values subdivided by field (ie, iTunes-style)
- what navidrome has now: separate search boxes by category, so a search box for groups/persons that only searches across track artists, album artists, composers (or whatever field navidrome supports in the future) etc, a search box for "albums" that only searches the album title field, a search box for "songs", a search box for "genre", etc.

**Comment by deluan** [comment]
The 1 search box (omni search) may be introduced later. For now, I see the scope of this issue as importing the `sort_` fields and adding them to the search index. In another step (#157) is to use the `sort_` fields to actually sort the UI views. 

When importing, if the file does not have the `sort_artist` tag, it will generate one with the "remove articles" + sanitize logic. If the `sort_album` is missing, it will be generated using only the sanitize logic.

Note: Sanitize = lowercase + trim extra spaces + remove accents (and maybe special chars in the beginning of the name, configurable: https://github.com/deluan/navidrome/issues/174)

**Comment by deluan** [comment]
Hey @arg274, is there really a `sort_title` tag? I couldn't find any in my songs. Do you have a sample?

**Comment by deluan** [comment]
Fixed in #208
