### ISSUE TITLE
Add support for themes in the web interface

### ISSUE THREAD

**Issue by jvoisin** [deluan/navidrome#129]
As @deluan said:

> Because Navidrome uses Material-UI, it is just a matter of generating a new theme (a json file) and using it.

It would be nice to document this somewhere, to enable people to create/share themes, maybe done via generators like [this one]( https://cimdalli.github.io/mui-theme-generator/ ).

**Comment by deluan** [comment]
As a first step, I'll add a theme selector to the UI, and extract the two existing ones into a `themes` folder. That would allow people to contribute with PR's adding new themes.

**Comment by deluan** [comment]
I just pushed code that allows to switch from dark to light themes. 
<img width="1209" alt="Screen Shot 2020-03-31 at 09 37 22" src="https://user-images.githubusercontent.com/331353/78032678-6435df80-7333-11ea-90e8-e2fae8d828bc.png">

Next steps:
- Load the list dynamically from the themes folder
- Persist the theme selected in the localStorage
- Document how to write and contribute new themes

**Comment by deluan** [comment]
@jvoisin I moved the menu to Personal, under Settings:

<img width="788" alt="Screen Shot 2020-03-31 at 21 30 22" src="https://user-images.githubusercontent.com/331353/78090029-05a24d00-7397-11ea-9340-bdb991ba9112.png">

There's also initial documentation on how to write and contribute with new themes. Let me know your thoughts.

**Comment by deluan** [comment]
Done and merged into master
