### ISSUE TITLE
Build the Docker container to run as an unprivileged user

### ISSUE THREAD

**Issue by madcatsu** [deluan/navidrome#139]
- **As a user**: I want my container to execute as a non-root user to improve the security posture of the container by default 
- **Definition of done**: This issue is resolved when the Docker container spec builds successfully and the container runs as an alternative user to root

**Comment by deluan** [comment]
Thanks for raising this. 

This will probably be a breaking change, as the files (DB, cache) created by Navidrome with a previous image will have their ownership as root, right? 

If that is the case, we will need to add some notice/simple instructions in the release notes

**Comment by madcatsu** [comment]
Indeed they will be owned by root :/

**Comment by deluan** [comment]
As we discussed:
> If you run the container with `docker run --user $(id -u):$(id -g)`, or swap with other ID's (not by name) then it will run unprivileged.
