### ISSUE TITLE
SubStreamer (Android) is not working with Navidrome

### ISSUE THREAD

**Issue by deluan** [deluan/navidrome#144]
It connects, load all albums, artists and album artwork. But it does not display any songs when clicking on an album, and stops showing items after browsing for a while.

I tried to contact the author (Gaven Henry), but the email is bouncing... :/

**Comment by deluan** [comment]
Closing this issue as I couldn't contact the author, and last update in Play Store is from 2017...

**Comment by sm0kingm4n** [comment]
I try to contact the app dev thanks for the fantastic navidrome project and keep up the good work
