### ISSUE TITLE
Deletion does not work properly when files are deleted while Navidrome is not running

### ISSUE THREAD

**Issue by arg274** [deluan/navidrome#151]
Steps to reproduce the bug:

- Close any running instance of Navidrome
- Delete files/directories from `ND_MUSICFOLDER`
- Restart the Navidrome instance

Navidrome would fail to detect the changes and would not remove anything from its DB and they'll still be visible in the Navidrome UI upon next launch.

**Comment by deluan** [comment]
This is caused by the way Navidrome's scanner works, keeping the previous scan results in memory. This may be alleviated by #130, but I may take a look on how to improve the scanner to handle this situation

**Comment by ElleshaHackett** [comment]
Possibly, yes. What is the fix? Delete database and recreate? Or do we have some kind of "rescan full library" option somewhere?
