### ISSUE TITLE
When clicking an album it first displays the previous loaded album track list. 

### ISSUE THREAD

**Issue by mindfuucker** [deluan/navidrome#158]
It takes about 100ms but was slow enough to notice. I ran a trace in chrome devtools. You can load the .json file into devtools. 
Have a look at the difference between 1.4s and 1.48s

The screen first has to use resources to draw the old list before redrawing it with the new track list. This is sub-optimal. 

[Profile-navidrome.zip](https://github.com/deluan/navidrome/files/4458239/Profile-navidrome.zip)

**Comment by deluan** [comment]
Yeah, this is a "feature" of ReactAdmin, [optimistic rendering](https://github.com/marmelab/react-admin/blob/master/docs/Actions.md#usequerywithstore-hook), and I could not find a way to disable it.

I'll take another look at it, but any suggestions/workarounds are very welcome :)

**Comment by mindfuucker** [comment]
Setting the visibility of the list container to hidden beforehand and displaying it after filling?

**Comment by deluan** [comment]
That's a good idea, we have this information: https://github.com/deluan/navidrome/blob/656ca1f3b5b541e43f1a539fe2a3c88836ce46c7/ui/src/album/AlbumShow.js#L25
Will play with this tonight.

Ideally, there should be a property in their `<Datagrid/>` component that would disable this behaviour, but I could not find anything like that.

I'm thinking of opening a feature request on their repo.

**Comment by deluan** [comment]
Found [documentation](https://marmelab.com/react-admin/List.html#uselistcontroller) on how to create a custom <List> component. I'll be part of the next release (probably tonight)
