### ISSUE TITLE
Use ffprobe instead of ffmpeg for metadata extraction

### ISSUE THREAD

**Issue by jvoisin** [deluan/navidrome#163]
While this shouldn't change the scanning time, this would improve/simplify the codebase, since `ffprobe` is able to output json.

**Comment by deluan** [comment]
This was already implemented in the past, but removed: 

https://github.com/deluan/navidrome/blob/123f543a94361cca7694711f088edafb66c16770/conf/configuration.go#L23

It definitely would improve the codebase, but there is another issue: originally the extraction was done with `ffprobe`, but I had to move to `ffmpeg` as `ffprobe` does not allow extraction of **multiple files**, so I'd have to execute one probe command for each file!! With `ffmpeg`, I'm currently calling it once for each folder, but can potentially increase the number of probed files at once

**Comment by jvoisin** [comment]
Damn!
