### ISSUE TITLE
Playing/adding from higher level

### ISSUE THREAD

**Issue by mindfuucker** [deluan/navidrome#166]
It would be nice to be able to add/play all songs from an artist or album from the listview or album view. 

You might be able to create an on-hover dropdown animation effect over the album-art like this:
![Knipsel](https://user-images.githubusercontent.com/5075692/79073980-fe116b00-7ce9-11ea-8d41-d3ef547c8804.PNG)

**Comment by deluan** [comment]
I'm reopening this, as you still cannot access the context menu from the Artist and Album list views, only the Album grid view

**Comment by deluan** [comment]
ContextMenu adde to AlbumListView in https://github.com/deluan/navidrome/commit/3bb573b45fc6f6ab3d27f904016bc275d88e05fe

Feel free to reopen this issue if you feel the Context Menu is not enough

**Comment by mindfuucker** [comment]
Thank you very much!
It looks great

![image](https://user-images.githubusercontent.com/5075692/80861424-cb1a2180-8c6e-11ea-8f63-323640e162de.png)
