### ISSUE TITLE
Request to add Chinese language support

### ISSUE THREAD

**Issue by ye61123** [deluan/navidrome#185]
Hello, dear developer, I used docker to deploy this service. I think it performs well. Thank you! Could you consider adding Chinese language support? I think Google translation can be used. I can also help.

**Comment by deluan** [comment]
I added support for translation yesterday!! 

Do you have basic JS skills? If you want to contribute, take a look at the initial documentation: https://www.navidrome.org/docs/developers/translations and let me know if you need more information.

**Comment by ye61123** [comment]
Ha ha, I'm an automation major. I don't know JS very well, but I can try it.😃

**Comment by deluan** [comment]
I've just add more content to the doc page. If you want to accept the challenge, join our [Discord server](https://discord.gg/xh7j7yF) and I can help you with any questions you may have.

**Comment by deluan** [comment]
I added your translation file in commit f6617ff. I will release a new version this weekend, but if you use Docker, you can get the develop version sooner, in about 1 hour.

Let me know if it is correct so I can close the ticket

**Comment by ye61123** [comment]
OK, let me try it

**Comment by deluan** [comment]
Hey @ye61123 Are you satisfied with the Chinese translation? Are you planning to change anything? Let me know so I can close this issue

**Comment by ye61123** [comment]
Ha ha, I think there are still some small problems, but I'll fix it later. I'm doing my graduation project recently.😃

**Comment by ye61123** [comment]
I think you can close this issue

**Comment by deluan** [comment]
Ok. If you want to change anything, just create a PR. Thanks for the translation

**Comment by ye61123** [comment]
Not at all. I am glad to have a chance to Participate in translation😃
