### ISSUE TITLE
Support for symlinks

### ISSUE THREAD

**Issue by cascooscuro** [deluan/navidrome#193]
Hi,

Would it be possible to add support for symlinks?

Thanks!

**Comment by deluan** [comment]
I'll take a look at this this week

**Comment by deluan** [comment]
Hey @cascooscuro , I'm assuming by "support for symlinks" you mean Navidrome following any folder symlinks found in your music library folder, is that right? I.e. if you have the following setup:

Your config:
`ND_MUSICFOLDER=/music`

You have a symlink `/music/someotherfolder` pointing to `/folder`

`/folder` has two files: `/folder/file1.mp3` and `/folder/file2.mp3`

Navidrome should add the files to the library, found in the paths:
`/music/someotherfolder/file1.mp3` and `/music/someotherfolder/file2.mp3`

Is that the expectation of this request?

**Comment by cascooscuro** [comment]
> 
> 
> Hey @cascooscuro , I'm assuming by "support for symlinks" you mean Navidrome following any folder symlinks found in your music library folder, is that right? I.e. if you have the following setup:
> 
> Your config: `ND_MUSICFOLDER=/music`
> 
> You have a symlink `/music/someotherfolder` pointing to `/folder`
> 
> `/folder` has two files: `/folder/file1.mp3` and `/folder/file2.mp3`
> 
> Navidrome should add the files to the library, found in the paths:
> `/music/someotherfolder/file1.mp3` and `/music/someotherfolder/file2.mp3`
> 
> Is that the expectation of this request?

That's exactly my use case. Thanks!
