### ISSUE TITLE
Recently Added Albums

### ISSUE THREAD

**Issue by bubblesnout** [deluan/navidrome#201]
Is it possible to add a "Recently Added Albums" section somewhere? I often add new music to my collection in batches and then forget what some of it was, so I use the "Recently Added" lists in the various music clients I use. I'm starting to do all my listening directly via the Navidrome web-UI so having this would be brilliant.

Ideally this list would be ever-growing so you can scroll back as far as you want, effectively listing out all albums in the order they were added to the library (newest first).

**Comment by bubblesnout** [comment]
Okay so I actually just realised that when you choose the "Album" view this is exactly what it does, it's showing the most recent albums added to my library first. Personally this does exactly what I'm after so I'm happy with that. If you did want to add a separate section for Recently Added Albums I can't imagine it looking much different, just perhaps listing the date each album was added.

Interested to see what you come up with, happy to find out that the album grid view is already ordering things this way though!

**Comment by deluan** [comment]
Yeah, I didn't mention this in my original reply because right now there's a bug in this behaviour: if you click on an artist in the Artist list, it will show all their albums in _chronological_ order. After that, the order of the Albums view is changed and will not go back to _recently added_ order, until you refresh the browser window... Far from ideal :(

**Comment by bubblesnout** [comment]
Hmm that's interesting, I've just had a bit of a click around and I'm not able to replicate that behaviour. I go in to any artist with multiple albums, confirm that it's displaying in chronological order (based on release date), go back to the album view and they are still showing most recently added albums first.
