### ISSUE TITLE
Combine Albums with songs from multiple Artists

### ISSUE THREAD

**Issue by nebula-it** [deluan/navidrome#203]
First of all thank you a lot for navidrome. We really need a good (and modern) selfhosted music server and this is heading in right direction.

Now to the issue, is it possible to combine albums that have songs from different artists? Right now if an Album has songs from say 4 artists, I'm seeing that album 4 times in Album page but it would be ideal if it just showed up as 1.

**Comment by certuna** [comment]
That should work if they're tagged correctly:
- Album Artist either empty for all, or the same (eg "Various Artists") for all 4 songs
- Part Of Compilation = Yes

**Comment by deluan** [comment]
Hey @nebula-it , as _certuna_ said, this should be working.  What tagger are you using? Can you confirm the tracks have one of the options above set?

**Comment by nebula-it** [comment]
I tried that, if I set "Album Artist" to "Various Artist" then it shows up as single album but issues with this is under artist section it shows up as Various Artist instead of individual artist names.
If I leave "Album Artist" field empty it shows up 4 individual albums. And even turning the Compilation ON in Album page did not combine those infact nothing showed up then.

**Comment by certuna** [comment]
It's not turning compilations on in navidrome, it's tagging the files with Compilation = Yes. What do the tags look like? Should look like this (Album Artist empty, "Compilation" box ticked):
![Screenshot 2020-04-24 at 09 34 00](https://user-images.githubusercontent.com/62144283/80186739-c9b57d00-860e-11ea-97e2-cc958a8173fb.png)

**Comment by nebula-it** [comment]
That works, kinda. Now the album is showing up under "Various Artists" in artist page so thats good but is it possible for it to show up under each artist as well that has a song in that album? (Maybe its my misunderstanding of how ID3 tags work coming from streaming services, its been long time since I handled my own local music library)
Also some of the songs in that album have two artists, which are a comma separated and are in tag "Artist" (or Contributing Artist in Windows). Do you know if that is treated as two artists e.g does it understand that there are two artist named Artist1 and Artist2 or doe it think its one artist named "Artist1, Artist2"?

**Comment by certuna** [comment]
Yes these are valid points:

- putting compilation artists in the Artist list is a bit of a hot item. Personally I'm in favour of doing this, but loads of people don't like their Artist list cluttered up with lots of one-song artists. Most other music library managers like iTunes/Music and Plex for example exclude them.
- Multiple artists or genres per song has been discussed here: https://github.com/deluan/navidrome/issues/131#issuecomment-608993601 , one problem why this is difficult for everyone is there's not really a agreed on standard separator for it. Some use `,` (but how do you prevent accidental splitting of the artist "Earth, Wind & Fire"?), some use `;` or `/` and yet others want support for separators like `feat.` or `featuring` or `vs.` or `presents`.

**Comment by deluan** [comment]
> That works, kinda. Now the album is showing up under "Various Artists" in artist page so thats good but is it possible for it to show up under each artist as well that has a song in that album? (Maybe its my misunderstanding of how ID3 tags work coming from streaming services, its been long time since I handled my own local music library)
This will be implemented at some point: https://github.com/deluan/navidrome/issues/94#issuecomment-613551121

> Also some of the songs in that album have two artists, which are a comma separated and are in tag "Artist" (or Contributing Artist in Windows). Do you know if that is treated as two artists e.g does it understand that there are two artist named Artist1 and Artist2 or doe it think its one artist named "Artist1, Artist2"?
As _certuna_ explained, this is really hard and will probably not be done for artists. But this will be implement for genre: https://github.com/deluan/navidrome/issues/131#issuecomment-618690156

**Comment by nebula-it** [comment]
> This will be implemented at some point: #94 (comment)

Thank you. Good to know that its coming.

> As certuna explained, this is really hard and will probably not be done for artists. But this will be implement for genre: #131 (comment)

I see, if its not too much work for you I would love to see an option to use a custom character as separator for Artists as well. It will be up to end users to make sure their library is tagged correctly or they can disable this entirely. But always good to have options.

**Comment by deluan** [comment]
@nebula-it, that's a good idea, not sure when I'll be able to work on it, though.

I'll close this issue now, but can you please describe the idea in another issue so we don't lose track of it?

Thanks!
