### ISSUE TITLE
Artists with lowercase first letter pushed to bottom of list

### ISSUE THREAD

**Issue by bubblesnout** [deluan/navidrome#206]
Hopefully a simple one, I have a few artists that are tagged in all lowercase as that's how they generally stylise their name (eg. blink-182, far, sleepmakeswaves) and currently these are all listed at the end after "Z". It would be great if the sorting wasn't case-sensitive.

**Comment by deluan** [comment]
This is being taken care in #174. I'm closing this in favour of that one. Please subscribe to #174

**Comment by deluan** [comment]
This is also a duplicate of https://github.com/deluan/navidrome/issues/157
