### ISSUE TITLE
Web App doesn't load

### ISSUE THREAD

**Issue by ElleshaHackett** [deluan/navidrome#214]
Looks like a great app, well documented and way better designed than all others I know. I would love to use it and started it with almost the bare docker-compose template as provided in the documentation. I only changed the volumes. 

My docker-compose looks like this:

```
version: "3"
services:
  navidrome:
    container_name: navidrome
    restart: unless-stopped
    image: deluan/navidrome:latest
    ports:
      - "4533:4533/tcp"
    environment:
      # All options with their default values:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_SCANINTERVAL: 1m
      ND_LOGLEVEL: info
      ND_PORT: 4533
      ND_TRANSCODINGCACHESIZE: 100MB
      ND_SESSIONTIMEOUT: 30m
      ND_BASEURL: ""
    volumes:
      - "/media/user/disk_002/docker_volumes/navidrome:/data"
      - "/media/user/disk_002/datastore1/music:/music:ro"
```

I started it like this:

`docker-compose -f /media/user/disk_002/docker_commands/navidrome.yaml up -d`. My host OS  is Zorin OS 15.2 bionic, which is basically Ubuntu/Debian.

The docker logs show that it can access both volumes. It scans the music folder and adds stuff to it's own data folder. Here is a part of my log:

```
                           Version: 0.16.0 (47311d1)
time="2020-04-25T17:21:23Z" level=info msg="Creating DB Schema"
2020/04/25 17:21:23 OK    20200130083147_create_schema.go
2020/04/25 17:21:23 OK    20200131183653_standardize_item_type.go
2020/04/25 17:21:23 OK    20200208222418_add_defaults_to_annotations.go
2020/04/25 17:21:23 OK    20200220143731_change_duration_to_float.go
2020/04/25 17:21:23 OK    20200310171621_enable_search_by_albumartist.go
2020/04/25 17:21:23 OK    20200310181627_add_transcoding_and_player_tables.go
2020/04/25 17:21:23 OK    20200319211049_merge_search_into_main_tables.go
2020/04/25 17:21:23 OK    20200325185135_add_album_artist_id.go
2020/04/25 17:21:23 OK    20200326090707_fix_album_artists_importing.go
2020/04/25 17:21:23 OK    20200327193744_add_year_range_to_album.go
2020/04/25 17:21:23 OK    20200404214704_add_indexes.go
2020/04/25 17:21:23 OK    20200409002249_enable_search_by_tracks_artists.go
2020/04/25 17:21:23 OK    20200411164603_add_created_and_updated_fields_to_playlists.go
2020/04/25 17:21:23 OK    20200418110522_reindex_to_fix_album_years.go
2020/04/25 17:21:23 OK    20200419222708_reindex_to_change_full_text_search.go
2020/04/25 17:21:23 OK    20200423204116_add_sort_fields.go
2020/04/25 17:21:23 goose: no migrations to run. current version: 20200423204116
time="2020-04-25T17:21:23Z" level=info msg="Creating Image cache" maxSize="100 MB" path=/data/cache/images
time="2020-04-25T17:21:23Z" level=info msg="Creating Transcoding cache" maxSize="100 MB" path=/data/cache/transcoding
time="2020-04-25T17:21:23Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music
time="2020-04-25T17:21:24Z" level=info msg="Creating default transcoding config" name="mp3 audio"
time="2020-04-25T17:21:24Z" level=info msg="Creating default transcoding config" name="opus audio"
time="2020-04-25T17:21:24Z" level=warning msg="Running initial setup"
time="2020-04-25T17:21:24Z" level=warning msg="Creating JWT secret, used for encrypting UI sessions"
time="2020-04-25T17:21:24Z" level=info msg="Starting scanner" interval=1m0s
time="2020-04-25T17:21:24Z" level=info msg="Mounting routes" path=/rest
time="2020-04-25T17:21:24Z" level=info msg="Mounting routes" path=/app
time="2020-04-25T17:21:24Z" level=info msg="Navidrome server is accepting requests" address=":4533"
time="2020-04-25T17:21:26Z" level=info msg="Folder changes found" numChanged=21 numDeleted=0

// a line per added folder

time="2020-04-25T17:21:39Z" level=info msg="Finished Music Folder" elapsed=13.95122695s folder=/music
```

So by the looks of it there are not errors. I can access the http://192.168.178.10:4533/app/#/ but it shows me an empty white page. When I checkout the Source I do see the source-code of the app, network tab doesn't show any errors such as 404 and properly load all files. But the console does show two errors:

![image](https://user-images.githubusercontent.com/5116641/80286370-5190a980-872b-11ea-91a7-59797c88f431.png)

I tried several browsers Chrome, Firefox, Edge. Did I do something wrong or is this a bug?

**Comment by deluan** [comment]
Ops, I think you found a bug. Let me check

**Comment by ElleshaHackett** [comment]
Thanks for the quick response :). Also, the music library I test with isn't that big but it consists only of FLAC files. Is that actually supported? And is it streaming in original format or transcoding everything?

**Comment by deluan** [comment]
Fixed. A new version will be available in the next hour.

Yes, FLAC is a first-class citzen :) And by default Navidrome does not transcode anything

**Comment by ElleshaHackett** [comment]
Great I will remove the container and try again in an hour. 

> Yes, FLAC is a first-class citizen

Great, can't wait. Was already thinking for some time to develop something like this myself out of frustration of the crap tools available. That must have been your motivation to start also. I will test it out soon.

**Comment by deluan** [comment]
Yes, that was one of my motivations. I'm always open to contributions. If you want to participate, join our Discord channel.

**Comment by ElleshaHackett** [comment]
Sure, thanks. I will test a bit first but my impressions are very good judging by docs, screenshots, scanning speed, choice of tech: go/react, containerization (docker) and your quick fix, although sad it was in a stable release ;). I might contribute somehow.

**Comment by ElleshaHackett** [comment]
I was waiting for aging for the "Plex of Music" of "open-source Spotify" 👍
