### ISSUE TITLE
Files are not deleted from index when moved

### ISSUE THREAD

**Issue by ElleshaHackett** [deluan/navidrome#221]
I just moved a bunch of files from one to another directory. The file change was detected and the "newly discovered" files where added. But the files on the non-existing "old location" were not removed from the index. Now I have a lot of files double in my index.

**Comment by deluan** [comment]
This can happen if Navidrome was not running when you moved the files. Was it the case? 

See #151

**Comment by ElleshaHackett** [comment]
Possibly, yes. What is the fix? Delete database and recreate? Or do we have some kind of "rescan full library" option somewhere?

**Comment by deluan** [comment]
One possibility for now is to drop the DB and start fresh.

Rescan full library is in the backlog https://github.com/deluan/navidrome/issues/130#issuecomment-606957522 Take a look there to see some alternatives, if you don't want to drop the DB

**Comment by ElleshaHackett** [comment]
Thanks. Fresh start if fine for now. Good it's already on the backlog.
