### ISSUE TITLE
Setting to choose personal start page

### ISSUE THREAD

**Issue by ElleshaHackett** [deluan/navidrome#228]
It would be great if a user has a personal option on which page to start after login. Artists / Albums / Song.

I would personally start with the Albums page in Grid mode where you see all album covers. Its probably the most fancy page. So that would require to select the page mode too. A default Grid or List view.

**Comment by deluan** [comment]
Agree, this would be cool.

**Comment by deluan** [comment]
This was implemented in #423. Now that we have multiple views for albums, a personal preference allows you to select which one is the default
