### ISSUE TITLE
Privacy and GUI improvement on login screen

### ISSUE THREAD

**Issue by ElleshaHackett** [deluan/navidrome#239]
I love the random unsplash background on the login screen. Great idea. But they load slow. In order to fix that, I suggest that we download two the first time Navidrome is opened. One to show, one to cache for the next time. Then every time when the login page is opened (please protect against massive refreshes in a short time) cache a new one for the next time and use the previously cached to show. This way, it's always locally served which is faster and still random every time. Also maybe you can improve the client-side caching with something like preloading in browser or load the "next" wallpaper already in background (hidden) in the browser so it's cached for the next time before the user even saw it. Now, I'm looking one or two seconds at an empty background before the beautiful background appears.

_Also, if you do use server-side caching and it isn't too much work and requires no or minimal dependencies, you could maybe optimize the image (jpg/progressive/80%) for example to load faster as well, but that's quite out of scope and not really necessary._ 

Lastly, I've read in another issue that out of privacy reasons you want to be able to disable the (upcoming) lastfm integration, great idea. I suggest we add a "privacy" section in the settings page that also allows to set a static/default background instead of the random unsplash one. That way no external connection is initiated every time someone hits the login screen.

_Apart from some security testing, I will also keep privacy in mind and possibly suggest more things_

**Comment by deluan** [comment]
The background image is a client-side only feature, the UI downloads the image directly from Unsplash.

TBH, I'm not changing it anytime soon, but feel free to contribute :)

Re: Privacy, this image can already be disabled/changed with the `ND_UILOGINBACKGROUNDURL` [configuration option](https://www.navidrome.org/docs/usage/configuration-options/). It can even be set to a `data` URL, containing a embedded image [for example](https://github.com/deluan/navidrome/pull/154).

**Comment by deluan** [comment]
For privacy reasons, I rather keep the image download client-side only. And as I said, there's already a way to disable the integration with Unsplash.

 I'll close this issue, as this didn't get any traction (no other users chimed in).
