### ISSUE TITLE
Logo on login page and fancy load animation?

### ISSUE THREAD

**Issue by ElleshaHackett** [deluan/navidrome#247]
I suggest to replace the Lock Icon with the Logo (currently only as Favicon) for branding purposes.

Lock Icon:
![image](https://user-images.githubusercontent.com/5116641/80483571-9a787600-8956-11ea-976b-be60b6614e1a.png)

Favicon:
![image](https://user-images.githubusercontent.com/5116641/80483674-c693f700-8956-11ea-8e2e-b02485d5002f.png)

I made a small animation as a test: http://jsfiddle.net/j4s7rtyx/ with just some image, not the Navidrome logo. I thought it might be a cool "start-up" animation for the login page. It flips it one second and then stops again. The animation is optional of course.

**Comment by deluan** [comment]
Will see what I can do, but I don't want to spent too much time working on logo-related things, as this is not the definitive Navidrome logo, just an image I'm using as "placeholder"
