### ISSUE TITLE
Animate display on-hover albumview

### ISSUE THREAD

**Issue by mindfuucker** [deluan/navidrome#262]
The newly implemented context-menu are a great improvement and I really like it.

I only think the amount of text clutters the view a bit. It would be nice to animate an on-hover event. Maybe only on desktops as hover events on mobile are not very functional.

```
.MuiGridListTileBar-root{
    display: none;
    transition: all .2s ease-in-out;
}
.MuiGridListTileBar-root:hover{
    display: flex;
    transition: all .2s ease-in-out;
}
```

**Comment by deluan** [comment]
Yeah, I tried it before, but I couldn't get it right. Just tried adding your suggestion to the GridListTileBar and it didn't work:

`ui/src/album/AlbumGridView.js#L20`
```js
  tileBar: {
    display: 'none',
    transition: 'all .2s ease-in-out',
    '&:hover': {
      display: 'flex',
    },
    textAlign: 'left',
    background:
      'linear-gradient(to top, rgba(0,0,0,1) 0%,rgba(0,0,0,0.4) 70%,rgba(0,0,0,0) 100%)',
  }
```

The code above only hides the TileBar. The syntax is based on this answer: https://stackoverflow.com/a/52597084/653632

Will do more investigation. If you can come up with something, let me know

**Comment by deluan** [comment]
Fixed on https://github.com/deluan/navidrome/commit/86a9f9e4105dcaff72213cfeb0cdb8179a6c4c95
