### ISSUE TITLE
Sorting order for the track number is lexigraphic instead of being numeric

### ISSUE THREAD

**Issue by jvoisin** [deluan/navidrome#273]
![xxx](https://user-images.githubusercontent.com/325724/81273790-f326cd80-903e-11ea-9e52-e23c7ee412d7.png)

It would be nice to have 1 before 10 :)

**Comment by deluan** [comment]
As we discussed, this is sorted lexicographic by `discnumber, tracknumber`, so this is probably caused by a wrong discnumber tag. Can you confirm, please?

**Comment by jvoisin** [comment]
Yup, it's due to an error in my tags, my bad.
