### ISSUE TITLE
 Problem on the track number sorting column

### ISSUE THREAD

**Issue by diyfr** [deluan/navidrome#282]
On a compilation album, I had three songs with a different tag than on the rest of the album (name of Album artist).  
So in Navidrome I see four albums. **Correct**.  
I change the tag on these three songs.  
In Navidrome I only see one Album. **Nice** !  

Problem :
When I click on the track number column, the order is not respected   

Question :
The artists' index is created from the album(albumartist) not the track(artist)  ?  
In this example can't find The Eagles  
![Capture](https://user-images.githubusercontent.com/12012402/81398744-1bd7c180-912a-11ea-8944-2870783fbbe0.PNG)

**Comment by deluan** [comment]
- Tracks out of order: When sorting by `track #`, the actual sort used is `disc#/track#`, you may have a wrong `disc #`. See #273 and please confirm this is your case

- Yes, right now Navidrome only indexes album artists. Please see #211

**Comment by diyfr** [comment]
Indeed problem on one of the tags:  DISCNUMBER -> [TPOS(id3v2)](https://help.mp3tag.de/main_tags.html)  
Nice !   Thanks
