### ISSUE TITLE
Add a way to download albums/discography

### ISSUE THREAD

**Issue by jvoisin** [deluan/navidrome#285]
It would be nice to be able to download whole albums in .zip, or even the whole discography from an artist.

**Comment by deluan** [comment]
Yes. Song download is already available in the Subsonic API, but I agree this should be available in the UI, with artist/album(s) and song(s) options

**Comment by deluan** [comment]
The Subsonic API must also support downloading whole albums, even though the documentation says it is only meant for media files.

**Comment by deluan** [comment]
Implemented in the Subsonic API: https://github.com/deluan/navidrome/commit/2c370cae28e866c90dd874ee87a7409ff360187e#diff-517d76af3b14f4a39ae5e86c25a093daR47

You can even download full discographies by passing the `album_artist_id` as the id parameter to the `download.view` endpoint.

To close this, we need to add to the Web UI options in the album context menu, and find a way to add this to artists, as Navidrome currently does not have an artist context menu

**Comment by deluan** [comment]
Web UI now has option to download full albums: 38c19eddc36dfbc1195cd4e8d8ef41d892d11d79
<img width="449" alt="Screen Shot 2020-08-05 at 3 53 28 PM" src="https://user-images.githubusercontent.com/331353/89457737-d714f400-d733-11ea-9282-7da99acb773b.png">
And:
<img width="431" alt="Screen Shot 2020-08-05 at 3 53 16 PM" src="https://user-images.githubusercontent.com/331353/89457740-d8462100-d733-11ea-98b4-4d331b43d3c0.png">

I may implement the artist's discography download before next release, if time permits

**Comment by deluan** [comment]
This is now complete, all download options are available in release 0.30.0

**Comment by steifhahn** [comment]
Hi deluan. Is there an option to deactivate it for the web UI?

**Comment by deluan** [comment]
> Hi deluan. Is there an option to deactivate it for the web UI?

See `EnableDownloads` in [Configuration Options](https://www.navidrome.org/docs/usage/configuration-options/)

**Comment by steifhahn** [comment]
I have

ND_ENABLEDOWNLOADS: "false"   

in file docker-compose.yml

but it is not working. If i put in without ““ then an error is thrown from docker. 

Mit freundlichen Grüßen


Stefan Förster

**Comment by deluan** [comment]
Change LogLevel to "debug". Check if it shows the `EnableDownlods` config as false in the logs:
```
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                                        Version: dev

Loaded configuration from '/Users/deluan/Development/navidrome/navidrome.toml': &conf.configOptions{
    ...
    UILoginBackgroundURL:       "https://source.unsplash.com/random/1600x900?music",
    EnableTranscodingConfig:    true,
    EnableDownloads:            false,
    TranscodingCacheSize:       "100MB",
    ...
 ```
 
 Also make sure you force-refresh the UI, then you should see a message like this in the logs, showing the downloads are disabled:
 ```
 DEBU[0018] UI configuration                              appConfig="map[baseURL: devActivityPanel:true devFastAccessCoverArt:true enableDownloads:false enableTranscodingConfig:true firstTime:false gaTrackingId: loginBackgroundURL:https://source.unsplash.com/random/1600x900?music version:dev welcomeMessage:Use \u00a0 <i>demo/demo</i>]"
```

If you still see the "Download" options in the UI after confirming `EnableDownloads` is false in these two places, please open a new issue here in GH, as it is a different issue.

**Comment by steifhahn** [comment]
Ok download is disabled. But the web shows the possibility to download. i thought this option is not shown anymore.


Mit freundlichen Grüßen


Stefan Förster

**Comment by deluan** [comment]
The option to Download from the UI should not show up if `EnableDownlods=false`. Make sure you are not seeing a cached version in the UI (clear the browser's cache or use Shift-Ctrl-R to force refresh the page) 

It it still does not work, please open a new GitHub issue, as this one is closed and was resolved a while ago

**Comment by steifhahn** [comment]
ahhh the cache.

THX.

now its fine

Mit freundlichen Grüßen


Stefan Förster
