### ISSUE TITLE
Ability to star and view tracks or artists from WebUI

### ISSUE THREAD

**Issue by axllent** [deluan/navidrome#287]
It would be great to be able to star tracks or albums in the WebUI, and also to be able to view all starred items. I use DSub (Android) which has a cool polling auto-sync feature for all starred items. The server appears to support starring from what I can see, so I'm assuming this is simply a lacking frontend feature? 

Also thanks for the awesome project!

**Comment by deluan** [comment]
Yes, this is lacking in the UI, but is fully implemented in the server. I love this feature from DSub as well. I'll add this after the work with playlists in the UI are done

**Comment by axllent** [comment]
Thanks so much @deluan for the recent additions to include this. I'm not sure if I should leave this "issue" open, or close this and open different related feature request, so I'll just put my ideas here for now.

1. It would be great to access the starred items in an easier manner rather than having to filter by them, ie: a `Starred` menu on the left in the WebUI if anything is starred (where it says `Albums`, `Artists`, `Songs` & `Playlists`), even if it is just a shortcut to the current search/filter. Not too serious though.
2. The ability to add starred items to the current playlist in **random** order (ie: play a random selection of my favorite songs or albums).

Relating to 2, one of the most used features I use from Airsonic (which I want to migrate away from due to ... well Java & its overheads) is the ability to "Shuffle play" from pretty much any location, including starred, albums, songs etc, and of course from random albums:

![Screenshot from 2020-06-01 16-03-56](https://user-images.githubusercontent.com/1463435/83375181-22eca980-a422-11ea-9a55-52c1c099f03a.png)

Are there any plans for something similar? 

Thanks again for all your hard work - this project is coming together very nicely. Hopefully I can work out a way to "migrate" my 1,300+ favorite songs from Airsonic without having to manually add them all again at some stage (ie: what is currently synced on my phone via dsub). I don't expect you to write a solution, but you may have some ideas as to how best do this.  I note that one can export an *.m38u file (from Airsonic) of a playlist (eg: from starred songs), so I may start with that and parse the list (plain text) and maybe do some sqlite commands to try "star" them in the Navidrome sqlite DB.

**Comment by deluan** [comment]
Thanks for the feedback. I didn't close this before because the work is not done yet, what I did was just a quick break from the playlists implementation. 

Regarding your ideas:
1. Yes, this will be implemented when I tackle this GH issue. Just have to figure out a good UX, because I also want to add Album Lists (random, recently played, starred, recently added, etc...)

2. Yes, I plan to add "shuffle all" in as many places as possible. What you can do for now is, after adding all songs you want to play in the play queue, change the play mode to "Shuffle":

![Kapture 2020-06-01 at 22 57 54](https://user-images.githubusercontent.com/331353/83474997-5f88c700-a45b-11ea-953b-ec7bccc9f6f4.gif)

**Comment by deluan** [comment]
@axllent Just an update: I just added options to star and filter by star Artists and Albums. It will be part of this weekend's release. 

Not sure if you saw the latest release, but I also added a "shuffle all" button in the Songs list. Next is adding "shuffle all " in more places

**Comment by axllent** [comment]
@deluan I sure did! I didn't want to comment and ask whether you were done with that (or whether there was more coming) because the issue was still open, and because I didn't want to nag :-) It's awesome so far, well done!

**Comment by deluan** [comment]
Forgot to mention: Re: migrating from other *sonic servers, @peguerosdc created a python script to do that: https://github.com/peguerosdc/subimporter

**Comment by axllent** [comment]
Excellent, thank you! One request regarding starting is the ability to star songs in the current playlist. When I play random songs I like to star the ones that are playing when I hear them. This is useful when listening to a new album etc, and not have to search for the song separately each time in the music library, thanks!

**Comment by deluan** [comment]
I'm closing this as the original issue is already resolved: You can now start artists, albums and tracks from the UI and from the API. 

Regarding the other items discussed in this thread: 
- "Shuffle All" in more places: #456 
- Ability to star current playing song. It is coming: #467
