### ISSUE TITLE
On-demand scanning support

### ISSUE THREAD

**Issue by delucks** [deluan/navidrome#293]
This would look like an implementation of Subsonic's `getScanStatus` and `startScan` APIs, which return a simple status like this:

```
{
   "subsonic-response" : {
      "status" : "ok",
      "version" : "1.15.0",
      "scanStatus" : {
         "scanning" : true,
         "count" : 51
      }
   }
}
```

I don't think any of the other routes so far access the scanner so this may need a bit of refactoring if two scans cannot run concurrently.

**Comment by deluan** [comment]
Thanks for reporting it. Yes, this requires some refactoring to the current scanner, making it a proper service. 

We already have a ticket for this: https://github.com/deluan/navidrome/issues/130, so I'll close this one to have all the suggestions/comments in one place.
