### ISSUE TITLE
Import breaks with single quote characters in the song title

### ISSUE THREAD

**Issue by Xyv** [deluan/navidrome#294]
Hello,

First I'd like to thank you for your work on this awesome project!

I've encountered some hiccup when trying to import part of my music library:
Whenever there's a single quote character (`'`  or it's escaped version `\'`)  the import breaks with respectively:

```
level=error msg="Error importing MediaFolder" error="readdirent: no such file or directory" folder=/music
```
```
level=error msg="Error importing MediaFolder" error="readdirent: interrupted system call" folder=/music
```

While this is not too bad in itself (I can rename the problematic files), the confusing part is that even if renaming/removing those files navidrome won't continue the import process: same error message appears each time the process is run
This is true...even when nuking the data folder containing the db and restarting the container (I'm using the docker version).
Only way to have the import properly restart is to remove the container + data folder + problematic files and then recreate the container.

Steps to reproduce:

- Configure the container like in the documentation.
- Have files in the mounted music volume with either `'` or `\'` in their names .
- Wait for the import error.
- Stop the container.
- Nuke the mounted data folder.
- Move/remove the problematic files.
- Restart the container.
- Import still errors out.

Just for reference here's the whole trace output I have in the docker logs:
```
level=trace msg="SQL: `SELECT value FROM property WHERE id = ?`" args="['LastScan-/music']" elapsedTime="523.329µs" rowsAffected=1
level=debug msg="Scanning folder" folder=/music lastModifiedSince="2020-05-13 14:49:30.835 +0000 UTC"
level=error msg="Error importing MediaFolder" error="readdirent: no such file or directory" folder=/music
level=trace msg="SQL: `UPDATE property SET value = ? WHERE id = ?`" args="['1589381430937','LastScan-/music']" elapsedTime="469.788µs" rowsAffected=1
level=error msg="Errors while scanning media. Please check the logs"
level=error msg="Error scanning media folder" error="errors while scanning media" folder=/music
```

I guess the errors are due to the characters not being properly escaped when inserting/retrieving to/from the db, but I am really confused by the fact that deleting the db and problematic files don't work.

**Comment by deluan** [comment]
I'm not sure if the issue you are experiencing is related to the quote char. I have files with both single and double quotes in my library, and don't have this issue. Ex:

<img width="1431" alt="Screen Shot 2020-05-13 at 10 33 51 PM" src="https://user-images.githubusercontent.com/331353/81886280-467eab80-956a-11ea-9bcc-4fc146110c67.png">

Can you please change the log level to `trace` leave only the problematic file in place and try again? Then send me the full log.

Thanks for the report and for trying Navidrome.

**Comment by Xyv** [comment]
You are right, this is not linked to the quote char, it appears to have been a coincidence. After some more testing this is more probably due to my library being on a cifs mount.

I was not able to reproduce the problem with a local folder, though it always happens if I import from my smb share. If not on the first import it will happen on subsequent refresh:

- If failing on the first import, the artist and album sections of the UI is empty, though the song section will have all the imported songs up to the failing album/artist and I can play them fine. (see screenshots below) I am unable to import new songs as every refresh fails with `level=error msg="Error importing MediaFolder" error="readdirent: no such file or directory" folder=/music` right away. (Maybe the path to the folder is not properly formatted  in the db when it fails the first time)
- If failing on a refresh all sections are properly populated only the failing album/artist/song are missing and subsequent import won't always fail.

Some more information: I am running the container via docker-compose on a rpi3b (armhf platform) and the music library is on a smb3 share on a synology nas.

I'm pretty sure the error is due to the smb mount (I regularly have trouble with file locking and zombie connection for other containers) and don't think you can do much about it. Though you might be able to improve how navidrome handles the error on the first import (seems the db for artist/album is not properly populated if failing) when it happens.

Empty album/artist section
![image](https://user-images.githubusercontent.com/8529837/81916326-fb00e780-95d3-11ea-9d7e-ab2d44c8c881.png)
![image](https://user-images.githubusercontent.com/8529837/81916472-27b4ff00-95d4-11ea-9497-22608940f0a1.png)
![image](https://user-images.githubusercontent.com/8529837/81916578-43b8a080-95d4-11ea-8098-101f59d3184e.png)


Here's the log when failing on the first import. (Note that sometimes it will successfully import some albums and then fail, in this case it failed right away, nothing was imported).
<details><summary>Failed import log</summary>

```
Creating navidrome ... done
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                           Version: 0.18.0 (8b79b28)

time="2020-05-14T07:43:46Z" level=debug msg="Loaded configuration" config="&conf.nd{ConfigFile:\"./navidrome.toml\", Port:\"4533\", MusicFolder:\"/music\", DataFolder:\"/config\", ScanInterval:\"1m\", DbPath:\"/config/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL\", LogLevel:\"trace\", SessionTimeout:\"30m\", BaseURL:\"\", UILoginBackgroundURL:\"https://source.unsplash.com/random/1600x900?music\", IgnoredArticles:\"The El La Los Las Le Les Os As O A\", IndexGroups:\"A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ) [Unknown]([)\", EnableTranscodingConfig:false, TranscodingCacheSize:\"100MB\", ImageCacheSize:\"100MB\", ProbeCommand:\"ffmpeg %s -f ffmetadata\", DevLogSourceLine:false, DevAutoCreateAdminPassword:\"\"}" file=./navidrome.toml
time="2020-05-14T07:43:46Z" level=debug msg="Opening DataBase" dbPath="/config/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL" driver=sqlite3
time="2020-05-14T07:43:46Z" level=info msg="Creating DB Schema"
2020/05/14 07:43:46 OK    20200130083147_create_schema.go
2020/05/14 07:43:46 OK    20200131183653_standardize_item_type.go
2020/05/14 07:43:46 OK    20200208222418_add_defaults_to_annotations.go
2020/05/14 07:43:46 OK    20200220143731_change_duration_to_float.go
2020/05/14 07:43:46 OK    20200310171621_enable_search_by_albumartist.go
2020/05/14 07:43:46 OK    20200310181627_add_transcoding_and_player_tables.go
2020/05/14 07:43:46 OK    20200319211049_merge_search_into_main_tables.go
2020/05/14 07:43:46 OK    20200325185135_add_album_artist_id.go
2020/05/14 07:43:46 OK    20200326090707_fix_album_artists_importing.go
2020/05/14 07:43:46 OK    20200327193744_add_year_range_to_album.go
2020/05/14 07:43:46 OK    20200404214704_add_indexes.go
2020/05/14 07:43:46 OK    20200409002249_enable_search_by_tracks_artists.go
2020/05/14 07:43:46 OK    20200411164603_add_created_and_updated_fields_to_playlists.go
2020/05/14 07:43:46 OK    20200418110522_reindex_to_fix_album_years.go
2020/05/14 07:43:46 OK    20200419222708_reindex_to_change_full_text_search.go
2020/05/14 07:43:46 OK    20200423204116_add_sort_fields.go
2020/05/14 07:43:46 OK    20200508093059_add_artist_song_count.go
2020/05/14 07:43:46 goose: no migrations to run. current version: 20200508093059
time="2020-05-14T07:43:46Z" level=info msg="Creating Image cache" maxSize="100 MB" path=/config/cache/images
time="2020-05-14T07:43:46Z" level=debug msg="Found ffmpeg" path=/usr/bin/ffmpeg
time="2020-05-14T07:43:46Z" level=info msg="Creating Transcoding cache" maxSize="100 MB" path=/config/cache/transcoding
time="2020-05-14T07:43:46Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music
time="2020-05-14T07:43:46Z" level=trace msg="SQL: `SELECT count(*) as count FROM transcoding`" args="[]" elapsedTime=3.7232ms rowsAffected=1
time="2020-05-14T07:43:46Z" level=info msg="Creating default transcoding config" name="mp3 audio"
time="2020-05-14T07:43:46Z" level=trace msg="SQL: `INSERT INTO transcoding (command,default_bit_rate,id,name,target_format) VALUES (?,?,?,?,?)`" args="['ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -f mp3 -',192,'2e6051f6-1c91-4785-902c-c92eb9f77c74','mp3 audio','mp3']" elapsedTime="685.411µs" rowsAffected=1
time="2020-05-14T07:43:46Z" level=info msg="Creating default transcoding config" name="opus audio"
time="2020-05-14T07:43:46Z" level=trace msg="SQL: `INSERT INTO transcoding (command,default_bit_rate,id,name,target_format) VALUES (?,?,?,?,?)`" args="['ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -c:a libopus -f opus -',128,'a58c67ce-e0e2-433a-967b-ee44e0dde6a4','opus audio','oga']" elapsedTime="633.797µs" rowsAffected=1
time="2020-05-14T07:43:46Z" level=trace msg="SQL: `SELECT value FROM property WHERE id = ?`" args="['InitialSetup']" elapsedTime="450.413µs" rowsAffected=1
time="2020-05-14T07:43:46Z" level=warning msg="Running initial setup"
time="2020-05-14T07:43:46Z" level=trace msg="SQL: `SELECT value FROM property WHERE id = ?`" args="['JWTSecret']" elapsedTime="303.696µs" rowsAffected=1
time="2020-05-14T07:43:46Z" level=warning msg="Creating JWT secret, used for encrypting UI sessions"
time="2020-05-14T07:43:46Z" level=trace msg="SQL: `UPDATE property SET value = ? WHERE id = ?`" args="['284ceeba-3619-435d-93a5-6fe68ec13e3f','JWTSecret']" elapsedTime="312.654µs" rowsAffected=0
time="2020-05-14T07:43:46Z" level=trace msg="SQL: `INSERT INTO property (id,value) VALUES (?,?)`" args="['JWTSecret','284ceeba-3619-435d-93a5-6fe68ec13e3f']" elapsedTime=1.013377ms rowsAffected=1
time="2020-05-14T07:43:46Z" level=trace msg="SQL: `UPDATE property SET value = ? WHERE id = ?`" args="['2020-05-14 07:43:46.252094704 +0000 UTC m=+0.595069180','InitialSetup']" elapsedTime="504.631µs" rowsAffected=0
time="2020-05-14T07:43:46Z" level=trace msg="SQL: `INSERT INTO property (id,value) VALUES (?,?)`" args="['InitialSetup','2020-05-14 07:43:46.252094704 +0000 UTC m=+0.595069180']" elapsedTime="645.567µs" rowsAffected=1
time="2020-05-14T07:43:46Z" level=info msg="Starting scanner" interval=1m0s
time="2020-05-14T07:43:46Z" level=info msg="Mounting routes" path=/rest
time="2020-05-14T07:43:46Z" level=info msg="Mounting routes" path=/app
time="2020-05-14T07:43:46Z" level=trace msg="SQL: `SELECT value FROM property WHERE id = ?`" args="['JWTSecret']" elapsedTime="374.163µs" rowsAffected=1
time="2020-05-14T07:43:46Z" level=info msg="Navidrome server is accepting requests" address=":4533"
time="2020-05-14T07:43:48Z" level=trace msg="SQL: `SELECT value FROM property WHERE id = ?`" args="['LastScan-/music']" elapsedTime="535.1µs" rowsAffected=1
time="2020-05-14T07:43:48Z" level=debug msg="Scanning folder" folder=/music lastModifiedSince="0001-01-01 00:00:00 +0000 UTC"
time="2020-05-14T07:43:48Z" level=error msg="Error importing MediaFolder" error="readdirent: no such file or directory" folder=/music
time="2020-05-14T07:43:48Z" level=trace msg="SQL: `UPDATE property SET value = ? WHERE id = ?`" args="['1589442228271','LastScan-/music']" elapsedTime="327.706µs" rowsAffected=0
time="2020-05-14T07:43:48Z" level=trace msg="SQL: `INSERT INTO property (id,value) VALUES (?,?)`" args="['LastScan-/music','1589442228271']" elapsedTime="524.423µs" rowsAffected=1
time="2020-05-14T07:43:48Z" level=error msg="Errors while scanning media. Please check the logs"
time="2020-05-14T07:43:48Z" level=error msg="Error scanning media folder" error="errors while scanning media" folder=/music
```
And if you prefer to download the log: [navidrome.log](https://github.com/deluan/navidrome/files/4627163/navidrome.log)

**Comment by deluan** [comment]
Hey @Xyv, seems like there is an issue with Go 1.14 and CIFS mounts that is causing these intermitent errors. Take a look at @TheForcer's comment: https://github.com/deluan/navidrome/issues/393#issuecomment-657237003

Quick fix:
> I added the GODEBUG=asyncpreemptoff=1 variable to my Docker compose file, and voila, works perfectly :)

Let me know if this fixes the issues you were having (if you are still having them)

**Comment by deluan** [comment]
I'm closing this now as there is a fix, but feel free to reopen if you are still having related issues.

**Comment by Xyv** [comment]
Hey,
Yes I was still having the issue (and stopped using navidrome for a while), adding the variable to the compose file seems to finally resolve the problem!
Thanks for keeping tabs on this.
