### ISSUE TITLE
Ability to exclude files / folders from scanning

### ISSUE THREAD

**Issue by guim31** [deluan/navidrome#297]
I have in my library some unsorted files that I have to tag/sort/deduplicate...
I don't want to move the folders containing those songs out of my /music folder.

Should be a great feature to exclude folders from scanning.

Plex does that by the creation of a .plexignore file in the folder.

**Comment by deluan** [comment]
Navidrome now ignores folders containing a `.ndignore` file. The folder is ignored as well as all its sub-folders. This will be released this week, but if you want to give it a try, you can use the `develop` docker image or get the binaries from here: https://github.com/deluan/navidrome/actions/runs/108473614

**Comment by spiral6** [comment]
.ndignore is a good solution but it is very user intensive to have to create an .ndignore for *every* folder that requires one. A nice feature that would help would be to create a global blacklist for folders to be scanned such as a root config with .ndignore.

**Comment by deluan** [comment]
@spiral6 Yeah, I though about allowing a syntax like `.gitignore` inside the .ndignore`. Please feel free to open a new GH issue so this suggestion is not buried in a closed issue. Thanks!
