### ISSUE TITLE
Ability to Browse by folder

### ISSUE THREAD

**Issue by jerrycan619** [deluan/navidrome#299]
Hi, thank you for your good work on this project!
I really love navidrome.

I would like to ask you if i would be possible to implement a Browse by Folder function because my hole library is organized in folders.

I tried a lot of other Musicservers and just 1-2 are able to browse by folder.
But it's necessary for me :(

**Comment by deluan** [comment]
Thanks for trying Navidrome. 

Unfortunately, there are no plans to implement browse by folder, as it would require a huge refactoring/rewrite. 

I'm closing this now, as it is out of scope for Navidrome, at least for the foreseeable future.
