### ISSUE TITLE
Type incompatibilities in API responses

### ISSUE THREAD

**Issue by delucks** [deluan/navidrome#304]
Two fields are returned as strings rather than int64 as the spec states-
* Child.size
* Indexes.lastModified

`Child.size`:
```
$ navicurl getSong "&id=$SAMPLE_SONG" | jq '."subsonic-response".song.size'
"35204343"
```

`Indexes.lastModified`:
```
$ navicurl getIndexes | jq '."subsonic-response".indexes.lastModified'
"1589902195004"
```

I've confirmed that both of them are the wrong type in both JSON & XML responses, here's an excerpt from `/getIndexes`:
```
<subsonic-response status="ok" version="1.10.2" type="navidrome" serverVersion="0.17.0 (13ce218)">
<indexes lastModified="1589902195004" ignoredArticles="The El La Los Las Le Les Os As O A">
...
```

**Comment by deluan** [comment]
Thanks! Will fix them for next release
