### ISSUE TITLE
How can I make server accessible from outside of network?

### ISSUE THREAD

**Issue by chimsol** [deluan/navidrome#307]
I want to stream from the server on Android phone when I am away from home.  Can someone provide steps for this?  I am running Win10.

**Comment by the-salami** [comment]
The easiest and most secure way is to use a VPN to connect to your local area network. If you've ever used something like Hamachi to play games with friends, it's the same thing. Personally I use a zerotier network for this purpose. There are many other options. You can also port forward on your router to expose navidrome to the internet, but that is a security risk.

This is also not really an appropriate forum for this discussion, as it's not an issue, bug report, or feature request. In the future, consider posting on Reddit.

**Comment by deluan** [comment]
There are good tutorials in the Nets about this topic.

There is actually a discussion about this exact topic happening in our Reddit: https://www.reddit.com/r/navidrome/comments/gnhrg4/can_the_server_stream_music_from_anywhere/
