### ISSUE TITLE
Ability to upload files

### ISSUE THREAD

**Issue by guim31** [deluan/navidrome#311]
Is it planned to allow users to upload content within the UI ?
Could be individual mp3 files, complete .zip albums..

Would be very interesting in order to create a shared library.

**Comment by jvoisin** [comment]
Since navidrome has no notion of folder, it would be tricky I think.

**Comment by deluan** [comment]
IMO, there are better ways to do this: FTP/SFTP, Lidarr or even a shared folder. As long as Navidrome is configured to scan the music folder continually (default is every 1m), it will detect the new files as they appear in the media folder.

Having said that, I may implement this in the future. But this requires #192 

@jvoisin: Navidrome does not care about folders, so it would not be a problem. You could have a configuration to set the _upload folder_.  But this could conflict with the support for `cover.jpg` files...

**Comment by guim31** [comment]
>  But this could conflict with the support for cover.jpg files...

Haha so I ask for 2 conflicting things ^^ 
Thanks for your detailled answer

**Comment by deluan** [comment]
@guim31,  after giving this some thought, I don't think this is a feature I'd like to have in Navidrome. There are better options and tools to handle File upload and management. Will close this now, but feel free to chime in with any concerns
