### ISSUE TITLE
Default cover art not found in some cases

### ISSUE THREAD

**Issue by delucks** [deluan/navidrome#314]
While fetching cover art for songs from the database, I get an occasional Error 0, with an "Internal Error" message. From the logs of the host running navidrome, I see it attempted to load the image `resources/navidrome-310x310.png` and got a "no such file or directory", and this error caused the failed call. I also see a message from the `image` library that is potentially related:

```
May 23 05:07:31 machine.hostname navidrome[2982]: time="2020-05-23T05:07:31Z" level=warning msg="Error extracting image" error="image: unknown format" path= requestId=machine.hostname/hMRTwsC2Cw-000184 size=0
May 23 05:07:31 machine.hostname navidrome[2982]: time="2020-05-23T05:07:31Z" level=error msg="Error loading cover art" error="open resources/navidrome-310x310.png: no such file or directory" path= requestId=machine.hostname/hMRTwsC2Cw-000184 size=0
May 23 05:07:31 machine.hostname navidrome[2982]: time="2020-05-23T05:07:31Z" level=error msg="Error retrieving coverArt" error="open resources/navidrome-310x310.png: no such file or directory" id=ed58293ef4b9e2be516b272669c4007f requestId=machine.hostname/hMRTwsC2Cw-000184
May 23 05:07:31 machine.hostname navidrome[2982]: time="2020-05-23T05:07:31Z" level=warning msg="API: Failed response" error=0 message="Internal Error" requestId=machine.hostname/hMRTwsC2Cw-000184
```

I haven't observed this with any tracks that have embedded artwork, so I think this is a problem with either bundling or fetching the default cover artwork. I'm running navidrome built from git, commit `ec0002e77a9da015ddcd6328178fd0f47e4ad87b`.

**Comment by deluan** [comment]
As we discussed in the Discord chat, this happens when you build the server with `go get`. As Navidrome has some embedded resources, you need to run `go-bindata` first. 

The easiest (and proper) way to build Navidrome is to run: `make buildall`.
