### ISSUE TITLE
Album art not showing up for Opus encoded albums

### ISSUE THREAD

**Issue by andre15silva** [deluan/navidrome#318]
Hi!

I'm having an issue similar to #308 but with Opus files and embedded art.

The following warning message was present in the logs for each Opus encoded album:

> (...) level=warning msg="Error extracting image" error="image: unknown format" (...)

I used opusinfo to retrieve the following information from one of the albums in question:

> METADATA_BLOCK_PICTURE=3|image/jpeg||800x800x24|<344293 bytes of image data>

I can upload a file if you'd like to. 

Using v0.19.0 armv7 build. I noticed you just released a new version half an hour ago, but by reading the commits I think none affect this. I can try and update if you'd like to as well.

**Comment by deluan** [comment]
This is a known issue in the upstream library used to extract embedded art: https://github.com/dhowden/tag/pull/69

I'm testing the fix and hopefully we will have it fixed this week.

**Comment by deluan** [comment]
Do you have a lot of files in this situation? I can generate a test build (later today) and you can try it

**Comment by andre15silva** [comment]
Yes, a little over 4k files. I can try it when ready

**Comment by deluan** [comment]
Here is the build with the fix:
Binaries: https://github.com/deluan/navidrome/actions/runs/114082205
Docker: `deluan/navidrome:pr-319`

Let me know the results. Thanks!

**Comment by deluan** [comment]
Hey @andre15silva , did you had a chance to test this?

**Comment by andre15silva** [comment]
I'm busy with uni work sorry. I'll try to test it tomorrow

**Comment by andre15silva** [comment]
I can confirm it works! 

![pic-selected-200527-1538-22](https://user-images.githubusercontent.com/31904862/83034546-497ca000-a030-11ea-8d06-f42fcd90e8cb.png)

I don't see any album without it's corresponding album art and saw no error or warning message when importing the library. Thank you!

**Comment by Bertsz** [comment]
Hi, I don't think it's that important since out of 70000 opus and mp3 files just 10 had issues (4 of them where mp3s), but there might still be a rare edge case where the thumbnail generation fails with `error="image: unknown format"`.

Let me know if you want to get to the bottom of this and thanks for the hard work on this project.

**Comment by deluan** [comment]
Thanks for testing this, @Bertsz. Can you attach a sample file?

**Comment by deluan** [comment]
For next release, I'll use the potential fix, to expose it to more users with different opus encoded files.
