### ISSUE TITLE
deleted files not picked up

### ISSUE THREAD

**Issue by certuna** [deluan/navidrome#322]
0.20 seems to fail to recognize that folders/files are deleted, after a restart. Changed files are rescanned, but deleted songs/albums are not removed.

`WARN[0015] API: Failed response                          error=0 message="open /folder/file.mp3: no such file or directory"`

Can anyone replicate this?

**Comment by deluan** [comment]
Did you delete the files while Navidrome was not running? (See #151)

**Comment by certuna** [comment]
Yes - looks like it's the same issue, you can close this one.
