### ISSUE TITLE
After changing MusicFolder old titles stay in library

### ISSUE THREAD

**Issue by IeP4nieF** [deluan/navidrome#325]
After changing the "MusicFolder" configuration option in navidrome.toml for example from "/var/local/music_a" to "/var/local/music_b" the titles under "/var/local/music_a" are still in the library. If it is not possible to remove them automatically, there should be at least an option to clean the database.

Thanks!

(I'm using Version v0.21.0.)

**Comment by deluan** [comment]
Thanks for trying Navidrome.

This will be fixed in #192. For the time being, if you change the MusicFolder configuration, you should also delete all files in the DataFolder. This will force a fresh start (you'll have to create the admin user again)

**Comment by deluan** [comment]
To add to my previous response, you'll also be able to clean the DB when #130 is done.

I'm closing this for now, as the fix for this will be tackled in other issues. Please subscribe to those issues to be informed about their progress.
