### ISSUE TITLE
sort order of artists with (at least) german articles is not right

### ISSUE THREAD

**Issue by IeP4nieF** [deluan/navidrome#326]
In the artist list artist names with english article (The) are sorted correct, while artist names with german articles (Die) are not sorted correct. For example "The Beatles" are sorted as "Beatles", but "Die Sterne" are sorted as "Die Sterne". My expected behaviour is, that "Die Sterne" are sorted as "Sterne".

Of course the tags in the files are right (ARTISTSORT="Beatles, The" and ARTISTSORT="Sterne, Die"). Obviously the artist list in navidrome is sorted by the order_artist_name row in the db. For "The Beatles" this field is correct: "Beatles". But for "Die Sterne" it is "Die Sterne".

BTW: What is the difference between order_artist_name and sort_artist_name? FYI: The sort_artist_name field for "The Beatles" is "Beatles, The" and for "Die Sterne" is "Sterne, Die". So navidrome uses the ARTISTSORT-tag, but puts into order_artist_name "Die Sterne".

**Comment by IeP4nieF** [comment]
Some more information: Obviously sorting is done by the clients. I see the described behavior in the WebUI of navidrome and in ultrasonic. But with Audinaut also the artists with the english article "The" are sorted wrong (all artists starting with "The..." are sorted together under "T").

**Comment by deluan** [comment]
Thanks for the report! I forgot to [document](https://www.navidrome.org/docs/usage/configuration-options/) the `IgnoredArticles` config option! It allows you to change the prefix words that Navidrome considers articles when creating the `order_*` fields.

You can add the German articles to the list. Unfortunately, as we don't have a [full rescan option yet](https://github.com/deluan/navidrome/issues/130), you'll need to drop the DB and start from scratch. Let me know if this works for you so I can close this issue.

As for the difference between `sort_*` and `order_*`, the former are the copy of the sort tags from the imported music file. Navidrome only uses the contents of these fields for search, as they usually contains the Latin version of non-Latin tags (Japanese, Arabic, etc...). See #121. 

The `order_*` fields are ["sanitized"](https://github.com/deluan/navidrome/blob/5ce3135f004e4151edd535fb5aa0219a18af7f03/scanner/tag_scanner.go#L284) versions of the original tags (ex: `artist`, not `sort_artist`). This is the field actually used for sorting the artists in the UI. Navidrome doesn't use `sort_*` fields for artists as they are not consistent and usually change the order of the artist's first/last name: (ex: Young, Neil)

Re: Audionaut, that's strange. It is working correctly in my instance. See the screenshot below.

![Screenshot_20200601-090357](https://user-images.githubusercontent.com/331353/83411804-f5ced580-a3e6-11ea-9055-5a0863103dae.png)

**Comment by IeP4nieF** [comment]
After adding the articles to the "IgnoredArticles" configoption, the artists are sorted correct in the WebUI. This is not the case in Audinaut and ultrasonic, but that could be a caching problem.

So you can close this one.

Thanks!
