### ISSUE TITLE
Skip directory with insufficient permission while scanning

### ISSUE THREAD

**Issue by PichetGoulu** [deluan/navidrome#328]
This is a corner case of #297 where `navidrome` does not have the permission to read the content of a directory, thus cannot read the `.ndignore` file in it.

Instead of skipping the directory and scanning the rest of the folders in `MusicFolder` with proper permissions, `navidrome` stop.
A possible fix would be to warn about such directories and keep scanning.

I my case, the `MusicFolder` is at the root of an ext4 partition, and `navidrome` does not run as root.
`navidrome` does not have the permission to read the content of the `lost+found` directory, thus cannot read the `.ndignore` file in it.

```
time="2020-06-01T10:56:59Z" level=error msg="Error importing MediaFolder" error="open /var/music/lost+found: permission denied" folder=/var/music
time="2020-06-01T10:56:59Z" level=error msg="Errors while scanning media. Please check the logs"
time="2020-06-01T10:56:59Z" level=error msg="Error scanning media folder" error="errors while scanning media" folder=/var/music
```

**Comment by deluan** [comment]
Yes, you are right. Right now Navidrome stops the scanning if it finds any kind of error. I'm working on the scanner this next couple of weeks, I'll try to make it more robust. Thanks for the report!
