### ISSUE TITLE
Makefile: check_go_env problem

### ISSUE THREAD

**Issue by winks** [deluan/navidrome#33]
I was just trying to build this on a new vm and I noticed that

```
check_go_env:
        @(test -n "${GOPATH}" && hash go) || (echo "\nERROR: GO environment not setup properly!\n"; exit 1)
```

could be a bit problematic. I've not done a lot of go for 2 years, but [the docs](https://golang.org/doc/install#testing) currently say

> Create your workspace directory, $HOME/go. (If you'd like to use a different directory, you will need to set the GOPATH environment variable.) 

But even if I put the checkout in this correct folder, this will fail if you don't set `GOPATH`, but this shouldn't be needed when it's in exactly this folder?

**Comment by deluan** [comment]
Yeah, this is not perfect, I'm thinking of rewriting the makefile. I'll try to come back to this during the week

**Comment by deluan** [comment]
I removed the check for GOPATH in cc58642, as it is not really required as this project uses Go Modules. 

The Makefile refactoring will come later. 

Thanks for reporting 👍
