### ISSUE TITLE
Missing "Add To Playlist" Option in Album View

### ISSUE THREAD

**Issue by amura11** [deluan/navidrome#334]
When viewing an album, either directly from the Album list or via the Artist list there is no way to add songs to a playlist. Selecting on or more songs in this view only gives the option to "Play Later". It would be really convenient to have an "Add to Playlist" option in the Album view like the Song view.

**Song View**
![image](https://user-images.githubusercontent.com/1559993/83479138-f4d48d00-a454-11ea-96e3-6921b9c8d23d.png)

**Album View**
![image](https://user-images.githubusercontent.com/1559993/83479154-00c04f00-a455-11ea-8fe9-daf7c1a69121.png)

**Comment by deluan** [comment]
Good catch. Will add this in the next release!

**Comment by deluan** [comment]
Wait, I can see the "Add to Playlist" option in the Album view:
<img width="1011" alt="Screen Shot 2020-06-02 at 12 43 32 AM" src="https://user-images.githubusercontent.com/331353/83480750-2146d400-a46a-11ea-8192-65c9f4a0d80e.png">

I don't remember when I added this, but it is surely there in the latest version. Can you confirm this?

**Comment by amura11** [comment]
My bad, it must have been added after 0.19, just updated to 0.21 and it's there now.
