### ISSUE TITLE
Binary doesn't start if `./music` and/or `./data` are not created

### ISSUE THREAD

**Issue by winks** [deluan/navidrome#34]
Just built from master and starting `./navidrone` yields

```
[ORM]2020/01/26 16:09:24 register db Ping `default`, unable to open database file: no such file or directory
panic: register db Ping `default`, unable to open database file: no such file or directory
```

just creating the `data` dir fixes it, but I wonder if it shouldn't be created automatically.

A similar error a second or two later if `./music` doesn't exist:

```
ERRO[0002] Error importing MediaFolder                   error="open ./music: no such file or directory" folder=./music
```
adding it to the README could also be a possible resolution, but at least the first one should probably be a better error message, maybe after creating the dir?

Otherwise I can report that building with go 1.13 / nodejs 13.3 on FreeBSD 11.3 works flawlessly.

**Comment by deluan** [comment]
Yes. I'm changing this right now, as I'm preparing the distributable binaries for release

**Comment by deluan** [comment]
Just pushed a change related to this, f9db80c. Now there is a config for the DataFolder, default `./`, and DbPath now defaults to `${DataFolder}/navidrome.db`.

For the music folder, it does not prevent Navidrome to start, so I'd consider it a usage error, and it is reported as such. This behaviour will change once multi MusicFolders are introduced.

I'm closing this for now, but feel free to reopen if you think this solution is not satisfactory.
