### ISSUE TITLE
[Request] Add Public/Private button to the playlist view

### ISSUE THREAD

**Issue by BobWs** [deluan/navidrome#344]
Hi,
Is it possible that you add the Public/Private button to the playlists list view? That would make it easier to share or unshare playlists when one has a lot.

![Screen_Shot](https://user-images.githubusercontent.com/5485820/84042221-124dad80-a9a5-11ea-9376-8bd8c615cfdc.png)

**Comment by deluan** [comment]
Great idea! Will try to add this in the next release

**Comment by deluan** [comment]
@BobWs This will be available in this weekend's release:

![Kapture 2020-06-08 at 18 43 31](https://user-images.githubusercontent.com/331353/84087484-336bc980-a9b8-11ea-8997-16bf32a5df43.gif)

If you want to try it sooner, just use the `develop` builds

**Comment by BobWs** [comment]
Great that is exactly what I was talking about. Thanks for your quick response!
