### ISSUE TITLE
Problems with spaces in folder names in the media library

### ISSUE THREAD

**Issue by winks** [deluan/navidrome#35]
Had a folder called `./music/Band Name/Album Name (2008)` with some MP3s (also with spaces) in them.

First I got 
```
ERRO[0002] Error importing MediaFolder                   error="open music/music/: no such file or directory" folder=./music
ERRO[0002] Errors while scanning media. Please check the logs              
ERRO[0002] Error scanning media folder                   error="errors while scanning media" folder=./music
```

then I renamed `Band Name` to `Band_Name` and I got

```
ERRO[0002] Error importing MediaFolder                   error="open music/music/Band_Name: no such file or directory" folder=./music
ERRO[0002] Errors while scanning media. Please check the logs              
ERRO[0002] Error scanning media folder                   error="errors while scanning media" folder=./music
```

if I just copy one of the files to `./music/test.mp3` this is found.

This is FreeBSD, but I can't imagine the folder reading to be really different than on Linux.

**Comment by deluan** [comment]
That's really strange. I tested this in Linux and macOS, my library has spaces all over the place and it works fine. My first thought is that it could be caused by the shell you use, as of right now Navidrome calls ffmpeg to extract tags.... I'll investigate a little more and let you know. 

Does it work when you have `./music/band/test.mp3` (no spaces, with a band folder) ?

By the way, what FreeBSD and shell versions are you using?

**Comment by winks** [comment]
When I put the file as `./music/band/test.mp3` it shows up in the web UI and a search for parts of the band or title will find it, so that works. The album in question does not show up at all.

```
freebsd% echo $ZSH_VERSION
5.7.1
freebsd% uname -a
FreeBSD freebsd 11.3-RELEASE-p5 FreeBSD 11.3-RELEASE-p5 #0: Tue Nov 12 08:59:04 UTC 2019     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

But I'd be surprised if it was the shell. Starting it with the default `tcsh` or `csh` makes no difference, except that I don't get any errors right now.

**Comment by winks** [comment]
Happy to help debug this more if you give me some hints how to get better logging, or use a different branch. Or some simple repro snippet extracted from the codebase. 

I'm just playing around though because if I used this in prod, I'd need it to run on my FreeNAS (v11) in a jail, like I use subsonic now, that's why I'm not using Linux. I can fully understand if you don't care for BSD :)

**Comment by deluan** [comment]
I'll try to run FreeBSD in a VM or docker and try to reproduce this error on my side. 

Can you send me one of these files (via Dropbox, or something similar)?

**Comment by winks** [comment]
Sent link via mail.

**Comment by deluan** [comment]
Hey @winks, sorry for the lack of updateI didn't forget about this, but I couldn't find a proper Docker image with FreeBSD (do you know if there is any?), and I don't have space for more VMs in my computer...

Will try to clean up some space this weekend and work on this.

**Comment by winks** [comment]
No worries.

But no idea, sorry - I just spun up a vm on my home server with libvirt and [the qcow image](https://download.freebsd.org/ftp/releases/VM-IMAGES/11.3-RELEASE/amd64/Latest/).

DigitalOcean has FreeBSD, so spinning up a 5$ droplet for a few hours should be just a few cents, maybe that's an easier solution?

Did a really quick search but also found no trustworthy up to date Vagrant boxes, but that could be another path.

**Comment by deluan** [comment]
Hey @winks , I'm having trouble setting up FreeBSD here.

As an experiment, I escaped spaces in filenames when calling ffmpeg. Can you try it? I pushed this in the branch https://github.com/deluan/navidrome/tree/escape-space.

Also, I added some more info to the logs, when you run it, try setting the loglevel to trace.

Let me know the results

**Comment by winks** [comment]
Sorry, commented in the wrong tab: https://github.com/deluan/navidrome/commit/8758415ec79dbc64521bc1e4815bbf205fdfcce0

**Comment by deluan** [comment]
Hey, I saw your comments and logs. I think (hope?) I understand what is going on: I'm usign `path.Join` while traversing the music tree. It should be `filepath.Join`, that caters for the right `os.PathDelimiter`. 

I pushed a change to the branch, and also added a `log.Trace` to log all changed/deleted folders found in the process. Can you try this?

Regarding the web ui, it need to be built to be availabe. You can build it with `make buildall`, or just entering the `ui` folder and running `npm run build`

**Comment by winks** [comment]
Gonna try that tonight, thanks.

Re: the ui. I did `make buildall` again, like in my original test - but it simply didn't do anything useful. I only see a ".gitkeep" when I go to localhost:4533 - I suppose `go-bindata` didn't work properly, but I didn't see why. I'm gonna see if I can find out why.

**Comment by winks** [comment]
Pretty sure this is not a FreeBSD problem, can reproduce on Linux.

```
RAC[0002] Folder analysis complete                      changed=3 deleted=0 elapsed="253.921µs" total=3
INFO[0002] Folder changes found                          changed="music/BAND/ALBUM;music/BAND;." deleted= numChanged=3 numDeleted=0
```
but then only `TRAC[0002] Executing command                             args="[-i music/test.mp3 -f ffmetadata]" cmdLine=ffmpeg` is ever analyzed by ffmpeg

Could it simply be that the scanner is not properly recursing into subfolders?

I didn't grasp this skip for example: https://github.com/deluan/navidrome/blob/escape-space/scanner/metadata_ffmpeg.go#L58

**Comment by deluan** [comment]
Found the issue!!

This line shows that the scanner is **NOT** finding the folders correctly:
```INFO[0002] Folder changes found                          changed="music/BAND/ALBUM;music/BAND;." deleted= numChanged=3 numDeleted=0```

`changed` should be "BAND/ALBUM;BAND;." without the "music" prefix, that's what was causing the problem.

 The issue was caused by me improperly manipulating relative paths with simple string functions. I replaced this strings.TrimPrefix() with filepath.Rel() [here](https://github.com/deluan/navidrome/commit/354062e7b567ad7b9b9bbefa2151d21ea71db6db#diff-8b5c136943b1e3b3a7f96c089a698e9fL96) and it is now working!

Let me know if it works for you!

-------------
Re: your questions about the scanner. 
> I didn't grasp this skip for example: https://github.com/deluan/navidrome/blob/escape-space/scanner/metadata_ffmpeg.go#L58

This is _after_ the scan happens. For each folder that was deemed "changed" (new folders or folder with file changes), this ExtractAllMetadata function is called. It loads _only_ files in the given path (that's the reason of the skip above), and send them to be analyzed by ffmpeg

**Comment by deluan** [comment]
I decided to merge it now, as it would cause any MusicFolder defined as a relative path to fail. 

Feel free to reopen if the fix does not work for you.

**Comment by winks** [comment]
Works as expected now! 👍

**Comment by deluan** [comment]
Hey @winks, sorry for tagging you after all this time. Are you still using Navidrome? If yes, can you add here the steps to compile it on FreeBSD? I'm thinking about adding it to the release pipeline and I'm not sure what dependencies I need to install. Thanks!

**Comment by winks** [comment]
Hey, it's been a while since I touched it, so I'll try to sum up what I did:

  * download the `master.zip` because I didn't want to wrangle with git just to try it out
  * `go` is installed in `/usr/local/go` just as on Linux

My history on the test VM shows this:

```
freebsd-update fetch
freebsd-update install
pkg install npm-6.12.1
pkg install ffmpeg
```

and then the usual gopath shenanigans and then following https://www.navidrome.org/docs/installation/build-from-source/ - unless it changed since then

But this is mostly from memory and `history` - if you run into any problems feel free to ping me again, happy to try to set it up from scratch and make notes, it didn't take long
