### ISSUE TITLE
"Could not register player" errors due to 0.23.0 upgrade

### ISSUE THREAD

**Issue by Wonderfall** [deluan/navidrome#352]
Hi, I just upgraded my server to 0.23.0, using Docker.

However it seems it can't recognize/add a "Navidrome UI" player. So my transcoding preferences are not applied, it seems. Audinaut is still recognized and working though.

```
time="2020-06-14T18:22:45Z" level=info msg="Registering new player" client=NavidromeUI id=xxxxxxxxxxxxxxx userName=Wonderfall
time="2020-06-14T18:22:45Z" level=error msg="SQL: `INSERT INTO player (client,id,ip_address,last_seen,max_bit_rate,name,transcoding_id,type,user_name) VALUES (?,?,?,?,?,?,?,?,?)`" args="['NavidromeUI','xxxxxxxxxxxxxxx','','2020-06-14T18:22:45.655468921Z',0,'NavidromeUI (Wonderfall)','','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15','Wonderfall']" elapsedTime="33.28µs" error="FOREIGN KEY constraint failed" requestId=16dc15dabad9/JCkWlsEmMB-000199 rowsAffected=0
time="2020-06-14T18:22:45Z" level=error msg="Could not register player" client=NavidromeUI userName=Wonderfall
```

Upgrade was done just by recreating the container. Was there something else to do?

**Comment by deluan** [comment]
Just a normal upgrade should work... I'll check this

**Comment by deluan** [comment]
Looks like it didn't upgrade your DB.... Can you post the DB version? It's the first line of the logs when you start Navidrome:
```
...
 \_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                  Version: v0.22.0-SNAPSHOT (2d1d992)

 2020/06/14 10:00:55 goose: no migrations to run. current version: 20200608153717
...
```

The version should be `20200608153717`

Have you ran the version from the PR #346, by any chance?

**Comment by Wonderfall** [comment]
```
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                           Version: 0.23.0 (2d1d992)

2020/06/14 18:16:18 OK    20200608153717_referential_integrity.go
2020/06/14 18:16:18 goose: no migrations to run. current version: 20200608153717
```

There it is. Just upgraded from 0.22.0, I don't recall running anything else.

**Comment by deluan** [comment]
So it did upgrade the DB... I think it has something to do with the username having a capital _W_. For testing purposes, can you change your username to `wonderfall` instead of `Wonderfall`?

**Comment by Wonderfall** [comment]
Yep, it worked instantly when I changed to `wonderfall`.

**Comment by deluan** [comment]
Thanks for finding this! I will release a bug fix in the next couple of days

**Comment by Wonderfall** [comment]
Sure, no problem! Glad if it could help.

**Comment by Wonderfall** [comment]
Also while I'm at it, I noticed that Navidrome showed "Streaming file" several times when I play a cached transcoded song from Navidrome UI (not from Audinaut, which is very strange). Not sure if it's related so it might get a new issue. I'm pretty sure I haven't seen this behavior in 0.22.0.

**Comment by deluan** [comment]
It's always been there. This is caused by the HTML audio player making chunked calls to the server. I may revisit this messages to avoid duplication

**Comment by Wonderfall** [comment]
I see, just wanted to be sure!

**Comment by MinchinWeb** [comment]
> So it did upgrade the DB... I think it has something to do with the username having a capital W. For testing purposes, can you change your username to wonderfall instead of Wonderfall?

Just ran into the same issue, and the same fix. Version 0.35.1 (f373f5f)
