### ISSUE TITLE
Unable to create Admin account

### ISSUE THREAD

**Issue by r0arkin** [deluan/navidrome#36]
I spun up the docker and upon going to http://localhost:4533 or the URI I set up, I am not prompted to create an admin account. My yml is below and a screenshot of the page.

<img width="597" alt="Screen Shot 2020-01-26 at 10 41 00 AM" src="https://user-images.githubusercontent.com/46236585/73139954-62e0f180-4028-11ea-81b8-737ff16dc258.png">

```version: '3.7'

services:
  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    restart: always
    environment:
      ND_MUSICFOLDER: /music
      ND_DBPATH: /data/navidrome.db
      ND_SCANINTERVAL: 1m
      ND_LOGLEVEL: info
      ND_PORT: 4533
    ports:
      - 4533:4533
    volumes:
      - ${USERDIR}/assets/navidrome:/data
      - /mnt/media/music:/music
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.navidrome-rtr.entrypoints=https"
      - "traefik.http.routers.navidrome-rtr.rule=Host(`navidrome.${DOMAINNAME}`)"
      - "traefik.http.routers.navidrome-rtr.tls=true"
      - "traefik.http.routers.navidrome-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.navidrome-rtr.middlewares=noauth-chain@file"
      ## HTTP Services
      - "traefik.http.routers.navidrome-rtr.service=navidrome-svc"
      - "traefik.http.services.navidrome-svc.loadbalancer.server.port=4533"

networks:
  traefik:
    name: traefik
    external: true```

**Comment by deluan** [comment]
Can you remove the `data/navidrome.db` file, change the loglevel to "trace" (ND_LOGLEVEL=trace) and post here the log, please?

**Comment by r0arkin** [comment]
Sure! Give me a moment.

**Comment by r0arkin** [comment]
[trace.log](https://github.com/deluan/navidrome/files/4114109/trace.log)

**Comment by r0arkin** [comment]
I stopped when it started scanning the library. If you want the whole log, let me know!

**Comment by r0arkin** [comment]
Ah there we go. I guess you need to wait for either the whole library to be processed first or part of it. You may want to document that :)

<img width="493" alt="Screen Shot 2020-01-26 at 11 03 54 AM" src="https://user-images.githubusercontent.com/46236585/73140237-940ef100-402b-11ea-97a7-73ac262ce88c.png">

**Comment by deluan** [comment]
Great that it worked for you! But I don't think this is related to the scan not being finished yet. I tried it here and it brings the "Create Admin" page before finishing the scan.

This screen is new, was just implemented yesterday. Maybe you have run an old version of the image (from before Friday), that created the `navidrome.db` with a default `admin` user?

If you can, please try it again (deleting the `navidrome.db` file) and try to access the UI before the scan finishes, and let me see the results

Thanks for the report, by the way :)

**Comment by r0arkin** [comment]
So it does look like it works prior to the scan being finished. It just takes a little bit of time. Roughly about 10 minutes after the container is created.

**Comment by deluan** [comment]
Ok. Well, I'm closing this for now, but feel free to report any other issue. Thanks!
