### ISSUE TITLE
album art when not all album tracks have it

### ISSUE THREAD

**Issue by certuna** [deluan/navidrome#360]
I've got some albums where only track 1 has album art embedded (I guess somebody was very keen to conserve disk space).

Most other music libraries, for example Plex & iTunes, scan the album and take the album art of the *first* track they scan, and then apply that for the whole album in Album view.

Navidrome on the other hand seems (?) to take the album art from the *last* track it scans, and if that is empty, the whole album has no artwork. I think that's probably not desirable? Can you reproduce this?

**Comment by deluan** [comment]
Navidrome takes album art from one of the tracks that have it, randomly, so it should not have this issue. I'll do some investigation and try to reproduce this locally

**Comment by deluan** [comment]
I can confirm this is a bug: Navidrome tries to read the album art from a random track if at least one has the album art, but not necessarily from the one that has it. We are adding [support for external album art](https://github.com/deluan/navidrome/pull/350) in one of the next releases, and I will fix this issue when that happens, as it touches the same code
