### ISSUE TITLE
No config file created automatically on Windows

### ISSUE THREAD

**Issue by LokeYourLord** [deluan/navidrome#37]
So I would really want to submit a proper issue text here, but this issue is fairly small. There is currently no way to configure the windows binary at all, as the software does not automatically create a config file (navidrome.toml) in where the changes should be made, so I hope you can fix this.

Best Regards, -Loke

**Comment by deluan** [comment]
The Windows binary is a command line tool, same as in other platforms.  Can't you pass command line flags (ex: `navidrome --musicfolder=c:\music`) or env vars? `ND_MUSICFOLDER=c:\music`?

I want to create a more "native" build for each platform, maybe even with an installer. This binaries are just a simple way to get going.

Let me know what you think

**Comment by LokeYourLord** [comment]
Yeah I tried that but using it by cmd it opens the .exe for me and does not let me do commands inside the navidrome.exe command line window, although I can see if I can find another way. Thanks a lot for the fast response, and your insanely awesome work!

**Comment by LokeYourLord** [comment]
Also, I first had the issue the other guy has with the space in the folder name, it is easily solvable with "" for the folder path in the command argument.

**Comment by deluan** [comment]
I don't have access to a windows machine write now (I'll install a VM soon, so I can test it), but I think you're trying to double click the executable to start it. If that's the case, then you really don't have any means to configure it. Some options: 

- Create a shortcut to the executable, edit it and add the parameters in the "command" field, after the name of the executable.
- Open cmd.exe and from there `CD` to the folder where Navidrome is downloaded/installed. Then you can call it with the command line options.

**Comment by LokeYourLord** [comment]
Yeah I actually tried both options in the end, I didn't double click because I did try natively from cmd and redirect with "CD", but it didn't recognize the value the first time, I changed some settings and got it to work however.

**Comment by deluan** [comment]
Great! Thanks for trying it out, and let me know if you find any other issues. Assuming this is not an issue anymore, I'm close this

**Comment by LokeYourLord** [comment]
Of course, thanks! I do have one question though because I am very very new to this, so how would I use this from beyond the Navidrome Localhost page to stream music? I tried "Jamstash" webplayer and tried to connect with my external IP, port and the username and password I created but it doesn't seem to work at all. Any hints? Sorry for bothering, but documentation on this (anywhere) is scarce 😅

**Comment by deluan** [comment]
Navidrome's UI does not have a means to play music directly (yet), so you need Subsonic compatible players to do it. Jamstash should work (I use it for test), You should be able to get it working by setting the server pointing to your external or internal address (if it is the same machine you are using: http://localhost:4533. Username/password is the one you created in the UI. Let me know if this works.

Yeah, docs are missing, sorry. I just released Navidrome two days ago, I still need to work on some stuff (docs, web site, better installers). Right now I'm trying to finish some needed features, but will work on these things as soon as possible

**Comment by LokeYourLord** [comment]
Thanks. I got it to work with Clementine on Windows, Jamstash doesn't want to work, and Android Players like Airsonic Players say that the Subsonic API is not supported (or some fail to connect). I gotta keep trying to get this to work, but thanks!

**Comment by deluan** [comment]
DSub works flawless. Will test with other players as soon as I have the chance

**Comment by LokeYourLord** [comment]
Yeah I am about to download DSub too, thanks for the heads up!

**Comment by LokeYourLord** [comment]
Hmm, on DSub I am getting "Connection failure. A network error occurred" and so on. What can I do about this? Apparently PC client Clementine works fine, but I cannot get DSub to work either. I can send you an image of how my settings look, if you could check if it's all correct I would appreciate that.

**Comment by LokeYourLord** [comment]
![KakaoTalk_20200127_134939655](https://user-images.githubusercontent.com/5807595/73150885-fc350400-410b-11ea-82b2-5c7f9b94ca21.png)
![KakaoTalk_20200127_134939975](https://user-images.githubusercontent.com/5807595/73150886-fccd9a80-410b-11ea-93a2-c681c12850a6.png)

So here you have my settings and also the error I receive, I put in the exact same into Clementine and it works, but on DSub it won't. I am fine with giving out my IP to you, by the way, and I can delete these images soon after you have checked them :)

**Comment by deluan** [comment]
You can delete now.

**Comment by LokeYourLord** [comment]
Alright thanks. So what would you say is wrong?

**Comment by deluan** [comment]
The "Local network address" cannot be "localhost", has to be some real IP, like 192.168.X.X or 10.X.X.X. You can find it running `ipconfig /all` in the cmd.exe prompt. If you don't know what it is, try just leaving this address empty, and DSub will use the external address

**Comment by LokeYourLord** [comment]
Yeah I tried leaving it empty, but it doesn't work either that way.

**Comment by LokeYourLord** [comment]
Nevermind, I got it to work FINALLY. I had to change some Router settings as well. Thanks for all the help @deluan !
