### ISSUE TITLE
song count and duration are much higher than expected

### ISSUE THREAD

**Issue by azah** [deluan/navidrome#373]
![2020-06-29_10-49](https://user-images.githubusercontent.com/9789467/86021759-fb84fe80-ba18-11ea-8b48-e3884c6e6cb1.png)

**Comment by deluan** [comment]
Very weird. I'll take a look and let you know if I need any more info. Thanks for the report

**Comment by deluan** [comment]
You are using the latest from master, right? I found an issue with the import (where the total is calculated)

**Comment by deluan** [comment]
You will need to reimport your library. If it is just a few and you don't want to do a full import, just `touch` the folders that contains albums with the wrong count.

**Comment by deluan** [comment]
Duration is also wrong. Reopening....
