### ISSUE TITLE
Support playlists (also with Subsonic API)

### ISSUE THREAD

**Issue by alex-phillips** [deluan/navidrome#39]
This looks great! Would love to see playlist support.

**Comment by deluan** [comment]
Thanks for trying Navidrome!

Playlists are already supported through the Subsonic API. Try to use it with your client and let me know if you have any issues. I'll leave this issue open, so please report back.

For the Navidrome UI, yes, it is missing playlists and a whole bunch of things. I'm rewriting the communication of the UI with the server this week, so I can easily start adding new features to the UI. Stay tunned :)

**Comment by alex-phillips** [comment]
Great! I use my own UI with subsonic servers and playlists worked! Thanks for responding.

**Comment by deluan** [comment]
Great! Is your UI open source, available somewhere? I'd like to add it to my tests. If you want to keep the chat going, I created a Discord server to discuss features and bugs: https://discord.gg/xh7j7yF 

Right now it is a Ghost Town, hehe, but I hope the brave souls that are trying Navidrome in its early days will jump aboard.

**Comment by deluan** [comment]
I'm going to close this, as support from the Subsonic API is already in place, and the Web UI will be implemented as part of #10
