### ISSUE TITLE
armv5 support

### ISSUE THREAD

**Issue by nikarh** [deluan/navidrome#395]
Hi, any particular reason there are no releases for armv5? This target is still supported by go.

**Comment by deluan** [comment]
No particular reason, but every platform adds up to the build time. If there is demand I can add it. Do you need it?

**Comment by nikarh** [comment]
Right now I am running navidrome on armv5 Nas, and it's somewhat painful to compile. Since I don't have a crosscompilation toolchain on my x86-64, and nodejs dropped armv5 support, I have to compile ui on my pc, copy it to Nas and continue compilation from there. So yes, I would be happy if I didn't have to go through it 😊.

**Comment by deluan** [comment]
Sure, I'll add it to the automated release. Can you verify it is working?

[navidrome_v0.24.0-SNAPSHOT_Linux_armv5.tar.gz](https://github.com/deluan/navidrome/files/4907764/navidrome_v0.24.0-SNAPSHOT_Linux_armv5.tar.gz)

**Comment by nikarh** [comment]
Thank you, it seems that everything is working with the build you have provided.
