### ISSUE TITLE
Loading music from 2 devices

### ISSUE THREAD

**Issue by n4562** [deluan/navidrome#396]
Hello,

So I've got music files on two devices. I'd like navidrome to scan both. My current workaround is to soft link one in the other to "show" navidrome a single folder. Unfortunately navidrome doesn't scan the soft link
Any other workarounds?

Thanks

**Comment by deluan** [comment]
Are you sure? Navidrome has supported symlinks for a while now: #193

**Comment by n4562** [comment]
Thanks @deluan, yes you're right. I did search for past issues concerning links, but I seem to have missed symlinks.
I am on docker latest so I've got that commit.
Interestingly, if I symlink pre-docker (before starting container) things don't work (in the sense that navidrome won't scan, but I can ls from inside the container). If I symlink later on (from inside the container), things do work.
Anyways, current workaround works ok, as you mentionned #192 will be the right way.
Thanks again.

**Comment by deluan** [comment]
Symlink before starting the container should work.Are you using absolute or relative symlinks? They should be relative, as the absolute paths most probably will be different inside the container because volume mappings. If it is not working, feel free to reopen this, so we can investigate more.
