### ISSUE TITLE
Navidrome won't show cover art from external files

### ISSUE THREAD

**Issue by TheForcer** [deluan/navidrome#399]
After now having updated to 0.24, Navidrome does not seem to fetch external Cover Art files for me and shows the default blue vinyl. Most of my collection consists of FLAC files with no embedded image files, but cover.jpg files in the album directories. The albums with embedded artworks show up fine.

For further testing, I also set the ImageCache option to 0 and priority as well in my compose file, but that did not help.

```
ND_IMAGECACHESIZE: 0
ND_COVERARTPRIORITY: "cover.*, folder.*, embedded"
```

Got an idea what could help?

Typical request would look like this:
```
time="2020-07-13T11:39:22Z" level=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=7975fc3601e2/0L9hnqby8i-000041 username=navidrome_user version=1.8.0
time="2020-07-13T11:39:22Z" level=trace msg="SQL: `SELECT * FROM user WHERE user_name = ?`" args="['navidrome_user']" elapsedTime="577.511µs" requestId=7975fc3601e2/0L9hnqby8i-000041 rowsAffected=1
time="2020-07-13T11:39:22Z" level=trace msg="Looking for media file art" id=not_found requestId=7975fc3601e2/0L9hnqby8i-000041
time="2020-07-13T11:39:22Z" level=trace msg="SQL: `SELECT starred, starred_at, play_count, play_date, rating, media_file.* FROM media_file LEFT JOIN annotation on (annotation.item_id = media_file.id AND annotation.item_type = 'media_file' AND annotation.user_id = 'ab581119-f9ce-495c-bbda-68810307e4e5') WHERE id = ?`" args="['not_found']" elapsedTime="607.437µs" requestId=7975fc3601e2/0L9hnqby8i-000041 rowsAffected=0
time="2020-07-13T11:39:22Z" level=trace msg="Retrieving cover art from file" error="data not found" path= requestId=7975fc3601e2/0L9hnqby8i-000041 size=0
time="2020-07-13T11:39:22Z" level=warning msg="Error extracting image" error="empty path given for cover" path= requestId=7975fc3601e2/0L9hnqby8i-000041 size=0
time="2020-07-13T11:39:22Z" level=debug msg="HTTP: GET http://127.0.0.1:82/rest/getCoverArt?u=navidrome_user&t=61774f36c02222268740133d0a2222a3&s=1594639626716&f=json&v=1.8.0&c=NavidromeUI&id=not_found" elapsedTime=9.986888ms httpStatus=200 remoteAddr=88.152.185.106 requestId=7975fc3601e2/0L9hnqby8i-000041 responseSize=378613 userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
```

_Originally posted by @TheForcer in https://github.com/deluan/navidrome/issues/308#issuecomment-657512336_

**Comment by deluan** [comment]
What was your previous version? Was it displaying the cover arts correctly? If it was, what was the value of `ND_COVERARTPRIORITY`?

**Comment by TheForcer** [comment]
Previous version was 0.22, it didn't show any cover art since only 0.24 supports external cover art files. However, embedded cover art files were shown correctly. 
I only added the cover art priority setting to debug the issue on 0.24, it was previously unset/left to default.

**Comment by deluan** [comment]
Ah yes, my bad: it was introduced in 0.24!

Did you rescan the library? A full rescan is required, as covers are detected during scan. I just released 0.25.0, that has experimental support for forcing a full rescan. Just execute: ` docker-compose run navidrome scan -f`

Let me know if this is the issue and if it helps you

**Comment by TheForcer** [comment]
Ah, alright, didn't know about the required scan.
Will update and re-scan :)

**Comment by TheForcer** [comment]
The rescan did indeed fix the issue, all the cover arts are now showing up.
Thank you very much for your help as always 😀
