### ISSUE TITLE
Scanning not done on full library

### ISSUE THREAD

**Issue by alex-phillips** [deluan/navidrome#40]
Just spun this up in docker and it automatically started scanning. It finished but only made into the 'B's. Hitting refresh on the UI doesn't seem to kick off a new scan. If it does, then it finishes almost immediately with no new files.

**Comment by deluan** [comment]
Refresh in the UI is to refresh the view, not start a rescan. Can you try removing the data/navidrome.db and start again with `-loglevel=trace`, then post the logs here? 

Also, what version of `ffmpeg` are you using?

**Comment by alex-phillips** [comment]
Will do that and post the logs when done. Using the docker container, so whichever version comes baked in.

**Comment by alex-phillips** [comment]
I blew everything away and restarted and it looks like it completed the scan. I guess we can close this for now.
