### ISSUE TITLE
Database stuck empty after startup with music folder un-mounted

### ISSUE THREAD

**Issue by InfinityTotality** [deluan/navidrome#407]
I recently rebooted my server without a ZFS kernel module properly installed, and Navidrome started up with the drive containing my music unmounted. It discovered my music folder was now an empty folder and completely cleared the database. Now, with the drive mounted again, it won't read anything from the folder. I've verified that the files are all present and accessible within the container. My other containers are able to access them as normal. I've had this issue with Airsonic in the past as well, though not in this case, but that at least has a menu option to drop the database and start over. Is there any way to clear this condition without deleting the entire configuration?

**Comment by deluan** [comment]
Try `touch`ing your Music Folder before starting Navidrome. 

Or if you are using version 0.25.0, there's experimental support to force a rescan:
```
$ navidrome scan --datafolder=<db directory> -f
```

Let me know if this helps

**Comment by InfinityTotality** [comment]
I touched an empty file in the root of the music folder (with it already running though), and it rescanned only that folder. I've gotten at least most of the files into the database by touching and removing a file in each folder, but I suspect any files in sub-directories will still be missing. I'll test the force rescan once it finishes the current update. Am I correct in assuming the docker image doesn't use a .toml file? It doesn't seem to be running with one as an argument or have one in the data directory

**Comment by InfinityTotality** [comment]
`# ./navidrome scan -f` within /app in the container seems to have done the trick, thanks!

**Comment by deluan** [comment]
Great! If you are using docker compose, you can also run it like this:
```
$ docker-compose exec navidrome scan -f
```

Will close this now, feel free to reopen if you find any related issues
