### ISSUE TITLE
[feature request] play entire artist from listing

### ISSUE THREAD

**Issue by tedder** [deluan/navidrome#409]
When I'm on the artist listing, I'd like a play button so I can simply play all 42 songs from 11 albums by a given artist, even if it's hidden in a triple-dot like on the album page.

Does that make sense? If not I'll whip up some chart-brut screenshots.

**Comment by deluan** [comment]
Yes, it makes sense. I'll add it to a Artist Context menu (the triple dot menu similar to the ones in Albums and Songs). The number of songs to be played may need to be limited (maybe 1000, 1500), to avoid performance issues. Is that ok?

**Comment by tedder** [comment]
for me at least, it's fine. My use case is ~100 songs, max.

and thanks- just getting back into 'drome after a few months.

**Comment by williamkray** [comment]
i'd also like to see this ability in the search/filter view, etc... for example, i have many starred albums, i'd like to be able to shuffle-play everything there.

i don't see issues with limiting the number of tracks for performance reasons.

**Comment by deluan** [comment]
@tedder Forgot to close this issue, it was implemented in v0.30.1

@williamkray, yes, I'll implement this, just trying to figure out the best way to do it without complicating the code too much. As a matter of fact, it is already working in the song view, "Shuffle All" respects the filters in that view.
