### ISSUE TITLE
The config file location cannot be set via environment variable.

### ISSUE THREAD

**Issue by duckpuppy** [deluan/navidrome#415]
There is currently no way other than using the command line option to set where the config file is read from. The documentation had a mention of using `ND_CONFIGFILE`, but that did not work.

From the looks of things, there is no binding for the `configFile` parameter to Viper, which is reading the variables from the environment if they exist.

https://github.com/deluan/navidrome/blob/7c3fd38559635715bf96b99f0152bea89db542ba/cmd/root.go#L67-L95

**Comment by deluan** [comment]
I have to handle the configfile explicitly, as loading it is a catch 22 situation. Commit d46a8cf should fix the issue. Let me know otherwise
