### ISSUE TITLE
Provide pre-built binaries for aarch64

### ISSUE THREAD

**Issue by snglth** [deluan/navidrome#431]
> If you can’t find a pre-built binary for your platform, you should open an issue in the project’s GitHub page.

Well that's why I'm here.

**Comment by deluan** [comment]
Isn't it just the [ARM64](https://en.wikipedia.org/wiki/AArch64)? If that's the case, there's ARM64 builds already. Let me know if they work for you

**Comment by snglth** [comment]
Yep, that it, works just fine. Thank you!
