### ISSUE TITLE
Systemd "SystemCallFilter=~... @privileged ..." prevents listening on TCP/4533

### ISSUE THREAD

**Issue by keith24** [deluan/navidrome#433]
**OS**: _Ubuntu 18.04_
**Verison**: _0.29.0_

I noticed that when I ran navidrome.service using [the service file from the installation docs](https://www.navidrome.org/docs/installation/pre-built-binaries/#create-a-systemd-unit), Navidrome wouldn't open port 4533 when the service was started.  

I was able to work around this by removing `@privileged` from the `SystemCallFilter` line in the file, leaving: 

```
SystemCallFilter=~@clock @debug @module @mount @obsolete @reboot @setuid @swap
```

Not sure if this is a bug or what.

**Comment by deluan** [comment]
Thanks for the report! That service file is meant to be an example, maybe this fact is not explicit in the docs. I'll revise the docs, and will probably only put in the example a bare minimum configuration that should work on most versions.
