### ISSUE TITLE
[Feature Request] Add sort by Folder Structure

### ISSUE THREAD

**Issue by darktweek** [deluan/navidrome#434]
Hi !

Very interesting project.

I have a very huge collection, and a lot of old music rips by myself on old CD witouth id3tagg.
Can you juste add a sortlist by folder structure?
Like My_music/Artist/album/song.mp3?

And the [Multi Music Folders](https://github.com/deluan/navidrome/issues/192) option is also very interesting for me.

**Comment by deluan** [comment]
Thanks for trying Navidrome. When the files does not have a `title` tag, it uses the full path as a title. So if you sort songs by title isn't that enough?

**Comment by darktweek** [comment]
I haven't noticed this! I will check.
Retex soon.

**Comment by darktweek** [comment]
I have tried. It makes weird things (mix of ID3TAGG and title gen) but it's my fault.Very nice project! I will use this more harder and wait for the multiple source :PWhen this last thing will be added, I can swipe for Navidrome instead of Airsonic.
