### ISSUE TITLE
Demosite

### ISSUE THREAD

**Issue by The-Exterminator** [deluan/navidrome#439]
The Demo on you site, is not working -:(

**Comment by deluan** [comment]
Wat!?! Thanks for letting me know! Time to setup monitoring for the demo site :)

**Comment by deluan** [comment]
Back online! Will leave it open to track my work on monitoring setup

**Comment by deluan** [comment]
Done. Thanks again!

**Comment by The-Exterminator** [comment]
Your welcome -:)

**Comment by The-Exterminator** [comment]
Can you make a demo to admin, so people can see the admin options. ???

**Comment by deluan** [comment]
The problem with enabling admin mode in the demo is that someone could easily mess with the installation, so I rather not do this. That's actually the same approach used by other self hosted demo sites.

But it is so easy to get navidrome up and running, there are pre compiled binaries for all major platforms, add docket images. And just to see the admin options, you don't even need to configure anything, just run navidrome and go to http://localhost:4533
