### ISSUE TITLE
Cover art is not displaying in Navidrome for some albums, despite existing

### ISSUE THREAD

**Issue by SpencerDub** [deluan/navidrome#450]
I just installed Navidrome 0.30.1 for YunoHost via @ericgaspar's [package](https://github.com/yunohost-apps/navidrome_ynh). For the essentials--playing music, searching--it appears great! But unfortunately, much of my music is displaying the default Navidrome cover art image (the blue vinyl record), *despite* having cover art in the folder.

My logs occasionally show messages like this:

```
Aug 18 07:49:44 navidrome[2255]: time="2020-08-18T07:49:44-07:00" level=warning msg="Error extracting image" error="read /media/mediashare/Music/Adele/25/folder.jpg: input/output error" path=/media/mediashare/Music/Adele/25/folder.jpg requestId=xanderwhart.us/xHMegKbGDu-000334 size=300
Aug 18 07:49:44 navidrome[2255]: time="2020-08-18T07:49:44-07:00" level=error msg="Error retrieving coverArt" error="write tcp 127.0.0.1:4533->127.0.0.1:45534: write: broken pipe" id=al-66c96127dc389ca026c318a37b984a42 requestId=xanderwhart.us/xHMegKbGDu-000338
Aug 18 07:49:44 navidrome[2255]: time="2020-08-18T07:49:44-07:00" level=warning msg="API: Failed response" error=0 message="Internal Error" requestId=xanderwhart.us/xHMegKbGDu-000338
Aug 18 07:49:44 navidrome[2255]: time="2020-08-18T07:49:44-07:00" level=error msg="Error sending response to client" error="write tcp 127.0.0.1:4533->127.0.0.1:45534: write: broken pipe" payload="{\"subsonic-response\":{\"status\":\"fail\",\"version\":\"1.12.0\",\"type\":\"navidrome\",\"serverVersion\":\"0.30.1 (a2e0acd)\",\"error\":{\"code\":0,\"message\":\"Internal Error\"}}}" requestId=xanderwhart.us/xHMegKbGDu-000338
Aug 18 07:49:44 navidrome[2255]: time="2020-08-18T07:49:44-07:00" level=error msg="Error retrieving coverArt" error="write tcp 127.0.0.1:4533->127.0.0.1:45536: write: broken pipe" id=al-8872d23b41a876fcdc13620eb6f1e475 requestId=xanderwhart.us/xHMegKbGDu-000339
Aug 18 07:49:44 navidrome[2255]: time="2020-08-18T07:49:44-07:00" level=warning msg="API: Failed response" error=0 message="Internal Error" requestId=xanderwhart.us/xHMegKbGDu-000339
Aug 18 07:49:44 navidrome[2255]: time="2020-08-18T07:49:44-07:00" level=error msg="Error sending response to client" error="write tcp 127.0.0.1:4533->127.0.0.1:45536: write: broken pipe" payload="{\"subsonic-response\":{\"status\":\"fail\",\"version\":\"1.12.0\",\"type\":\"navidrome\",\"serverVersion\":\"0.30.1 (a2e0acd)\",\"error\":{\"code\":0,\"message\":\"Internal Error\"}}}" requestId=xanderwhart.us/xHMegKbGDu-000339
```

Another example, which corresponds to clicking on an album that's displaying without cover art but has a valid cover art image:
```
Aug 18 08:01:21 navidrome[2255]: time="2020-08-18T08:01:21-07:00" level=warning msg="Error extracting image" error="read /media/mediashare/Music/Ylvis/The Fox/folder.jpg: input/output error" path="/media/mediashare/Music/Ylvis/The Fox/folder.jpg" requestId=xanderwhart.us/xHMegKbGDu-000414 size=0
```

I've specified how cover art should be searched for in my `navidrome.toml` file:

```
CoverArtPriority = "folder.*,cover.*,embedded,front.*"
```

But a music folder can contain a `folder.jpg` and still fail to display the cover image.

**Comment by deluan** [comment]
Can you confirm the images exists and attach one of these images here (ex: `/media/mediashare/Music/Ylvis/The Fox/folder.jpg`)?

**Comment by SpencerDub** [comment]
Sure! They exist. Here's that image:
![folder](https://user-images.githubusercontent.com/4674927/90533056-d7968d00-e12c-11ea-9cc5-2fa09523df9b.jpg)

**Comment by deluan** [comment]
Were you able to rescan your library after changing the `CoverArtPriority` option? 

If yes, can you send me a zip file of one of the folders, including songs and cover art? Ping me on Discord with the link to the zip file

**Comment by SpencerDub** [comment]
> Were you able to rescan your library after changing the `CoverArtPriority` option?

I was! I got a lot of "Finished processing changed folder" messages, including for this Ylvis folder in question:

> INFO[0023] Finished processing changed folder            dir="/media/mediashare/Music/Ylvis/The Fox" elapsed=7.327468ms purged=0 updated=0

Still no change, though.

I'll zip up a folder and send it to you shortly!

**Comment by deluan** [comment]
Problem found and solved: After troubleshooting over Discord, we figure out that this was happening only with large images. The music folder was mounted over SMB/CIFS v1.0:
```
//192.168.0.1/sda1 /media/mediashare cifs vers=1.0,credentials=/home/admin/.smbcredentials,x-systemd.automount,noauto 0 0
```

After changing the protocol to v2.0 and clearing the browser's cache. Everything worked as expected.

**Comment by IsidoreIsou** [comment]
Hey, I got the same problem on a yunohost Navidrome (0.40.0 (8799358a)), 
* Some covers shows some don't
* All is tagged with Picard and embedded

> After changing the protocol to v2.0 and clearing the browser's cache. Everything worked as expected.

Would you mind explaining me how I can do that? How can I check how my music folder is mounted? Can't find it alone... Thanks!

**Comment by deluan** [comment]
I don't personally use Yunohost nor SMB/CIFS, but I assume the config `//192.168.0.1/sda1 /media/mediashare cifs vers=1.0,credentials=/home/admin/.smbcredentials,x-systemd.automount,noauto 0 0` would go in a file like `/etc/fstab`. You have to find it and change `vers=1.0` to `vers=2.0`

I think the OP used this link: https://askubuntu.com/questions/956361/cifs-mount-returns-input-output-error-on-frequent-file-read
