### ISSUE TITLE
Strange webplayer behavior if re-opening session

### ISSUE THREAD

**Issue by williamkray** [deluan/navidrome#457]
to reproduce:
1. open navidrome web ui (tested in firefox)
2. build up play queue, play some music
3. pause (or don't) after a few songs
4. close the browser tab
5. re-open the navidrome web ui

expected results:
the player would open in a paused state, ready to play the last song that was playing when the player was closed.

current results:
the player immediately skips through all songs in the play queue in sequence, but does not play any of them, and finishes on the last song in the queue. no music is ever played, and a song from the queue has to be chosen for the player to play any music.

**Comment by deluan** [comment]
Thanks for the report. This started happening with a recent upgrade of the upstream react player dependency (in release 0.27.0). I'll check if I can at least minimize the ugly behaviour

**Comment by AndersMoberg** [comment]
I believe this has relation to the browser autoplay settings. If you set those to allow autoplaying media, I think you will not experience this problem any longer.

**Comment by adamvlasak** [comment]
Hello, my desktop browser is MS Edge 85.0.564.51 (Win 10 2004). I am having same issue. Basically every time I open the page with navidrome it immediately tries to play last played song and I need to pause playback first. I would prefer an option to disable continuation of playback if session is re-opened. What do you think?

On mobile MS Edge on Android it shows playback dialog with controls and it skips few songs until stream starts to work again.  There's actually no chance to stop playback for me (I know it might be unrelated bug but it relates to skipping tracks) - the circle playback indicator I can drag it over the screen but does not react to tap or something to show modal playback dialog with playback controls.

Hope it helps a bit :)

BTW. this solution is something I've been searching for ages :) Thanks! I love it works on my raspberry pi 3 <3

**Comment by deluan** [comment]
>If you set those to allow autoplaying media, I

Hey @AndersMoberg , where can I find this setting in Chrome?
