### ISSUE TITLE
Some clients aren't getting cover art while browsing by folder

### ISSUE THREAD

**Issue by duckpuppy** [deluan/navidrome#46]
I've tried a couple of Android subsonic clients (D-Sub and Music Stash so far), and D-Sub will show cover art where Music Stash doesn't. Looking at Navidrome logs, it looks like D-Sub is making separate `getCoverArt` calls where Music Stash does not... both are calling `getAlbumList2`. When connecting to AirSonic, both clients get cover art.

I've tried digging into the Subsonic API schema to see where the disconnect is but I'm unable to find it. I can try to provide logs if that will help as long as I know what I'm looking for.

**Comment by deluan** [comment]
Weird, I haven't tested with Music Stash in a while, but it used to work... I'll check it out tonight. Thanks for the report

**Comment by deluan** [comment]
With the latest versions, Navidrome 0.4.1 and Music Stash 1.5.5, it displays the covers correctly when browsing by tag, but when browsing by folders, it does the getCoverArt calls but does not show any cover... 

I'll investigate why browsing by folders is not showing covers (even though Jamstash also browses by folder and it shows them correctly.

Can you please confirm the versions you are using? Also, can you try it with Jamstash?

**Comment by deluan** [comment]
Just note that Music Stash support is still a work in progress, as it does not silently ignores errors from the server, it does not respects the API version returned by the server. 

Having said that, I plan to support it really soon, as I really enjoyed it's interface

**Comment by duckpuppy** [comment]
I'm was running Navidrome 0.4.0 (The latest docker image at the time I pulled it) and Music Stash 1.5.5, and was also browsing by tags, not folders.  I've now pulled the newer 0.4.1 image and it seems that cover art is working via tags (as you said). I don't browse by folders generally so my use case is covered, though if there's still a bug with browsing by folders this bug should stay open, I suppose - I will leave that to you if you want to open a more specific bug or edit the description of this one.

Thanks for the great replacement for The *sonic apps, though... they're all very resource hungry and I've been looking at doing exactly this (in golang, no less) for a while. I look forward to seeing where this goes.

**Comment by deluan** [comment]
Yeah, I'll leave it open for now, to track the work on the bug for folder browsing.

So you are a developer? Nice! If you want to contribute to Navidrome, let me know and I can provide you with some guidence on how to start. There are lots to do: Last.FM integration, UI (React.JS) work, other APIs, Smart Playlist support... If you are interested, just join the project's Discord: https://discord.gg/xh7j7yF
