### ISSUE TITLE
'Star' icon overlaps song/album year on mobile

### ISSUE THREAD

**Issue by danshilm** [deluan/navidrome#466]
This seems like a bug from when the star feature was implemented since it looks like it was not an issue when the star icon wasn't here before.

Screenshots for reference:
https://ibb.co/2k2q5Lf
https://ibb.co/WF0w84y

This bug is not present on the Artist page however and seems to only be a lack of padding for the Material UI List Items which have a star icon (secondary action is what it's called from what dev tools says).

Navidrome Version 0.31.0 (0aceda9)

**Comment by deluan** [comment]
Hey @danshilm , I added a little extra padding between the info and the star icon. I don't think I can make it better without writing a custom List component, so I'm closing this for now and may revisit this in the future. Let me know if this is enough for you, and feel free to reopen the issue if you think it is not.

<img width="414" alt="Screen Shot 2020-09-24 at 9 30 00 PM" src="https://user-images.githubusercontent.com/331353/94216358-2dd5b900-fead-11ea-9708-f797de967ccb.png">
