### ISSUE TITLE
Artists view is not working with Music Stash (Android client)

### ISSUE THREAD

**Issue by duckpuppy** [deluan/navidrome#47]
Music Stash is using an API that was introduced in API version 1.11.0 (I think) to get artist info (`getArtistInfo2`) when browsing by artist and choosing an artist to view. Navidrome returns a 404 for `getArtistInfo2` and `getTopSongs`.

I know Music Stash is not necessarily the only client being targeted, and that Navidrome is advertised as using API version 1.8.0, so if this is just a known "won't fix", then please close this ticket.

**Comment by duckpuppy** [comment]
Also... I see that this is mentioned in the Last.FM integration, so maybe this is a duplicate... :)

**Comment by deluan** [comment]
Yes, this is a known issue, and these endpoints are part of the planned initial [Last.FM support](https://github.com/deluan/navidrome/issues/18). I'll close this issue and if you have any additional concerns regarding last.FM, please add to the issue https://github.com/deluan/navidrome/issues/18

**Comment by deluan** [comment]
Hey, just to let you know that I added a fake getArtistInfo2 endpoint. This allows Music Stash to display the artist view (with empty bio/pict, but let you browse the artist's albums). If you want to give it a try, it's already in master (commit ce11a2f3be0610a8a88bbf8fcce123acb3d3a784), also in the latest `develop` docker image.

This is just a placeholder. Right now I'm working on some scanner optimizations, and fine-tuning the transcoding, the Last.FM integration will be next.

**Comment by duckpuppy** [comment]
I've updated to the newest Docker image and tried Music Stash - it's working pretty well. Once I get some free time, I've forked Navidrome and I'll start getting into the code to see if I can provide some PRs.
