### ISSUE TITLE
Feature request: speed/tempo control

### ISSUE THREAD

**Issue by jacostag** [deluan/navidrome#477]
I am loving navidrome, is fast, and super small, I am also using it to play audiobooks, and with the api compatibility it already supports bookmarks and saving position, is it possible to add spped/tempo control to the web interface?

Thanks

**Comment by deluan** [comment]
Thanks for trying Navidrome! 

This would need to be implemented by the upstream [React Player](https://github.com/lijinke666/react-music-player) library. I'd suggest opening an issue there and hearing from its author.

**Comment by jacostag** [comment]
Thank you
