### ISSUE TITLE
Playlist "public" setting reset on update

### ISSUE THREAD

**Issue by ForgetfulMagnet** [deluan/navidrome#479]
Every time I update to the latest version all playlists have their "public" setting reset. I'm sharing my playlists with other users, so I have to re-enable them with every new update. Since theres no "enable all" button, I have to click on the radio button for every playlist. I have a lot of playlists which means a lot of clicks. 

It would be preferable if the setting persisted across versions or if there was an enable all button for the public setting.

**Comment by deluan** [comment]
Thanks for the report, this is not the intended behaviour. Will try to fix for the next release

**Comment by deluan** [comment]
Sorry, but I was not able to reproduce this. Can you send me more info, like from/to what version did you upgrade last time that you had this issue? 

Can you reproduce it going back to 0.31.0 and upgrading again to 0.32.0? If you can, can you set the loglevel to trace when starting version 0.32.0 after the upgrade? Make a backup of the data folder just in case...

Thanks

**Comment by deluan** [comment]
Hey @ForgetfulMagnet , were you able to take a look at this? As I said, I'm not able to reproduce in my 3 environments (Docker, VPS and running locally the binary)

**Comment by ForgetfulMagnet** [comment]
It happened again with the newest update.

**Comment by deluan** [comment]
Are you using Docker? If yes, are you mapping the DataFolder volume? If not, can you send me some more information? How is your setup? Which Platform/OS? Can you post your configuration here?

**Comment by ForgetfulMagnet** [comment]
- Docker, yes.
- Mapping "ND_DATAFOLDER" to /docker/navidrome (cache folder and db-files are located here, so mapping must work)
- Running on a Synology Diskstation
- Playlists are auto-imported .m3u

**Comment by deluan** [comment]
Does this happen only for the imported `.m3u` files? Can you try creating a playlist through the UI and validate if the issue happens with it?

**Comment by caler1s** [comment]
I've had this issue with playlists created through auto-importing from .m3u files (unrelated to any Navidrome update). Whenever I update an .m3u locally and it's imported again, the playlist that was auto-imported from the .m3u has its public toggle set back to disabled.
I'm using Docker on a QNAP NAS.

**Comment by deluan** [comment]
Thanks for the patience waiting for this. I just pushed a fix, and when upgrading to the next release (0.35.0) or updating an auto-imported playlist, this should not happen anymore.

If it still doesn't work for you, feel free to re-open the issue, and I can investigate further.
