### ISSUE TITLE
[0.33]: TagLib prefers id3v1.x tags over id3v2.x

### ISSUE THREAD

**Issue by certuna** [deluan/navidrome#492]
Just tried the new taglib-based metadata scanner: in some (all?) cases when there's two tags, it prefers id3v1.x tags over id3v2.x, resulting in truncated titles, etc.

**Comment by deluan** [comment]
Weird, I didn't see this behaviour in my collection... Can you please attach a sample mp3 file here?

**Comment by certuna** [comment]
It's a malformed tag probably - iTunes and Picard see id3v2.4 tags, but kid3 (another macOS tagger) only sees id3v1. Here's one of the files in question:

[02. Baltimora - Tarzan Boy (Ultrasound Extra Long Extended Mix).mp3.zip](https://github.com/deluan/navidrome/files/5201709/02.Baltimora.-.Tarzan.Boy.Ultrasound.Extra.Long.Extended.Mix.mp3.zip)

**Comment by deluan** [comment]
Yeah, I see the file has no issues.... If anyone finds this issue, please feel free to reopen and attach a sample mp3 file.
