### ISSUE TITLE
How to disable transcoding?

### ISSUE THREAD

**Issue by praise-you** [deluan/navidrome#494]
Hi deluan,
Thanks a lot for navidrome!
I've searched the documentation and couldn't find a way to disable transcoding for ever. I'd like to just stream the files as they are.
Cheers!

**Comment by praise-you** [comment]
Thank you very much for taking from your time to answer my question. It seemed to be logical that no transcoding would happen but it wasn't written so I had to ask. :)

**Comment by deluan** [comment]
I have to do some changes in the transcoding system (#351), once I finish that I'll write a page explaining how transcoding in Navidrome works and how to configure it. Thanks for the feedback.

**Comment by praise-you** [comment]
You're welcome!
