### ISSUE TITLE
The ID3 compilation flag only works with mp3 files

### ISSUE THREAD

**Issue by thias** [deluan/navidrome#495]
I've pointed navidrome at my music library, and ended up with a lot of "duplicate" albums. The typical multi-artists ones. I'm assuming Kodi has some sort of special case for this, since it manages to group them properly, but I remember having the same issue with Airsonic when I tried it.

My current solution is to set the non-standard iTunes "compilation" flag to 1 on the files, and that seems to do the trick, which is great! But... I have a few of these compilations in ogg vorbis and even in mpc format, and it doesn't seem to work on those, even though the tagging program I use (puddletag) happily adds it. It's "itunescompilationflag" set to 1, and I've also tried with "compilation" as that's what ffmpeg shows the field as on mp3 files, but to no avail.

My understanding is that this field isn't standard as far as ID3 goes. And the "Various Artists" issue isn't something new for most people with large-ish music collections. I'm not too keen on abusing the albumartist as "Various" or "Various Artists", especially since everything already works fine in Kodi and that the flag seems to already be honored in most cases.

Is there a way to have Navidrome also consider this flag for files that aren't mp3?

Here is ffprobe output from a working mp3 tag:
```
Input #0, mp3, from 'Hed Kandi 111 - Ibiza 2011/CD1/01. Example - Changed The Way You Kiss Me (Felix Leiter & Mark Maitland Remix).mp3':
  Metadata:
    title           : Changed The Way You Kiss Me (Felix Leiter & Mark Maitland Remix)
    artist          : Example
    track           : 01/15
    album           : Hed Kandi: Ibiza 2011
    disc            : 1/3
    date            : 2011
    genre           : House
    compilation     : 1
  Duration: 00:06:12.30, start: 0.000000, bitrate: 192 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s
```
And here is a non-working ogg tag:
```
Input #0, ogg, from 'Hed Kandi 006 - Winter Chill/CD1/01 - Nitin Sawhney - Letting Go.ogg':
  Duration: 00:04:52.56, start: 0.000000, bitrate: 120 kb/s
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      date            : 1999
      artist          : Nitin Sawhney
      disc            : 1/2
      album           : Hed Kandi: Winter Chill
      title           : Letting Go
      track           : 01
      genre           : Downtempo
      tracktotal      : 14
      itunescompilationflag: 1
```
I really think the mp3 tag's field is also called "itunescompilationflag" and that it's ffprobe being smart about the name, but trying to set a custom "compilation" tag on the ogg file didn't work.

Thanks a lot for this extremely promising piece of software!

**Comment by deluan** [comment]
Thanks for the detailed report! 

You are right: "Compilation" is an iTunes extension and it is usually stored in the ID3 tags as `TCMP`. But Ogg files should have [Vorbis comments](https://en.wikipedia.org/wiki/Vorbis_comment) and not ID3 tags. And it has provisions for a `compilation` comment. Example from `ffmpeg`:
```
Input #0, ogg, from '../library/Asian Dub Foundation/More Signal More Noise/01-09 Get Lost Bashar.ogg':
  Duration: 00:03:42.00, start: 0.000000, bitrate: 467 kb/s
    Stream #0:0(eng): Audio: vorbis, 44100 Hz, stereo, fltp, 499 kb/s
    Metadata:
      ALBUM           : More Signal More Noise
      ARTIST          : Asian Dub Foundation
      COMPILATION     : 0
      TITLE           : Get Lost Bashar
...
```
and from `taglib`:
```
******************** "../library/Asian Dub Foundation/More Signal More Noise/01-09 Get Lost Bashar.ogg" ********************
-- TAG (basic) --
title   - "Get Lost Bashar"
artist  - "Asian Dub Foundation"
album   - "More Signal More Noise"
year    - "2015"
comment - ""
track   - "9"
genre   - "Alternative"
-- TAG (properties) --
ALBUM                      - "More Signal More Noise"
ARTIST                     - "Asian Dub Foundation"
COMPILATION                - "0"
DATE                       - "2015-07-10"
...
```

Not sure why your tagging program is doing this.... Can you send me one of the Ogg files?

One workaround is setting the AlbumArtist to something like "Various Artists", and Navidrome will group the tracks under the same album

**Comment by thias** [comment]
I've sent you a link to some sample ogg/vorbis files by email. The tagging programs I'm using are EasyTag for most of my tagging and PuddleTag for adding the non-standard tag, as it allows to easily inspect all tags and add/remove arbitrary tags. They both seamlessly work with mp3, ogg/vorbis and mpc files, so I have no idea if they're properly using vorbis comments or shoving in some ID3 tags inside the ogg container (is that even possible?).

**Comment by deluan** [comment]
Thanks for the files. When I added them as is to my Navidrome server, they were separated as you said. But after setting the `compilation` tag to 1 (and removing the `itunescompilationflag `, using MusicBrainz Picard, the tracks were grouped as expected in the UI and the tag was recognized by `ffmpeg` with the correct name:
```
Input #0, ogg, from 'Paris Is Sleeping - Respect Is Burning/01. Catalan FC - Respect is Burning.ogg':
  Duration: 00:03:37.13, start: 0.000000, bitrate: 123 kb/s
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      track           : 01
      ARTIST          : Catalan FC
      TITLE           : Respect is Burning
      ALBUM           : Paris Is Sleeping - Respect Is Burning
      TOTALTRACKS     : 14
      DATE            : 1996
      GENRE           : House
      COMPILATION     : 1
      TRACKTOTAL      : 14
```

So, I think the issue may be that the softwares you are using for tagging do not handle `compilation` properly?

**Comment by thias** [comment]
You are absolutely correct. I could have sworn having tried "compilation" as well for the ogg/vorbis files, but mustn't have. It works fine! Thanks for looking into this, and sorry for wasting your time.
