### ISSUE TITLE
Distorted image cover in Albums view

### ISSUE THREAD

**Issue by ericgaspar** [deluan/navidrome#496]
I have imported a mp3 with a rectangle image who looks like this:

![Capture d’écran 16](https://user-images.githubusercontent.com/46165813/93021776-ec0f5d80-f5e4-11ea-8b5d-316ae8e8dda2.png)

in the Albums view it looks distorted:
![Capture d’écran 14](https://user-images.githubusercontent.com/46165813/93021792-0a755900-f5e5-11ea-9608-82ea51e2b528.png)

and in the Album page it looks OK:
![Capture d’écran 15](https://user-images.githubusercontent.com/46165813/93021805-22e57380-f5e5-11ea-8306-2ad58541b507.png)

**Comment by deluan** [comment]
Yeah, I know, this is not great, but I had a hard time to make the Material-UI Grid List work properly for the Albums view. I'm planning to rewrite the Albums view at some point, and will make sure this works as expected.

**Comment by deluan** [comment]
Fixed by #658
