### ISSUE TITLE
Files with timestamps in the future are detected as changed on each scan

### ISSUE THREAD

**Issue by thias** [deluan/navidrome#499]
Don't ask why, but I had an album with all files modified in the year 2030...

I realized after wondering why that single album was being continuously detected as changed.

Step to reproduce:
```
touch -d "`date -d 'now + 1 year'`" *.mp3
```
Then in the logs there's `changedFolders=1 deletedFolders=0` then `added=0 deleted=0 elapsed=637.522537ms folder=music playlistsImported=0 updated=0` over and over.

**Comment by deluan** [comment]
Thanks for the report! Yeah this is expected, and I personally saw this before in my library. But there's no way to fix this, as the scanner depends on timestamps to work properly.  I'm not planning on change this behavior. 

I'm closing the issue for now, but feel free to reopen if you feel this is a show stopper.
