### ISSUE TITLE
about lyrics and songs display way

### ISSUE THREAD

**Issue by KITblue** [deluan/navidrome#504]
We hope to add the function of lyrics display. Moreover, for songs stored in different folders, we can directly display all songs. Click to play instead of browsing the folder

**Comment by deluan** [comment]
Lyrics support is being tracked by #491. 

For your second request, this is how Navidrome works, it ignores folders and group songs by artists/albums. Is that what you mean?

**Comment by deluan** [comment]
Hey @KITblue,  can I close this as lyrics is being tracked in 491?
