### ISSUE TITLE
Add Album Names Under Album Cover

### ISSUE THREAD

**Issue by TheFlatworm** [deluan/navidrome#513]
Would there be a way to have the album name under the album cover à la sub/air sonic?  I have so many albums that I cannot recognize albums just by the cover.

**Comment by deluan** [comment]
This was discussed in our Discord server. The plan is to rewrite the Albums view and one of the main changes is to do this. I'll keep this issue open to track this implementation

**Comment by deluan** [comment]
This was implemented in #608:

<img width="224" alt="Screen Shot 2020-11-03 at 10 06 56 AM" src="https://user-images.githubusercontent.com/331353/98003384-b1dc6400-1dbc-11eb-8ea9-3e2b939f2bfa.png">
