### ISSUE TITLE
Transcoding `format` for Opus should be `opus`

### ISSUE THREAD

**Issue by MoritzMaxeiner** [deluan/navidrome#521]
The default transcoding configuration of Opus lists [`oga`](https://github.com/deluan/navidrome/blob/0403ec2a071ace2768ed80b695ec0f3451ab788a/consts/consts.go#L58) as its `targetFormat`.
`oga` is one possible file name extension for the [`Ogg` container format](https://en.wikipedia.org/wiki/Ogg) and thus could also mean `Vorbis`, `Theora`, or even `FLAC`.
Please change Opus' `targetFormat` from `oga` to `opus` so clients do not have to guess.

I've changed this on my own server manually via `EnableTranscodingConfig`, but I think this change should be the default.

**Comment by deluan** [comment]
I can change it, but I think I copied this configuration from AirSonic (can't remember), and it never caused me any trouble with all clients I tested. Do you have any specific situation it is causing issues?

**Comment by MoritzMaxeiner** [comment]
> I can change it, but I think I copied this configuration from AirSonic (can't remember), and it never caused me any trouble with all clients I tested. Do you have any specific situation it is causing issues?

Did the clients you tested with receive the opus transcoded file, because when I tried DSub (via the long open [trancoding PR](https://github.com/daneren2005/Subsonic/pull/987)), which uses `opus` targetFormat for Opus, I do get the file, but it's in `raw` format instead (which in my case was FLAC), since navidrome's default configuration doesn't understand `opus` targetFormat and falls back to `raw`.

At the end of the day I can always just change my navidrome instance's configuration, so it's not a huge issue, but when there's no standard to follow (and AFAICT the subsonic api doesn't say anything specific about what's allowed as the targetFormat) it's better to choose something that's unambiguous.

**Comment by deluan** [comment]
I'll change this, but I'd like to understand what is causing the DSub issue in your setup. DSub is my main player, and I have it transcoding to Opus with the default Navidrome configuration with no issues:

<p align="left">
    <img height="550" src="https://user-images.githubusercontent.com/331353/94162396-a78d8880-fe54-11ea-90c8-6d0153f4f000.png">
    <img height="550" src="https://user-images.githubusercontent.com/331353/94162408-aa887900-fe54-11ea-83bf-2e6a1e715cd0.png">
</p>

Where are you setting the targetFormat in DSub? I can only set the bitrate.... (I'm using version 5.4.4)

**Comment by MoritzMaxeiner** [comment]
> but I'd like to understand what is causing the DSub issue in your setup. DSub is my main player, and I have it transcoding to Opus with the default Navidrome configuration with no issues:

Via the DSub [pull request](https://github.com/daneren2005/Subsonic/pull/987) I linked to, which adds support for setting [`format`](http://www.subsonic.org/pages/api.jsp#stream) in the request sent to the server:

![transcode](https://user-images.githubusercontent.com/497073/94168750-3e2a6b80-fe8e-11ea-82a3-2a318b11f450.jpeg)

To me the more interesting question is how does navidrome select the transcoding codec when the client (DSub) doesn't specify a `format`?

**Comment by deluan** [comment]
> Via the DSub pull request I linked to

Ops, I missed that, I thought you linked to Navidrome's own [transcoding issue](https://github.com/deluan/navidrome/issues/351), my bad.

It would be great to have this DSub PR merged.... Anyway, I'm changing the default extension for the next release, as you suggested. 

Answering your question, if the client does not specifies a `format`, Navidrome only transcodes the file if a transcoding option is set for the player. The current logic is a bit convoluted, and it will be refactored as part of the issue #351. If you want to understand a bit better how the current logic works, I think it is better to read the test cases: https://github.com/deluan/navidrome/blob/9b1d5c196f600232a6041b127e9311304ff932f5/core/media_streamer_test.go#L74

**Comment by MoritzMaxeiner** [comment]
> Ops, I missed that, I thought you linked to Navidrome's own [transcoding issue](https://github.com/deluan/navidrome/issues/351), my bad.

Ah, I see, no worries.

> It would be great to have this DSub PR merged....

Yes, my own frustration with lack of merging on DSub let me to make [my own fork](https://github.com/MoritzMaxeiner/DStream), where - for now - I just collect those PRs I consider important.

>  Anyway, I'm changing the default extension for the next release, as you suggested.

Awesome, thank you :+1: 



> Answering your question, if the client does not specifies a `format`, Navidrome only transcodes the file if a transcoding option is set for the player. The current logic is a bit convoluted, and it will be refactored as part of the issue #351. If you want to understand a bit better how the current logic works, I think it is better to read the test cases:

I see, well I can report that with the PR I mentioned I pretty much always get the maximum bit rate selected in DSub as the one transcoded to by navidrome. If I select unlimited, I get the default bit rate for the codec/format.

**Comment by deluan** [comment]
> Yes, my own frustration with lack of merging on DSub let me to make my own fork, where - for now - I just collect those PRs I consider important.

It would be awesome if you created GitHub releases (with the final .APKs) for your builds.... ;)

**Comment by MoritzMaxeiner** [comment]
@deluan While I recommend compiling yourself, there's now a pre alpha build available [here](https://github.com/MoritzMaxeiner/DStream/releases/tag/0-alpha-pre).

**Comment by deluan** [comment]
I think the best way would be to setup a GitHub action to auto-release. Anyway, thanks for the build, will give a try!
