### ISSUE TITLE
Compilation issue on old PC

### ISSUE THREAD

**Issue by zoidy** [deluan/navidrome#524]
By default, navidrome will not compile on my system. It must be because my computer is old but but I have managed to resolve the problem. However, I don't know if it will break the compilation on other systems which is why I haven't submitted a pull request. However I wanted to share my modification in case it could be added

1. Compiler runs out of memory when compiling the ui. I was able to fix this by modifying ui/package.json
```"build": "react-scripts build",``` change to ```"build": "react-scripts --max-old-space-size=1492 build",```
2. The TagLib module causes compilation to fail with several errors related to unsupported functionality/syntax in scanner/metadata/taglib/taglib_parser.cpp
Add the ```#cgo CPPFLAGS: -std=c++11``` directive to scanner/metadata/taglib/taglib_parser.go
~~With the above flag, I get some warnings but compilation succeeds and navidrome runs without issue~~ I spoke too soon. The playlist is broken (the official release works just fine)

**Comment by deluan** [comment]
I'll test this changes and let you know. What is your the platform/OS/version?

**Comment by deluan** [comment]
The CPPFLAGS in `taglib_parser` should not influence in playlist behaviour.... Are you sure that was the problem?

**Comment by zoidy** [comment]
> The CPPFLAGS in `taglib_parser` should not influence in playlist behaviour.... Are you sure that was the problem?

Hmm, in that case, let me do some testing and I'll get back to you.

My server is running on Debian Jessie 32 bit.

**Comment by zoidy** [comment]
After some testing, in regards to item 2 from my original issue, it seems like there was something wrong with my build. Cleaning up my local git repo and starting fresh fixed the playlist issue.  I still needed to make the modifications I indicated though in order for it to compile successfully

**Comment by deluan** [comment]
Ah, ok. Well, for the first change I prefer to let the user change their environment with [`NODE_OPTIONS`](https://nodejs.org/api/cli.html#cli_node_options_options). Does that work for you?

For the second change (the c++11), I'll do some tests and let you know

**Comment by deluan** [comment]
Can you confirm that using `#cgo linux CPPFLAGS: -std=c++11` as the directive works? (note the`linux` option)

**Comment by zoidy** [comment]
Thanks I wasn't aware of NODE_OPTIONS, I will use that.  And yes, the directive with the ```linux``` option also worked.

**Comment by deluan** [comment]
Cool! So final version is:
```
#cgo linux CXXFLAGS: -std=c++11
```

Right? Care to make a PR? :)

**Comment by deluan** [comment]
PR merged. Thanks!
