### ISSUE TITLE
Support for Raspberry Pi 1

### ISSUE THREAD

**Issue by charleslaw** [deluan/navidrome#525]
I have an old Raspberry Pi I was going to use to run navidrome.

I ran `cpuinfo` and saw my machine has a ArmV6 processer:

```
model name	: ARMv6-compatible processor rev 7 (v6l)
Hardware	: BCM2835
Revision	: 000e
Model		: Raspberry Pi Model B Rev 2
pi@raspberrypi:~ $ cat /proc/cpuinfo | grep -i arm
model name	: ARMv6-compatible processor rev 7 (v6l)
```

I downloaded this binary file:
https://github.com/deluan/navidrome/releases/download/v0.33.0/navidrome_0.33.0_Linux_armv6.tar.gz

When running navidrome directlly, with or without a config file, there is an error:

```
pi@raspberrypi:/opt/navidrome $ ./navidrome 
Illegal instruction
```

Are the binaries supposed to be compatible with Raspberry Pi 1?

```
pi@raspberrypi:/opt/navidrome $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
pi@raspberrypi:/opt/navidrome $ uname -a
Linux raspberrypi 4.19.118+ #1311 Mon Apr 27 14:16:15 BST 2020 armv6l GNU/Linux
```

**Comment by deluan** [comment]
The ARMv6 build should work with Pi 1, based on this table:
```
ARMv2 – Used in Archimedes machines.
ARMv3 – RiscPC 600, RiscPC 700, A7000, A7000+
ARMv4 – StrongARM RiscPC, A9home, Omega, Virtual RPC, RPCEmu
ARMv5 – IYONIX pc
ARMv6 – Raspberry Pi 1, Raspberry Pi Zero
ARMv7 – BeagleBoard, IGEPv5, iMx6, PandaBoard, Raspberry Pi 2, Titanium, and other Cortex-A7, A8, A9, A15 based machines
ARMv8 – Raspberry Pi 3, Raspberry Pi 4
```
source: https://www.riscosopen.org/wiki/documentation/show/ARMv7%20compatibility%20primer

I don't own a Pi 1, so I don't have means to test it, but I never got a complaint about it. 

Can you try this:
- Try using the ARMv5, just in case ;)
- Try version 0.32.0. This was before introducing TagLib to the project, and changed the way the build is done. It could have potentially introduced this issue

Let me know the results of the tests above.

**Comment by charleslaw** [comment]
Seems like the build changes may be the reason.

The 0.33.0 Armv5 had a `Segmentation Fault`

The armV5 and armV6 binaries looked like they worked, they both started up at least.

**Comment by deluan** [comment]
So, with 0.32.0 it works fine? Hummm... if that's the case, I'll have to dig deeper, probably the TagLib compilation (C++) is generating an invalid ARMv5 instruction... 

Can you join our Discord so I can troubleshoot this with you? I'll be able to work on this later this week

**Comment by deluan** [comment]
Hey @charleslaw, can you try this build?

[navidrome_v0.34.0-SNAPSHOT_Linux_armv6.tar.gz](https://github.com/deluan/navidrome/files/5286921/navidrome_v0.34.0-SNAPSHOT_Linux_armv6.tar.gz)

**Comment by fringillidaes** [comment]
I have a PI Zero which appears to have the same processer as the Raspberry PI 1. With my testing, I was able to confirm the following.

- Version 0.34.0 armv6 ( https://github.com/deluan/navidrome/releases/download/v0.34.0/navidrome_0.34.0_Linux_armv6.tar.gz ) 
Did segmentation fault. 

- Version 0.32.0 armv6 ( https://github.com/deluan/navidrome/releases/download/v0.32.0/navidrome_0.32.0_Linux_armv6.tar.gz ) 
Does work and launch.

- Version 0.34.0 SNAPSHOT armv6 ( https://github.com/deluan/navidrome/files/5286921/navidrome_v0.34.0-SNAPSHOT_Linux_armv6.tar.gz ) 
Works and launches.

**Comment by charleslaw** [comment]
Works for me as well, on the Pi 1.

**Comment by deluan** [comment]
Thanks for testing it @fringillidaes and @charleslaw ! I'm pushing the fix now.
