### ISSUE TITLE
Display download size near download button

### ISSUE THREAD

**Issue by ryansalerno** [deluan/navidrome#534]
If you've got access to filesizes as you ingest tracks, it would be helpful to see an expectation of the summed size near the download button.

If this calculation is non-trivial, I'd also be happy to have it show up late after an async task does the calculating, or it could be summed and stored somewhere during the scan process if that's more straightforward/preferred.

Pressing the button generates a zip file, so actual size isn't important here, and maybe a simple human-size rounding is enough to get close anyway, since most of the music should be compressed such that zipping won't provide a material difference?

----------

Bonus points if you also display the filetype (though this gets messy quickly if the data is mixed for some reason), and double ultra bonus points if the download button is a secret dropdown that also lets you transcode into a zip file (though guessing non-cached transcode sizes is not really worth considering--except you do have duration, so I suppose the math could get approximate enough to still be useful)....

**Comment by deluan** [comment]
When importing I already store in the DB the file sizes. I'll take a look and see what is the simplest way to do it.

**Comment by certuna** [comment]
The download button should probably become a dropdown in the future, with the options "download" (which would offer the zip for download as it does now) and "sync" (which would cache the files in IndexedDB for offline mode).

**Comment by deluan** [comment]
I think Sync and Download are two different actions. And Sync only make sense in the scope of a PWA, not so much for a normal web app

**Comment by certuna** [comment]
Agreed. It would be relatively easy to catch anyway, with some conditional CSS - if the `display-mode` is "standalone" you're in the PWA.

**Comment by deluan** [comment]
Hey @ryansalerno, with #561 merged, you now have the size information in the album details (thanks @jrwren). Let me know what you think. 

Re: the idea of downloading a transcoded version of the tracks, this requires more deep changes, but I think it is a good idea, and I'll keep this issue open to track it

**Comment by deluan** [comment]
I expanded the code on #561 to also cover artists and playlists, and added the size in each download button.

<img width="644" alt="Screen Shot 2020-10-12 at 11 07 26 PM" src="https://user-images.githubusercontent.com/331353/95810770-c35fae00-0cdf-11eb-8126-6b59c49329f3.png">
<img width="354" alt="Screen Shot 2020-10-12 at 11 06 57 PM" src="https://user-images.githubusercontent.com/331353/95810771-c35fae00-0cdf-11eb-95e3-ebf82959fafc.png">

@ryansalerno I'm closing this as the original request is implemented, feel free to give feedback if you think it could be improved. Can you please open a new issue with your idea of downloading transcoded tracks? I think it is not direct related to this issue and deserves an issue for itself
