### ISSUE TITLE
Keep seeing these warn messages in the logs, What does it mean?

### ISSUE THREAD

**Issue by BobWs** [deluan/navidrome#539]
Hi,
I'm keep seeing these messages in the logs
```
WARN[0027] HTTP: GET http://music.mydomain.com/app/static/js/main.95248f27.chunk.js  elapsedTime="38.976µs" httpStatus=404 remoteAddr=192.168.178.232 requestId=navidrome/7pV0EqG8Jy-000004 responseSize=19
stdout
15:09:40
```
What does it mean? If it is a problem how do I fix it?
Thanks

**Comment by deluan** [comment]
This seems to be a request from the UI for a file from an older version... Did you refresh the page after the last upgrade?

**Comment by BobWs** [comment]
> This seems to be a request from the UI for a file from an older version... Did you refresh the page after the last upgrade?

Yes I did. So after using Navidrome yesterday the whole day I haven’t seen the “warn” message anymore in the logs. I guess it is fixed. (Not that there was anything to be fixed 😉)

Thanks for reaching out!
