### ISSUE TITLE
Use trusted-types

### ISSUE THREAD

**Issue by jvoisin** [deluan/navidrome#540]
Since navidrome is dealing with untrusted/semi-trusted data, and runs a lot of javascript, it would be neat to use [trusted-types](  https://web.dev/trusted-types/ ) to catch possible XSS :)

**Comment by jvoisin** [comment]
Trusted-type support was [added]( https://github.com/facebook/react/pull/16157/files/c338e627a0bd1a567295c6047d26713ec67e9ec2 ) in React in September 2019, yet it seems that this code isn't shipped in navidrome. Is the react-admin version lagging behind?

**Comment by deluan** [comment]
I don't know how this trusted-type stuff works. React-Admin uses React 16.9, but I can ensure you we are packaging the latest React version (16.13.1) with Navidrome.

**Comment by jvoisin** [comment]
The draft is still moving, I've wasted enough time on this to not want to re-do it again in a couple of months, closing for now.
