### ISSUE TITLE
FR: Bring Airsonic starrred lists?

### ISSUE THREAD

**Issue by gerroon** [deluan/navidrome#555]
Hi

I am thinking about moving to Navidrome but the main drawback for me is the huge amount of starred stuff I have in my Airsonic lib. Is there any reasonable way to bring them into Navidrome and integrate with the library? I will be sharing the same music files with same paths.

**Comment by deluan** [comment]
Thanks for trying Navidrome. @peguerosdc created a importer, not sure if it imports starred items: https://github.com/peguerosdc/subimporter

**Comment by peguerosdc** [comment]
Hi @gerroon !

It migrates starred songs, but not starred albums/artists. If that works for you, you could give it a go and see how it goes!
