### ISSUE TITLE
UX: Don't disable media controls when buffering

### ISSUE THREAD

**Issue by grahamotte** [deluan/navidrome#568]
I run navidrome on a linode and I'm currently somewhere with less than perfect internet. When I click next to skip a song this spinner comes up:

<img width="432" alt="Screen Shot 2020-10-12 at 10 34 05 PM" src="https://user-images.githubusercontent.com/6063967/95819742-8abdd580-0cdb-11eb-8458-48b63bd097ca.png">
<img width="432" alt="Screen Shot 2020-10-12 at 10 34 42 PM" src="https://user-images.githubusercontent.com/6063967/95819711-77ab0580-0cdb-11eb-81e1-6c3aaaed0369.png">

However if I also want to skip the next song, this can be pretty annoying since I need to wait for it to buffer before I'm allowed to click next again. 

Perhaps the solution is simply to cleanup my music library but it would be great if I was allowed to quick skip to the next song. 

Cheers

**Comment by deluan** [comment]
This is a behaviour of the upstream [React Player](https://github.com/lijinke666/react-music-player) project. Can you please open an issue in that project and link to this?

To alleviate this issue, you could open the play queue (see the image below) and select the song you want to listen directly, without having to skip one by one until you reach it (assuming you know it's name :) )

<img width="376" alt="Screen Shot 2020-10-13 at 10 17 26 AM" src="https://user-images.githubusercontent.com/331353/95872932-64308680-0d3d-11eb-938e-a698b973ea7d.png">

**Comment by grahamotte** [comment]
> Can you please open an issue in that project and link to this?

Will do
