### ISSUE TITLE
Suggestion - makes search section agnostic

### ISSUE THREAD

**Issue by antipiot** [deluan/navidrome#574]
Hello everybody!

First of all, thanks for the great work done - long live Navidrome :-)

I would like to have the ability for the search function to search for the case on every title, album and artist in the server and not only in the menu i'm in.

Actually, when i search something, i have to take care to be in the right menu - folder to search in.
I'd like to be able to search for everything, no matter where i am and have the results displayed in sections:

An example of result would be:
Search Rammstein:

Results:
Artist:
Rammstein

Album:
Rammstein

Track:
Rammstein

Is this possible?

**Comment by deluan** [comment]
Yes @antipiot, long live Navidrome!

We already have an issue opened for this: #468. Please subscribe to that issue as I'm gonna close this one as duplicated.
