### ISSUE TITLE
What should be done next?

### ISSUE THREAD

**Issue by deluan** [deluan/navidrome#575]
# Update: Poll closed, thanks for your participation

![](https://api.gh-polls.com/poll/01EMVCRA58PEAB19YKGYTPZT7Z/Trigger%20re-scans%20from%20the%20UI)
![](https://api.gh-polls.com/poll/01EMVCRA58PEAB19YKGYTPZT7Z/Last.FM%20scrobbling)
![](https://api.gh-polls.com/poll/01EMVCRA58PEAB19YKGYTPZT7Z/Artist%20artwork%20%28using%20Spotify%20API%29%20%28see%20issue%20394%29)
![](https://api.gh-polls.com/poll/01EMVCRA58PEAB19YKGYTPZT7Z/More%20flexible%20transcoding%20options%20%28see%20issue%20351%29)

I've been trying to split my available time for Navidrome into these different large pieces of work, and it is not getting me anywhere. So I'm asking for your help: What should I focus on? Just click on the option you'd like to see sooner than later.

As always, thanks for all your feedback and support, Navidrome would not be what it is today without your participation!

**Comment by msafadieh** [comment]
Hello! Great work on navidrome so far. I think it would be great if you would consider implementing password hashing. I see issue #202 is open for it. It would be easier if you use something like bcrypt which offers `hashpw` and `verifypw` interfaces. I've tried implementing it myself but I've never programmed in Go before so I couldn't figure out how to stop sending the hashed password back to the front-end in user settings and to implement proper db migrations.

Essentially you shouldn't be able to see your password in the UI anymore after it has been hashed and saved. For migrations, I was thinking of creating a new column called `hashed_password` and dropping the old `password` column after hashing all the entries. I'm happy to open a PR with [the work on my fork so far](https://github.com/msafadieh/navidrome/commit/4af222c63db5d20f7a40a195ceda4ff7720018f1) if you think it's a good starting point.

**Comment by deluan** [comment]
Thanks @msafadieh, let's move this conversation to https://github.com/deluan/navidrome/issues/202#issuecomment-711259500

**Comment by deluan** [comment]
Thanks everyone! I'm working on Artist artwork, and already have some initial implementation in the Subsonic API using Spotify (see #576)
