### ISSUE TITLE
Last.fm environment variables not detected (v0.36.0)

### ISSUE THREAD

**Issue by axllent** [deluan/navidrome#589]
I'm not sure if this is related to the docker build or the navidrome v0.36.0 binary, however starting the docker container with the `ND_LASTFM_APIKEY` & `ND_LASTFM_SECRET` environment variables set (as per the [docs](https://www.navidrome.org/docs/usage/configuration-options/#configuration-file)) results in:
```
time="2020-10-22T07:05:32Z" level=info msg="Last.FM integration not available: missing ApiKey/Secret"
```
I can confirm the environment variables are set within docker container itself.

**Comment by deluan** [comment]
Ops, you are right, thanks for letting me know. I just pushed a fix and this will be available in the next release. In the meantime, can you use a config file? If not, you can use the `develop` image, it will be updated in about 20 minutes.

**Comment by axllent** [comment]
Fantastic, you're a star! Thanks @deluan
