### ISSUE TITLE
Maximise play queue

### ISSUE THREAD

**Issue by obbardc** [deluan/navidrome#600]
It'd be really nice to be able to "maximise" the play queue from the bottom right to take up all of the bottom of the screen:
![image](https://user-images.githubusercontent.com/1029590/97167510-d31ad000-177e-11eb-80ef-94adb52ca5fb.png)

**Comment by deluan** [comment]
Thanks for trying Navidrome, and for the suggestion. Unfortunately this is currently not possible, as the player is a external component: https://github.com/lijinke666/react-music-player. Maybe in the future Navidrome will have its own player, but it is not currently planned. 

I'm closing this as it is out of scope for Navidrome. Feel free to open a feature request in the [player's repo](https://github.com/lijinke666/react-music-player/issues)
