### ISSUE TITLE
binary for ASUSTOR NAS

### ISSUE THREAD

**Issue by emosterd** [deluan/navidrome#614]
I'm not sure if this is the correct venue for this request, but per this page:

https://www.navidrome.org/docs/installation/build-from-source/

namely:

"If you can’t find a pre-built binary for your platform, you should open an issue in the project’s GitHub page."

I'd love to see a build for ASUSTOR NAS devices.  I know there's one for QNAP, and I think there might be one for Synology.  If it helps, here's ASUS' developer's guide:

http://download.asustor.com/developer/App_Central_Developer_Guide_3.1.0_20181227.pdf

And I'd be happy to be a guinea pig.  I'm getting fed up with Subsonic, and Emby just doesn't cut it for music, so it'd be great if I could give Navidrome a try.

Thanks for your consideration!

**Comment by deluan** [comment]
Hey, thanks for your interest in Navidrome. "Pre-built binaries" in the context of that page means an executable for a specific combination of OS/Platform. Ex: Linux/ARMv6 or Windows 64 bits. 

Based on the link you provided, all ASUSTOR models are already supported (assuming it runs on Linux):

<img width="701" alt="Screen Shot 2020-11-07 at 12 52 16 PM" src="https://user-images.githubusercontent.com/331353/98448220-7f05d900-20f8-11eb-89c3-2a9ba47f1e44.png">

I think what you mean is a "package" for your system. Currently the project does not maintain any packaging except for Docker. The QNAP package is maintained by someone from the community, and they use one of the binaries available in the [releases page](https://github.com/deluan/navidrome/releases)

The reason to not maintain any package in the project is that there are too packaging systems out there, and I don't have the time/resources/access to all of them, so I rely on the community to help with this. Examples of packages maintained by the community include:
- [Yunohost](https://yunohost.org/#/app_navidrome)
- [Arch Linux](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=navidrome-bin)
- [NixOS](https://search.nixos.org/packages?channel=20.09&show=navidrome&from=0&size=30&sort=relevance&query=navidrome)
- [Cloudron](https://git.cloudron.io/cloudron/navidrome-app)
- [QNAP](https://www.qnapclub.eu/en/qpkg/958)

Sorry for not being able to help you with this. Maybe you can request help from the [ASUSTOR community](https://forum.asustor.com/)?

**Comment by emosterd** [comment]
Thanks for following up!  Just in case anyone else stumbles across this, I was able to simply install one of the pre-built binaries (x86-64) using these instructions:

https://www.navidrome.org/docs/installation/pre-built-binaries/

Running it from the command line works without any modification, at least for my ASUSTOR AS5304T, though I assume it will work similarly on all other Intel-based ASUSTOR systems.

The only difference is that ADM does not use Systemd—at least that I can tell—so the start/stop/restart process is a bit different.  I've yet to figure out exactly what ADM uses, but for now, I just have it start with init.d.
