### ISSUE TITLE
m4b support

### ISSUE THREAD

**Issue by watson387** [deluan/navidrome#62]
Is m4b support planned? I added my audiobook library but Navidrome doesn't seem to recognize m4b files.

**Comment by deluan** [comment]
I added m4b to the supported (scannable) mime-types, and now .m4b files show-up in the collection. 

Keep in mind that there's still no full support for Audiobooks in Navidrome (bookmarks), but this would allow you to at least listen to them

Will release 0.6.1 in a few

**Comment by deluan** [comment]
Bookmarks (using the Subsonic API) will be supported in the next release, 0.28.0
