### ISSUE TITLE
multiple discs, not starting with track # 1

### ISSUE THREAD

**Issue by certuna** [deluan/navidrome#620]
When you have an album with:
disc 1 song 1
disc 1 song 2
disc 1 song 3
(disc 2 song 1 missing)
disc 2 song 2
disc 2 song 3

The navidrome UI will not split the album into two discs anymore, but will show them all under disc 1:
**disc 1:**
song 1
song 2
song 3
song 2
song 3

Example (in this case I'm missing tracks 1-10 from the second disc):

![Screenshot 2020-11-10 at 13 53 46](https://user-images.githubusercontent.com/62144283/98676964-9c3ae180-235c-11eb-9dad-61037bf0af28.png)

**Comment by deluan** [comment]
Ah yes, It detects the "new disc" based on track 1. Will fix this, thanks for the report
