### ISSUE TITLE
Navidrome not grouping songs of the same album

### ISSUE THREAD

**Issue by a20eac1d** [deluan/navidrome#622]
After scanning my music library Navidrome has found multiple songs of the same album but decided to show them each individually depending on the artists of that specific song.

Example:

https://i.imgur.com/kPcW3I7.png

All of these should be a part of the one album "8 Mile", but they are split up by artists as you can see below each album art.

This also happens on the main page "Albums -> All" without searching for the album specifically.

**Comment by certuna** [comment]
Do they have "Part Of Compilation" set to true?

**Comment by SteveDinn** [comment]
By any chance, are these files from a Google Music backup? I noticed that it grouped my compilation songs by artist by default. I had lots of single-song albums under each artist instead of a compilation with many songs.

If this is the case, I recommend going through your library with a tool like [MP3Tag](https://www.mp3tag.de/), and making sure all of your files are in the correct and optimal folder structure. I typically use "Artist / Album / Track Number - Track Name.ext"

**Comment by HappyBasher** [comment]
Another reason could be not all songs of the album have the same album artist tagged.

**Comment by deluan** [comment]
Time to add a new F.A.Q. ... :)

**Comment by deluan** [comment]
Add to F.A.Q (thanks @certuna): https://www.navidrome.org/docs/faq/#i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist

**Comment by vestingz** [comment]
I understand this is a fundamental design decision to not just use the common album tag to group songs together but rather rely on an explicit tag to be set in the files metadata, but it is quite unfortunate in those cases where altering the tags is not an option. Would you consider a grouping feature which only relies on a common album tag?

**Comment by deluan** [comment]
@vestingz, and how to handle albums from different artists that you **don't** want to group together? Examples:
<img width="1526" alt="Screen Shot 2021-01-31 at 10 53 36 PM" src="https://user-images.githubusercontent.com/331353/106413095-3ddf4580-6417-11eb-9dc8-16e40f0d94aa.png">
or
<img width="1512" alt="Screen Shot 2021-01-31 at 11 00 20 PM" src="https://user-images.githubusercontent.com/331353/106413479-25bbf600-6418-11eb-84c4-c12bd01c66f2.png">
or
<img width="516" alt="Screen Shot 2021-01-31 at 11 02 56 PM" src="https://user-images.githubusercontent.com/331353/106413600-7cc1cb00-6418-11eb-80d9-8a6067195ac9.png">

Implementing what you are suggesting would require implementing 'workarounds" to handle situations like these above. This implementation would be messy at best, and I don't think it makes sense to implement it when we have a perfect solution, a standard and widely accepted way to handle this: the "Part of Compilation" tag. 

May I ask why it is not an option for you to edit your tags?

**Comment by vestingz** [comment]
@deluan, you are absolutely correct, I did not consider this.

There are unfortunately still major use cases for music files, which require them to conform to a unique checksum or a hash. Editing their metadata would contradict this use case, so you either would have to retain an untouched duplicate or give up these use cases.
I could imagine that storing this "Part of Compilation" flag in an external database would be one possible solution?

**Comment by deluan** [comment]
Not an external database, but I'm contemplating supporting CUE files (https://github.com/deluan/navidrome/issues/497#issuecomment-706724225), and it would probably solve your issue: If a .CUE file is found in the folder, it could override the tags from the files, and of course all files would be considered part of the same album, even if they are from different artists. 

If you have any other ideas about this, please reply to that GH issue, as this one is closed and supporting external metadata is outside the scope of this issue.
