### ISSUE TITLE
api returns wrong song path

### ISSUE THREAD

**Issue by HappyBasher** [deluan/navidrome#625]
getSong returns for example
`<song album="Greendale" albumid="53da1e3857c540d7fcd55f1c269e7c5d" artist="Neil Young &amp; Crazy Horse" artistid="f1c6b7c898c0e98c94c55635295bd761" bitrate="930" contenttype="audio/flac" coverart="8d5f083ec6f32567d917368cd81e639b" created="2019-04-12T16:20:49Z" discnumber="1" duration="777" genre="Rock" id="8d5f083ec6f32567d917368cd81e639b" isdir="false" isvideo="false" parent="53da1e3857c540d7fcd55f1c269e7c5d" path="Neil Young &amp; Crazy Horse/Greendale/Grandpa's Interview.flac" playcount="2" size="90644859" starred="2020-11-06T14:04:23Z" suffix="flac" title="Grandpa's Interview" track="7" type="music" year="2003"></song>`
where the correct path is
`Neil Young/Greendale/07. Neil Young &amp; Crazy Horse - Grandpa's Interview.flac`
Seems the api builds his own version of the song path with the scheme Artist/Album/Title.suffix which has nothing in common with the real path.

**Comment by deluan** [comment]
Yes, this is by design. I implemented that way so when toggling offline mode in DSub, it shows a more sane structure of Artists/Albums, instead of having to navigate through various folders. Ex: If the original path is `/mnt/data/music/Crazy Horse/Greendale`, in offline mode DSub would show only one entry in the Library: `mnt`. Touching it would show another sole entry: `data`, and so on. You got the picture right?

Is there a reason you need the real absolute path?

**Comment by HappyBasher** [comment]
Yep, I do some python scripting to create smart playlists based on my starred items, what works excellently with airsonic. So I assume this will never be fixed as the DSub client depends on it.

**Comment by deluan** [comment]
I think I'll add an option in the Players configuration page, to enable real paths through the API. This would allow to select which players should receive the "fake" path (default) or the real one

**Comment by HappyBasher** [comment]
Super, that would be nice. :+1:

**Comment by deluan** [comment]
Done. New option on the player configuration:
<img width="617" alt="Screen Shot 2020-11-28 at 10 27 12 AM" src="https://user-images.githubusercontent.com/331353/100519196-5eafc400-3164-11eb-9956-8a5d9a43c1d7.png">

**Comment by HappyBasher** [comment]
Works as expected, thanx. :-)

**Comment by HappyBasher** [comment]
Seems with 0.44.1 the report real path feature is broken. Old behaviour takes place again.
