### ISSUE TITLE
Years not showing up for many albums

### ISSUE THREAD

**Issue by duckpuppy** [deluan/navidrome#63]
It looks like parsing the year for some of my music is failing. I think I've tracked it down to the use of TDRC vs TYER tags. I use beets to manage my music collection, and pull metadata from MusicBrainz. beets (and other MusicBrainz based taggers, I think) will use the TDRC tag for release date rather than the TYER tag (which is just the year).  ffmpeg then reports the `date` metadata output using the TDRC field, which can be a date string rather than a simple integer year.

It looks like the format in TDRC can be: `yyyy`, `yyyy-mm`, or `yyyy-mm-dd`. Lots of taggers that use MusicBrainz will use TDRC rather than the separate TDAT, TIME, TRDA, and TYER. The fact that TDRC also incorporates the TIME tag means it might be possible to find one with a time stamp added as well, but I've never run across one yet.

**Comment by duckpuppy** [comment]
Sample ffmpeg output from one of the files

```
[I] ➜ ffmpeg -i Signals/01\ Subdivisions.mp3 -f ffmetadata
ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enab
le-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-
libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora
--enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --
enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Trailing options were found on the commandline.
[mp3 @ 0x5635441dc780] Skipping 1044 bytes of junk at 62852.
[mp3 @ 0x5635441dc780] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'Signals/01 Subdivisions.mp3':
  Metadata:
    title           : Subdivisions
    artist          : Rush
    track           : 1/8
    album           : Signals
    disc            : 1/1
    date            : 1982-09
    genre           : Progressive Rock;Rock;Classic Rock
    TBPM            : 0
    compilation     : 0
    album_artist    : Rush
    artist-sort     : Rush
    TMED            : Vinyl
    TDOR            : 1982-09
    TIPL            : arranger
    TEXT            : Neil Peart
    Script          : Latn
    publisher       : Mercury Records
    Artist Credit   : Rush
    ALBUMARTISTSORT : Rush
    composer        : Geddy Lee, Alex Lifeson
    Album Artist Credit: Rush
    CATALOGNUMBER   : SRM-1-4063
    TSOC            : Lee, Geddy, Lifeson, Alex
    ....
```

**Comment by deluan** [comment]
What is your suggestion here? Just get the year part of the `date` field for now?  That would be a quick fix.

Support for original date would be cool. Unfortunately it would only be usable from Navidrome's WebUI, not from Subsonic API clients...

**Comment by deluan** [comment]
I'm adding support for the following formats:
```
	"2006",
	"2006.01",
	"2006.01.02",
	"2006-01",
	"2006-01-02",
	time.RFC3339,
```

And will log an error if it cannot parse the date field. I think that is enough for now. Looking forward for the TDOR enhancement request so we can discuss how can this be implemented.

**Comment by deluan** [comment]
Hey, I replaced the parsing with a regex. It will match anything that starts with 4 digits, from 1000 to 2999. 

I'm closing this for now, but feel free to re-open if you feel it does not cover all cases you've seen.

**Comment by duckpuppy** [comment]
I wiped my database to force a rescan and everything's looking great for the years now. I'll open the enhancement request soon.

Hopefully I can contribute some code. I'm pretty proficient in go, less so in node/javascript.
