### ISSUE TITLE
Comments cut off if longer than wrapper

### ISSUE THREAD

**Issue by geekedtv** [deluan/navidrome#637]
Comments cut off if they are longer than the wrapper. This could be an issue for audiobooks with large descriptions.

See this image.
https://prnt.sc/vktgii

**Comment by deluan** [comment]
Thanks for the report.

Should we do the same as other platforms and strip line breaks from the comment?

**Comment by metalheim** [comment]
I can confirm the problem (also had this with an audiobook with a very long comment).

Its actually enough to remove the CSS property "white-space: nowrap;" from the wrapper" and the text will flow nicely.

Default (with white-space: nowrap)

![image](https://user-images.githubusercontent.com/44159957/99907001-8f15df00-2cda-11eb-8c65-bd5706f8e989.png)

Exptected behaviour (removed white-space: nowrap)

![image](https://user-images.githubusercontent.com/44159957/99907007-9dfc9180-2cda-11eb-8726-1b8ad86f98f1.png)

**Comment by sergio-ns** [comment]
Hello,
I just upgraded to v0.39.0 on docker and #637 seems to still be there.
Tried both on Firefox 85 and Edge.
Thanks!
(PS loving increasingly Navidrome by the day)

![2021-02-13 11_53_19-Navidrome](https://user-images.githubusercontent.com/46521034/107848246-22e6db00-6df2-11eb-99fe-a7e693e8f3f9.png)

![2021-02-13 11_52_17-Navidrome](https://user-images.githubusercontent.com/46521034/107848227-ffbc2b80-6df1-11eb-9f39-82e04f8e024c.png)

**Comment by deluan** [comment]
Thanks @sergio-ns . Can you send me one song from this album, that contain this comment?

**Comment by sergio-ns** [comment]
Sent to your email address

**Comment by deluan** [comment]
@sergio-ns Navidrome actually enables expanding the comments in this case, you just have to click on the comment. The issue is that there's no visual cues for that:
![Screen Recording 2021-02-15 at 1 35 53 PM](https://user-images.githubusercontent.com/331353/107983053-28c7f200-6f93-11eb-9833-eb1fe1164e22.gif)

I'll take a look at that. If you have any more comments, please open a new GH issue, as this one is closed.

**Comment by sergio-ns** [comment]
Thanks for clarifying
