### ISSUE TITLE
Server Uptime: OFFLINE

### ISSUE THREAD

**Issue by jwalton** [deluan/navidrome#640]
I just set up a brand new Navidrome instance with Docker.  It found all my music (well, it found a bunch of music - I haven't gone digging to see if it found all), and I can play music, and everything seems to be working... except, in the upper right corner there's a yellow triangle with a ! in the middle, and a "loading" circle spinning around it.  If I click on it, it tells me the server is offline:

![image](https://user-images.githubusercontent.com/1771003/99469145-1399e380-2910-11eb-8e0f-292a2f483831.png)

Clearly, this is lies - I'm listening to music off the server right now.  There's nothing going on in the logs that indicates anything out of the ordinary.  What'd I do wrong?  :P

**Comment by AvdWerfhorst** [comment]
Same here. Only my instance is not in a docker.

**Comment by deluan** [comment]
This happens when the UI cannot open an EventStream with the server. What browsers are you using? Can you see any error messages in the browser's console?

**Comment by AvdWerfhorst** [comment]
I am starting to wonder if I am experiencing the same issue as @jwalton . As I have been digging around a bit more, I think, the cashed parts are in this case making it seem like the rest is up and running. I am primary using Firefox 82.0.3 on Ubuntu 20.10. When the application mentions it is offline, I can still load some album views. But when I try to open a session in Chromium, it appears I cannot reach even the logon page. So in my case, without digging on the server side, it kind of feels like at one moment the webservice part crashes/stops responding. After a restart of Navidrome itself, which I have running on a Raspberry Pi, everything connects again.

I only noticed it after having Navidrome open in a browser window for a while. So I will check if I can reach the site, after a few hours, after not having it opened in a browser.

**Comment by jwalton** [comment]
On Chrome, I get no errors in the console... But on Firefox I *do* see an error in the console.  (It was burried under a bunch of warnings - I'm running another service on this same server on another port over https, and I was getting a flood of warnings from Firefox that one of the cookies was going to be treated as not-same-site because the scheme didn't match.  -_-  I created a second hostname to get around this for now...)

Anyways, on Firefox:

```
Firefox can’t establish a connection to the server at http://music:4533/app/api/events?jwt=[redacted]
```

I see that exactly once, and then checking in the network tab, we see a steady stream of "0 byte" requests to /app/api/events:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/1771003/99540903-22b77a80-297e-11eb-9ef7-e233cbf7032b.png">

**Comment by jwalton** [comment]
```sh
jason@orac:~$ curl -v http://music:4533/app/api/events?jwt=...
> GET /app/api/events?jwt=... HTTP/1.1
> Host: music:4533
> User-Agent: curl/7.54.0
> Accept: */*
>
```

And then nothing... It seems to just hang forever.

**Comment by jwalton** [comment]
Hmmm...  I restarted the navidrome server, and now it's connecting to that endpoint.

**Comment by deluan** [comment]
When you connect to this endpoint, it should return the server start time, and then keep the connection, receiving at least one message every 15 seconds:
```
data: {"data":{"startTime":"2020-11-18T11:02:09.567039253Z"},"name":"serverStart"}
data: {"data":{"ts":1605709389},"name":"keepAlive"}
data: {"data":{"ts":1605709404},"name":"keepAlive"}
...
```

**Comment by deluan** [comment]
When you connect to this endpoint, it should return the server start time, and then keep the connection, receiving at least one message every 15 seconds:
```
data: {"data":{"startTime":"2020-11-18T11:02:09.567039253Z"},"name":"serverStart"}
data: {"data":{"ts":1605709389},"name":"keepAlive"}
data: {"data":{"ts":1605709404},"name":"keepAlive"}
...
```

In the browser you should have something like this:
<img width="730" alt="Screen Shot 2020-11-18 at 9 27 30 AM" src="https://user-images.githubusercontent.com/331353/99542680-54c9dc00-2980-11eb-8ce8-7118e3782449.png">

Now that you restarted, can you see these messages with curl or in the browser?

**Comment by jwalton** [comment]
Yup.  (And TIL about "Content-Type: text/event-stream".  I was expecting a 101 switching protocols to a websocket!)

**Comment by deluan** [comment]
Yeah, Server-Sent Events and Event Streams are simpler and more lightweight than websockets for this use case. 

Anyway, it seems that there was a hiccup somewhere in the installation... Are you still having the issue? Let me know so we can close this

**Comment by jwalton** [comment]
I'll close this.  If I get a chance later, I'll try setting up a new instance and see if I can get a reproducible test case.  It's perhaps worth noting that when I first set this up, it sat there for a couple of days unable to find any music, because for some reason when I copied all this music to my Synology, the Synology SMB server set the permissions on all the folders to 000.  -_-  I fixed that, and it found all the music, but just in case that detail sparks some insight on your end I thought I'd mention it - it's the only thing "unusual" I can think of about my install.

Thanks for all the hard work on this project, BTW!

**Comment by zoidy** [comment]
I have the same issue. For me, it does not work when I access my server locally over HTTP on local LAN. When I access it via my HTTPS-enabled internet-facing domain, it works

**Comment by xsteadfastx** [comment]
same problem.... https... navidrome in docker over traefik reverse proxy.

**Comment by xsteadfastx** [comment]
looks like something is blocked or something.

![image](https://user-images.githubusercontent.com/168397/100613704-4337eb00-3315-11eb-9434-7349e6c796d6.png)

**Comment by buergi** [comment]
I'm having the same problem, and I assume it is related to buffering of the reverse proxy. I'm using apache2 with mod_proxy_http.
While direct access via curl works perfectly and immediately outputs, for example,

    id: 0
    event: serverStart
    data: {"startTime":"2022-04-23T15:50:33.988105765+02:00","version":"0.47.5 (86fe1e3b)"

however, when curl-ing through the reverse proxy the connection is pending for several seconds (~30s) until at once a whole bunch of output is printed, always exactly 45056 byte. Unfortunately I didn't find a way to disable proxy buffering. `flushpackets=on` did not help.
