### ISSUE TITLE
Use a logarithmic volume slider

### ISSUE THREAD

**Issue by wanieru** [deluan/navidrome#668]
Correct me if I'm wrong, but the volume slider is currently implemented linearly?
Volume controls are much better when implemented as a logarithmic volume slider. It matches the way human hearing works. It makes turning the volume down from 100% to 50% actually impactful, instead of barely making a difference.
For me, this is currently my preferred volume: [https://i.imgur.com/e4B0lu2.png](https://i.imgur.com/e4B0lu2.png). 
See this thread for some detail: [https://ux.stackexchange.com/a/116300](https://ux.stackexchange.com/a/116300)

**Comment by certuna** [comment]
This is probably better posted as an issue for the upstream react player: https://github.com/lijinke666/react-music-player

**Comment by andrewzah** [comment]
Made an issue: https://github.com/lijinke666/react-music-player/issues/227

**Comment by andrewzah** [comment]
The issue was just closed- we'll need to implement this feature manually.

**Comment by danshilm** [comment]
https://github.com/lijinke666/react-music-player/pull/266 was merged.
