### ISSUE TITLE
Last.fm bio Artist crash navidrome

### ISSUE THREAD

**Issue by corinzio** [deluan/navidrome#669]
Hello i use navidrome on a ubuntu 20.04 machine,
I downloaded the binary from the site.

When using the musicstash App on android if I try to show an artist Navidrome crash with this log:

> API: New request /rest/getArtistInfo2         client=musicstash requestId=Machine/w5k3wqh7Pz-000079 username=myuser version=1.15.0
> Found player by name                          client=musicstash id=278ce1fe-0ba9-41d6-a006-c5f43adf8b36 username=myuser
> ArtistInfo not cached                         id=ee2632475ad35346c79c5a6a9161371b updatedAt="0001-01-01 00:00:00 +0000 UTC"
> Calling Last.FM ArtistGetInfo                 artist=Adele requestId=Machine/w5k3wqh7Pz-000079
> Calling Spotify SearchArtist                  artist=Adele requestId=Machine/w5k3wqh7Pz-000079
> Calling Last.FM ArtistGetSimilar              artist=Adele requestId=Machine/w5k3wqh7Pz-000079
> fatal error: unexpected signal during runtime execution

**Comment by corinzio** [comment]
Duplicate of #588
Solved by rebuilding navidrome from source code as described there.

**Comment by deluan** [comment]
Thanks for the report, this error is really weird. It looks like the OS sent a SIGNAL to Navidrome when it tries to access external resources, something like a firewall. Anyway, I'm closing this as this is a duplicate. If you find anything relevant, please post in #588
