### ISSUE TITLE
Navidrome as app inside Nextcloud?

### ISSUE THREAD

**Issue by h-2** [deluan/navidrome#683]
This looks really great! Have you considered making a version that can be used from inside Nextcloud? Nextcloud currently has a music app that offers subsonic and ampache streaming, but the interface is rather slow and a lot less intuitive that navidrome!

Thank you in any case!

**Comment by Wumbargh** [comment]
You can use Navidrome with the "External Site" App in you Nextcloud!?

**Comment by deluan** [comment]
Thanks for the compliment, really appreciate.

I never used Nextcloud, so I'm not sure what that entails. Packaging Navidrome for Nextcloud? Creating a small app? Don't really know. Anyway, packaging for other platforms is generally out of scope for Navidrome (see https://github.com/deluan/navidrome/issues/614#issuecomment-723477350)

**Comment by h-2** [comment]
Thanks for the replies! This is not about "packaging", but more about creating an app for nextcloud. This means using nextcloud's user management and accessing the files through nextcloud (also shares received from other users etc).

I assume that it would not be trivial, so please don't see it as a request or anything. But maybe something to keep in mind for the future. Over here in Europe, Nextcloud is super huge with hundreds of thousands of users in public and private instances, so I it would definitely get you a lot of exposure :)
