### ISSUE TITLE
Error trying to register new player

### ISSUE THREAD

**Issue by SteveDinn** [deluan/navidrome#685]
Looking in my logs for an unrelated reason, and I see this snippet each time I stop and start my web-client.

```
time="2020-12-08T17:05:57Z" level=info msg="Registering new player" client=NavidromeUI id=6c06a144-62d6-4fac-8753-8641962eba77 username=Steve
time="2020-12-08T17:05:57Z" level=error msg="SQL: `INSERT INTO player (client,id,ip_address,last_seen,max_bit_rate,name,report_real_path,transcoding_id,type,user_name) VALUES (?,?,?,?,?,?,?,?,?,?)`" args="['NavidromeUI','6c06a144-62d6-4fac-8753-8641962eba77','','2020-12-08T17:05:57.240073769Z',0,'NavidromeUI (Steve)',false,'','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36','Steve']" elapsedTime="253.536µs" error="FOREIGN KEY constraint failed" requestId=navidrome/8jYJezCGzH-000234 rowsAffected=0
time="2020-12-08T17:05:57Z" level=error msg="Could not register player" client=NavidromeUI username=Steve
```

I have more than one machine running this web-client logged on as 'Steve', and there is already a "NavidromeUI (Steve)" player in the list. There are several parameters in that SQL statement that are null that perhaps shouldn't be.

**Comment by SteveDinn** [comment]
Side thought: Is there any way to use MySQL or MariaDB as the backend for Navidrome?

**Comment by deluan** [comment]
This is an issue with the way players are identified and how the whole transcoding engine is programmed. This msgs are harmless, but if you want different transcodings settings for different instances of the Web UI, that's not currently possible. This will be fixed as part of the transcoding refactoring (#351). 

Will close this issue, and please subscribe to #351 to get progress update about the refactoring.

> Side thought: Is there any way to use MySQL or MariaDB as the backend for Navidrome?

Currently it is not possible, but I have plans to make the SQL code more generic and adding support to Postgres and possibly MySQL as well.

**Comment by SteveDinn** [comment]
I have been blissfully ignorant of those errors until now and they have done me no harm. I don't transcode to the web client anyway.
