### ISSUE TITLE
Can't change transcoding from UI even after enabling transcoding config

### ISSUE THREAD

**Issue by berkentekin** [deluan/navidrome#694]
As the title says, even after setting ND_ENABLETRANSCODINGCONFIG=true at navidrome.toml, the server still doesn't allow me to change the transcodings.

Here are permissions for the file:
`-rw-r--r-- 1 root      root           64 Dec 17 01:23 navidrome.toml`

and here are the contents:
```
MusicFolder = "/home/pi/Music"
ND_ENABLETRANSCODINGCONFIG=true
```
I have tried everything from changing the owner to navidrome to making it executable, but to no avail.

**Comment by orlea** [comment]
`ND_ENABLETRANSCODINGCONFIG` is an environment variable.
If you want to use navidrome.toml to enable that setting, use
`EnableTranscodingConfig=true`, I think.

**Comment by berkentekin** [comment]
> `ND_ENABLETRANSCODINGCONFIG` is an environment variable.
> 
> If you want to use navidrome.toml to enable that setting, use
> 
> `EnableTranscodingConfig=true`, I think.

This instantly worked, thanks.
