### ISSUE TITLE
"unable to open database file: no such file or directory" error when not runing as root

### ISSUE THREAD

**Issue by ben16w** [deluan/navidrome#695]
When running Navidrome with Docker:
```
docker run -d \
   --name navidrome \
   --restart=unless-stopped \
   --user 1000:1000 \
   -v /home/username/navidrome/music:/music \
   -v /home/username/navidrome/data:/data \
   -p 4533:4533 \ 
   -e ND_LOGLEVEL=info \
   deluan/navidrome:latest
```

I'm getting these errors:
```
time="2020-12-16T22:30:01Z" level=error msg="Error disabling foreign_keys" error="unable to open database file: no such file or directory"
time="2020-12-16T22:30:01Z" level=error msg="Failed to apply new migrations" error="unable to open database file: no such file or directory"
```

But I don't get any errors and everything works fine if I ommit the `--user 1000:1000`. It's running on a RPi 4.

**Comment by deluan** [comment]
A couple of  things to check:
- Do you have a user in your host with id = 1000 and groupid = 1000?
- Does this user have write permission on the `/home/username/navidrome/data` folder?

**Comment by ben16w** [comment]
Thanks @deluan. So I checked:

- `id` gives `uid=1000(username) gid=1000(username) groups=1000(username),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),115(netdev),118(lxd)`
- `touch /home/username/navidrome/data/test` gives no errors and the file is created.

Anything else I can check?

**Comment by deluan** [comment]
Looks like permissions are correct. Not sure what is going on here.... the few times people complained about this was a permissions issue. I can assure you this works, I use it like this in my environment and I know other users are also configuring their docker containers this way. The only difference I see is that in my case I use `docker-compose`, instead of the `docker` command, but it should behave the same.

**Comment by ben16w** [comment]
I've tried using `docker-compose` and a bunch of other things, and it's still not playing ball. I'm using 64bit Ubuntu, rather than Raspbian, so maybe it's something to do with that. For the moment I'll just run as root. Thanks for your help.

**Comment by teuteuguy** [comment]
Same problem trying to run on raspberry pi.
pi user is 1000:1000.
Any fix ?

**Comment by letompouce** [comment]
Using `docker-compose` with this configuration:
```
    user: 1000:1000
    volumes:
    - /srv/volumes/navidrome/data:/data:rw
```

The problem here is, when bringin the stack up, the `volumes` are created by the docker daemon, *before* the container is started using `id=1000`. As a result, the `data` volume is owned by `root`:

```
$ namei -l /srv/volumes/navidrome/data/                                                                                                                                                                                         
f: /srv/volumes/navidrome/data/
drwxr-xr-x root root /
drwxr-xr-x root root srv
drwxrwxr-x root adm  volumes
drwxr-xr-x root root navidrome
drwxr-xr-x root root data
```
The fix is obvious then:
```
$ sudo chown 1000: -R /srv/volumes/navidrome/
```
HTH.

**Comment by lhuang001** [comment]
I get the same error when using docker-compose.  please update installation tutorials.

**Comment by kaka2022** [comment]
Modify permissions to solve this problem. Please check whether you have folder read and write permissions.
