### ISSUE TITLE
Feature - docker custom mount path

### ISSUE THREAD

**Issue by abescalamis** [deluan/navidrome#697]
I just installed Navidrome in my synology nas and I love it,

Can you please make it possible for the docker image to use a custom mount path, currently is case sensitive and you can only use /music, /data.

**Comment by deluan** [comment]
I don't see why you would change these folders, as they can be mapped to anything you want in the host, when setting up the container volumes, for example (using docker-compose):
```
    volumes:
      - /Users/JohnDoe/Music:/music
      - /Users/JohnDoe/Navidrome:/data
```

As you can see, you don't need to change these folders to map to any folder in the host. But if you really want to change the folders used by Navidrome inside the container, just set the [config options](https://www.navidrome.org/docs/usage/configuration-options). Ex:

```
    environment:
      - ND_MUSICFOLDER=/Navidrome/Music
      - ND_DATAFOLDER=/Navidrome/Data
```

I'm closing this as the "feature" you are requesting is already available, but feel free to reopen in case you think I'm missing something.
