### ISSUE TITLE
Navidrom Restarts When Attempting to Pull Artist Biography

### ISSUE THREAD

**Issue by Beswald** [deluan/navidrome#700]
Log attached. Using DSub on android, when an artist is selected I get errors. Navidrome is crashing. If I comment out last.fm and spotify keys Navidrome does not crash. All other functionality is fine, streaming music works great.

Version: 0.39.0, arm64

[navidrome.log](https://github.com/deluan/navidrome/files/5736235/navidrome.log)

**Comment by deluan** [comment]
Can you try with these two binaries, please?

[1navidrome_v0.39.0-SNAPSHOT_Linux_arm64.tar.gz](https://github.com/deluan/navidrome/files/5736474/1navidrome_v0.39.0-SNAPSHOT_Linux_arm64.tar.gz)
[2navidrome_v0.39.0-SNAPSHOT_Linux_arm64.tar.gz](https://github.com/deluan/navidrome/files/5736473/2navidrome_v0.39.0-SNAPSHOT_Linux_arm64.tar.gz)

**Comment by Beswald** [comment]
Had the same issue with #1 (1navidrome....tar.gz)

However, all is working with #2 (2navidrome...tar.gz), artist biographies load up quick and the log is very clean now.

Thanks for looking into this. Is it a change on your end or did you identify something with my config?

**Comment by deluan** [comment]
Thanks for helping test this.

It is not a config issue. It seems like this is an issue with the CGO network library used by go: https://github.com/google/cadvisor/issues/1481#issuecomment-259101833

In version 2 I turned on the Go network library (`-tags netgo`) as suggested in the attached thread. Please do more testing (specially streaming and using the UI) so we can be sure we can apply this change to the next version.

**Comment by Beswald** [comment]
Thanks, will do. I'll let you know if anything else comes up.

**Comment by Beswald** [comment]
Streaming seems to be fine, both web ui and through DSub. UI seems responsive, haven't had any issues. Looking at the back end, resource usage is low and the logs are clean.

Anything in particular you want me to look at. I should mention that I don't do any transcoding, the hardware is a little light and usually if I won't have a wifi connection I'll cache music.

**Comment by deluan** [comment]
I think this is enough. I'll merge this into master, thanks for the help!
