### ISSUE TITLE
Error parsing year from ffmpeg date field, "date=12"

### ISSUE THREAD

**Issue by tedder** [deluan/navidrome#702]
This came up in #63, I noticed I'm seeing it on a new album:

```
time="2020-12-25T03:50:43Z" level=warning msg="Error parsing year from ffmpeg date field" date=12 file="/music/Taylor Swift/evermore/10 ivy.mp3"
```

And when running `ffprobe`, here's what the metadata looks like:
```
Input #0, mp3, from '/music/Taylor Swift/evermore/03 gold rush.mp3':
  Metadata:
    album           : evermore
    artist          : Taylor Swift
    genre           : Pop-Folk
    date            : 12
    comment         : 0
    title           : gold rush
    track           : 3/15
    encoded_by      : LAME 3.98 (Max 0.9.1)
    creation_time   : 2020-12-11T04:26:23
    TDTG            : 2020-12-11T04:26:23
  Duration: 00:03:05.44, start: 0.025056, bitrate: 342 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : LAME3.98 
    Stream #0:1: Video: png, rgba(pc), 500x500 [SAR 11811:11811 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Other
```

Yes, the year is "12". This album is straight from `store.taylorswift.com`, so apparently UMG is encoding it wrong?

It may be a "wontfix", but I wanted to at least document it.

**Comment by deluan** [comment]
> Yes, the year is "12". This album is straight from `store.taylorswift.com`, so apparently UMG is encoding it wrong?

You'd think they can do better... Anyway, not sure what can be done on Navidrome's side. This is clearly an invalid year value, so I think displaying the warning message is the right thing to do here
