### ISSUE TITLE
DSub requests giving 'Wrong username'

### ISSUE THREAD

**Issue by tedder** [deluan/navidrome#704]
Hi, I'm trying to troubleshoot some intermittent behavior in dsub. Playing items seems to work, but telling dsub to cache or permacache them gives errors.

When tailing the navidrome logs, here's a successful set of lines:
```
time="2020-12-27T20:48:33Z" level=debug msg="API: New request /rest/savePlayQueue.view" client=DSub requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000064 username=ted version=1.2.0
time="2020-12-27T20:48:33Z" level=trace msg="SQL: `SELECT * FROM user WHERE user_name LIKE ?`" args="['ted']" elapsedTime="254.458µs" requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000064 rowsAffected=1
time="2020-12-27T20:48:33Z" level=trace msg="SQL: `SELECT * FROM player WHERE (client = ? AND user_name = ?)`" args="['DSub','ted']" elapsedTime="188.991µs" requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000064 rowsAffected=1
time="2020-12-27T20:48:33Z" level=debug msg="Found player by name" client=DSub id=06cc916d-9db9-4228-9d1a-cf0bc3dc99f7 username=ted
time="2020-12-27T20:48:33Z" level=trace msg="SQL: `UPDATE player SET client = ?, id = ?, ip_address = ?, last_seen = ?, max_bit_rate = ?, name = ?, report_real_path = ?, transcoding_id = ?, type = ?, user_name = ? WHERE id = ?`" args="['DSub','06cc916d-9db9-4228-9d1a-cf0bc3dc99f7','192.168.3.29','2020-12-27T20:48:33.959442548Z',0,'DSub (ted)',false,'','DSub','ted','06cc916d-9db9-4228-9d1a-cf0bc3dc99f7']" elapsedTime="191.45µs" requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000064 rowsAffected=1
time="2020-12-27T20:48:33Z" level=trace msg="SQL: `DELETE FROM playqueue WHERE user_id = ?`" args="['309b977c-6c67-4d93-b346-fde06686c2f4']" elapsedTime="155.199µs" requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000064 rowsAffected=1

```

Almost immediately afterwards there are errors from dsub:
```
time="2020-12-27T20:48:34Z" level=debug msg="API: New request /rest/savePlayQueue.view" client=DSub requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000065 username=ted version=1.2.0
time="2020-12-27T20:48:34Z" level=debug msg="API: New request /rest/savePlayQueue.view" client=DSub requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000066 username=ted version=1.2.0
time="2020-12-27T20:48:34Z" level=trace msg="SQL: `SELECT * FROM user WHERE user_name LIKE ?`" args="['ted']" elapsedTime="338.357µs" requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000065 rowsAffected=1
time="2020-12-27T20:48:34Z" level=warning msg="Invalid login" error="invalid authentication" requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000065 username=ted
time="2020-12-27T20:48:34Z" level=trace msg="SQL: `SELECT * FROM user WHERE user_name LIKE ?`" args="['ted']" elapsedTime="313.422µs" requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000066 rowsAffected=1
time="2020-12-27T20:48:34Z" level=warning msg="Invalid login" error="invalid authentication" requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000066 username=ted
time="2020-12-27T20:48:34Z" level=warning msg="API: Failed response" error=40 message="Wrong username or password" requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000065
time="2020-12-27T20:48:34Z" level=warning msg="API: Failed response" error=40 message="Wrong username or password" requestId=navidrome-endpoint-6dfc696475-q4lfx/uJZFU6DSPq-000066

```

I __think__ that dsub is threading requests, and perhaps trying to auth many parallel requests at the same time. I haven't dug enough to see if navidrome or subsonic use a tokenized auth or if it is requesting auth every time and failing for some reason. Please let me know if I can help you diagnose.

**Comment by deluan** [comment]
Sorry for the delay in replying to this. "Invalid login" can only happen if the user does not exists or if the token/salt sent in the http request are invalid. Not sure how this can happen to some requests but not to others.... Maybe your DSub is caching an old password? 

Try to get the _token_ and the _salt_ (`t` and `s` parameters in the HTTP request) from the logs, and validate them using this: https://play.golang.org/p/yV8r01tdUcU (replace the SALT and PASSWORD with your values and check if the generated token matches the token from the HTTP request

The HTTP request should be in the logs with this format:
```
time="2020-12-30T14:38:50Z" level=debug msg="HTTP: GET http://my.server.com/rest/stream.view?u=ted&s=p1rm76iu6d2k3sh1ef8qkp5j1h&t=47349bff5e3db1a57cd9c7f394123e5a&v=1.2.0&c=DSub&id=32a93b168a4c134afbef9b70c744bb1c&maxBitRate=96" elapsedTime=5.766850876s httpStatus=200 remoteAddr=174.89.34.81 requestId=c6d2049fd1a4/Lhbt7H8g9K-005447 responseSize=2199661 userAgent=DSub
```

Use the request that is getting the error, the one that matches the `requestId` from the warning API message.

**Comment by tedder** [comment]
I was going to update this today, I have a strong suspicion that this was caused by running the "data" mount of navidrome on (slow raid5) nfs. I would see complaints about a locked DB and some long timeouts on requests, I suspect that was all related.

I've moved it off of that nfs mount but need to wrap up my testing- I'll leave this issue open until then.

**Comment by tedder** [comment]
Actually, no need to leave it open, a quick google confirmed:

https://www.sqlite.org/faq.html#q5

> SQLite uses reader/writer locks to control access to the database. [..] But use caution: this locking mechanism might not work correctly if the database file is kept on an NFS filesystem. This is because fcntl() file locking is broken on many NFS implementations. You should avoid putting SQLite database files on NFS if multiple processes might try to access the file at the same time. 

Apologies for opening this before checking that assumption!
