### ISSUE TITLE
Transcoding from flac was broken

### ISSUE THREAD

**Issue by rdiff** [deluan/navidrome#71]
In 0.7.3 doesn't work transcoding.
Docker, ultrasonic.

**Comment by deluan** [comment]
Thanks for the report.

Transcoding/Downsampling is a WIP right now. Did you enabled it with ND_ENABLEDOWNSAMPLING=true? 

If so, was it working with previous versions? Can you restart the container with ND_LOGLEVEL=trace, and send to my email the logs? 

(my email can be found in my GitHub profile page)

**Comment by rdiff** [comment]
No, yes, done

**Comment by deluan** [comment]
Thanks for the logs. 

Yeah, based on the logs, it is not even trying to transcode the files, it is just streaming the original (raw) file:
```
level=debug msg="Streaming raw file" id=xxxxxxxxxxxxxxxxxx originalBitrate=822 originalFormat=flac path="/music/Artist/Album/02 Track.flac" requestId=d06d4ea929fb/1FNoP2Z1bz-000039
```

I can't think of anything that changed between 0.7.2 and 0.7.3 that could cause this. Will install Ultrasonic tonight and try to understand what is going on.

**Comment by rdiff** [comment]
Yeah, it's Ultrasonic issue, but transcoding still disabled with
ND_ENABLEDOWNSAMPLING=true, may be this env in another branch?

пн, 10 февр. 2020 г. в 21:07, Deluan Quintão <notifications@github.com>:

**Comment by rdiff** [comment]
Transfer env params to env file, transcoding works nice.
