### ISSUE TITLE
API status is set to "fail" on bad request, not "failed" as in Subsonic

### ISSUE THREAD

**Issue by ta264** [deluan/navidrome#716]
See https://github.com/deluan/navidrome/blob/069199b2d884d4d8dc96e4bc56d639b2bf0d2c9c/server/subsonic/api.go#L207

The subsonic documentation suggests a failed response should have status `failed` and not `fail`.
http://www.subsonic.org/pages/api.jsp

> If a method fails it will return an error code and message in an <error> element. In addition, the status attribute of the <subsonic-response> root element will be set to failed instead of ok. For example:
```
<?xml version="1.0" encoding="UTF-8"?>
<subsonic-response xmlns="http://subsonic.org/restapi" status="failed" version="1.1.0">
   <error code="40" message="Wrong username or password"/>
</subsonic-response>
```

The Lidarr subsonic integration checks for failed, so it doesn't work properly with Navidrome.  For now I can change it to check for not `ok`, but it might be causing issues for other client apps too.

Thanks!

**Comment by deluan** [comment]
Wow! Not sure how this was overlooked for so many time! Thanks for noticing it!
