### ISSUE TITLE
[feature req] scan album comment from file as well as from the tags

### ISSUE THREAD

**Issue by andrewzah** [deluan/navidrome#737]
Hi, would it be possible to set an album comment from something like a `comment.txt`? Some of the albums I own have longer descriptions that are kind of a pain to manage via the `comment` tag.

**Comment by certuna** [comment]
All these messy 1990s-style sidecar files from the days when media files couldn't hold their own metadata is something we all want to get away from, right?

**Comment by deluan** [comment]
Thanks for the suggestion, but as @certuna noted, there's no standard for these sidecar files. I may try to implement support for [CUE files](https://en.wikipedia.org/wiki/Cue_sheet_(computing)) (to support single FLAC albums), and this format supports storing basic metadata. So maybe this will allow you to do what you want (not sure if the CUE format supports album comments, but I think it does). 

Anyway, this discussion is already covered in this issue: https://github.com/deluan/navidrome/issues/497#issuecomment-706724225, so I'm closing this one.
