### ISSUE TITLE
Save log to file for Fail2Ban

### ISSUE THREAD

**Issue by ich777** [deluan/navidrome#740]
Hi,
is there an option to save the log to file?
I'm using the Docker image of the application and would like to add it to my Fail2Ban jail but it seems there is no option to save the log to a file.

Cheers

**Comment by deluan** [comment]
Navidrome tries to follow the [Twelve Factor methodology](https://12factor.net/) as much as possible, and logs in particular are implemented [that way](https://12factor.net/logs), only being sent to stdout, allowing log management tools to handle all logging needs (store, rotate, etc..) I don't plan to introduce any log management features in Navidrome itself.

Having said that, I'm sure there has to be a way to configure fail2ban to parse logs from docker containers, but if you can't find it, one option is to change the command to be run in the container (using the entrypoint/command docker arguments) to something like this:
```
/bin/sh -c /app/navidrome | tee /data/navidrome.log
```

This would allow the logs to be sent to the `navidrome.log` file _in addition_ to the Docker logs

**Comment by ich777** [comment]
For me that is not acceptable and a show stopper so I can't use the Container.

Anyways, thank you for the response.

**Comment by cannibal3004** [comment]
I know this is closed, but i came across this looking for a solution to get logs and thought I would share what I've come up with, in case someone else find this.

If you are using unraid, I found an easy way to get logs from navidrome. This should work with docker run as well if you're not using unraid but you'll need to figure out the syntax.

Tee doesn't seem to work in the docker image, not sure why. I needed to create this simple start script in my data directory "start.sh":

#!/bin/bash
/app/navidrome &> /data/navidrome.log

Then you need to add the entrypoint extra parameters to the container in the advanced view:
Extra Parameters: "--entrypoint "/bin/sh"
Post Arguements: "-c "sh /data/start.sh"

![ExtraParameters](https://user-images.githubusercontent.com/11273301/120235974-d4ced980-c220-11eb-963d-a6bb3cb238da.PNG)

**Comment by deluan** [comment]
Why not configure the container to redirect the logs to syslog, using docker's `--log-driver syslog` option?

See https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers
