### ISSUE TITLE
[feature request] resume playback in webui

### ISSUE THREAD

**Issue by AzMo23425** [deluan/navidrome#744]
Hello and thanks for this awesome project.
Is there any way to save the current position in the playlist or even in the song so you can resume playback where you left off when reloading/closing-reopening the page? Currently the playlist is persistent but playback restarts at the first entry. This feature would be highly appreciated by me and also by my daughter when she's listening to her children's audiobooks.

**Comment by deluan** [comment]
Thanks for trying Navidrome. The API already supports it, and it works among Subsonic clients (ex: Dsub and Sublime), but the Web UI is not using it yet.

This is already being tracked by this issue: https://github.com/deluan/navidrome/issues/245, so I'll close this one as it is a duplicate. Please subscribe to that issue to follow its development or give suggestions.
