### ISSUE TITLE
Docker image not launching on armv6

### ISSUE THREAD

**Issue by oliveconstant** [deluan/navidrome#747]
The latest Docker image does not launch on armv6 (assuming a working `docker-compose.yml` in the working directory):

```
$ docker-compose up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Starting navidrome ... done
Attaching to navidrome
navidrome exited with code 132
```
Furthermore, `docker logs` shows no output for the container.

According to [this](https://old.reddit.com/r/docker/comments/bltx02/container_exits_with_132_with_no_logs/) post, it seems that code 132 means attempting to execute an illegal instruction.

Is Navidrome expected to work on armv6?

**Comment by deluan** [comment]
It should work in armv6. Can you try downloading and running the binary directly: https://github.com/deluan/navidrome/releases/download/v0.39.0/navidrome_0.39.0_Linux_armv6.tar.gz

**Comment by oliveconstant** [comment]
> It should work in armv6. Can you please try downloading and running the binary directly: https://github.com/deluan/navidrome/releases/download/v0.39.0/navidrome_0.39.0_Linux_armv6.tar.gz

The binary works, but I would use Docker if it worked.

**Comment by deluan** [comment]
I just checked and I remembered there is not Docker image for armv6, only armv7 and arm64:

<img width="548" alt="Screen Shot 2021-01-31 at 7 32 08 PM" src="https://user-images.githubusercontent.com/331353/106403143-1b3f3380-63fb-11eb-8539-1d103581a92b.png">

The only way to run Navidrome in Armv6 is to run the binary. I may add the Docker image for armv6 in the next release
