### ISSUE TITLE
Compilations get incorrectly sorted in Album view

### ISSUE THREAD

**Issue by certuna** [deluan/navidrome#93]
![image](https://user-images.githubusercontent.com/62144283/76626112-d5eeea80-6538-11ea-945d-84f880b3b7b8.png)

Compilation albums seem to get inserted into the Album list (sort by Artist) according to the first track artist on that compilation.

Compilation albums should either get their own category in the Library tree on the left (preferred way to handle them I think), or get sorted in the Album list either first before A or last after Z (preference #2), or least ideal, under the "V" for Various Artists.

**Comment by deluan** [comment]
Hummm... They should be under "V" (Various Artists)... I'll check that.

I agree this is not ideal. My idea is to show compilations as the first artist, like iTunes:

<img width="590" alt="Screen Shot 2020-03-13 at 10 02 44" src="https://user-images.githubusercontent.com/331353/76627747-f2c3f780-6511-11ea-9b84-b755451a9fa2.png">


I didn't spent too much time in the Web UI yet. I hope to finish Transcoding (#11) this weekend, and will spent the next week polishing the UI a bit.

**Comment by certuna** [comment]
FYI all these compilations are id3v2.3 tags, have the Album Artist (TPE2) field empty and "Part of Compilation" (TCMP) tag set to true.

**Comment by certuna** [comment]
For what it's worth, iTunes sorts compilations first under the Artist view (as your screenshot shows), but last in the list under the Albums view.

**Comment by deluan** [comment]
> For what it's worth, iTunes sorts compilations first under the Artist view (as your screenshot shows), but last in the list under the Albums view.

Yes, in the album view I plan to do something similar to iTunes's album view.

**Comment by certuna** [comment]
btw I see multiple other sort/filter issues in the UI, does it make sense to open a new issue thread for each or just create a list of them in 1 issue?

**Comment by deluan** [comment]
I think you can go ahead and create multiple issues and I can filter and join as needed (based on their relation in the codebase).

By the way, thanks a lot for helping out!

**Comment by deluan** [comment]
Hey @certuna, now when sorting by Artist, compilations should be grouped together at the end of the list, sorted by title. This is a temporary solution while the album and artist views rework is not finished.

The fix will be part of the next version, but it is already available the `deluan/navidrome:develop` Docker image (it is building right now)

**Comment by deluan** [comment]
I also added a "Compilation" filter in the album view. Should also help navigate your through collection
